- srcpkgs/grc/files/conf.socklog
- srcpkgs/grc/patches/install.sh.patch
- srcpkgs/grc/template
I've tried to make a wrapper for xbps-install, xbps-query etc. but it's still to hackish. Maybe i'll come up with something better. But i've added a conf. file for socklog.
> New package: grc-1.5

- srcpkgs/noip2/files/noip2/run
- srcpkgs/noip2/patches/foreground.patch
- srcpkgs/noip2/patches/prefix.patch
- srcpkgs/noip2/template
No-ip Dynamic DNS Update Client
> New package: noip2-2.1.9_1

- srcpkgs/python-Flask/template
- srcpkgs/python-Werkzeug/template
- srcpkgs/python-itsdangerous/template
- srcpkgs/python3.4-Flask
- srcpkgs/python3.4-Werkzeug
- srcpkgs/python3.4-itsdangerous
New Package python-Flask-0.10.1
New Package python-Werkzeug-0.9.6
New Package python-itsdangerous-0.24
> New Package python-Flask-0.10.1

- srcpkgs/w_scan/template
Re-organized my git history. Sorry for the chaos.
> New package: w_scan-20141122_1

- srcpkgs/spotify/INSTALL
- srcpkgs/spotify/REMOVE
- srcpkgs/spotify/files/spotify
- srcpkgs/spotify/template
- srcpkgs/spotify/update
Version numbers vary significantly between 32 and 64 bit. 0.9 is the smallest common denominator.
xlint claims allow_unknown_shlibs is a custom variable...
> New package: spotify-0.9_1

- srcpkgs/zpaq/template
This commit adds the package "zpaq", for incremental archiving purposes.
The package installs a single binary `zpaq`into /usr/bin.
For more information on this application, please consult the homepage of this package ( http://mattmahoney.net/dc/zpaq.html )
> New package: zpaq

- srcpkgs/tvbrowser/template
- srcpkgs/tvbrowser/update
> New package: tvbrowser-3.4.1.0_1

- srcpkgs/krusader/template
> New package: krusader-2.4.0

- common/shlibs
- srcpkgs/libenet-devel
- srcpkgs/libenet/template
Yadda yadda new package called enet that provides cross-platform reliable UDP, used in games and game engines like 0AD and Cube.
http://enet.bespin.org/
> New package: libenet

- common/shlibs
- srcpkgs/libmosquitto
- srcpkgs/libmosquitto-devel
- srcpkgs/libmosquittopp
- srcpkgs/libmosquittopp-devel
- srcpkgs/mosquitto-clients
- srcpkgs/mosquitto/template
Subpackages:
- libmosquitto{,-devel}
- libmosquittopp{,-devel}
- mosquitto-clients
> New package: mosquitto-1.4

- srcpkgs/sv-helper/template
Utilities for administering runit-as-pid1
> New package: sv-helper-1.0.0

- srcpkgs/daemontools/patches/daemontools-0.76.cross.patch
- srcpkgs/daemontools/template
* Added manpages (from http://smarden.org/djb)
* Added crosscompile patch (from openwrt)
> daemontools: update to 0.76_2

- srcpkgs/clockspeed/files/NOTES
- srcpkgs/clockspeed/files/clockctl
- srcpkgs/clockspeed/files/clockspeed.conf
- srcpkgs/clockspeed/files/clockspeed/finish
- srcpkgs/clockspeed/files/clockspeed/log/run
- srcpkgs/clockspeed/files/clockspeed/run
- srcpkgs/clockspeed/files/clockspeed_adjust/clock_adjust.sh
- srcpkgs/clockspeed/files/clockspeed_adjust/log/run
- srcpkgs/clockspeed/files/clockspeed_adjust/run
- srcpkgs/clockspeed/files/taiclockd/log/run
- srcpkgs/clockspeed/files/taiclockd/run
- srcpkgs/clockspeed/patches/clockspeed-0.62.cross.patch
- srcpkgs/clockspeed/patches/clockspeed-0.62.errno.patch
- srcpkgs/clockspeed/template
clockspeed: remove unused template variable
clockspeed: make arch-specific for x86/x86_64
* Add NOTES about what the package contains
* Add README and INSTALL to docs
clockspeed: depend on sv-helper for supervision
> New package: clockspeed-0.62

- srcpkgs/zpaq/template
Really all there is to it. Some changes have happened, but nothing breaking.
Changes can be found here: http://mattmahoney.net/dc/zpaq.html#history
> zpaq: update to 7.02

- srcpkgs/spotify/template
Incompatibility with new gtk2 versions leading to segmantation faults.
Added precompiled private libraries for gtk2-2.24.24.
> spotify: updated to 0.9_4

- srcpkgs/yakuake/template
> New package: yakuake-2.9.9

- srcpkgs/kvirc/template
> New package: kvirc-4.2.0

- srcpkgs/openjdk/template
Reverts voidlinux/void-packages#1069
> Revert "openjdk: rebuild to generate shlib-provides"

- common/shlibs
- srcpkgs/darktable/template
- srcpkgs/gphoto2/template
- srcpkgs/gvfs/template
- srcpkgs/libgphoto2/template
- srcpkgs/sane/template
- srcpkgs/shotwell/template
- srcpkgs/wine/template
Please note before merging:
libgphoto2 fails currently on i686 with the following error:
```
configure:3730: checking whether the C compiler works
configure:3752: i686-pc-linux-gnu-gcc  -O2 -pipe -fstack-protector-strong -march=i686 -mtune=generic    -D_FORTIFY_SOURCE=2    -Wl,--as-needed   conftest.c  >&5
i686-pc-linux-gnu-gcc: error: unrecognized command line option '-fstack-protector-strong'
```
> libgphoto2 update

- srcpkgs/daemonize/template
-rw-r--r-- root/root      1032 2015-03-06 18:54 ./props.plist
-rw-r--r-- root/root      1107 2015-03-06 18:54 ./files.plist
-rw-r--r-- 0/0            6095 2015-03-06 18:54 ./usr/share/man/man1/daemonize.1
-rwxr-xr-x 0/0           13864 2015-03-06 18:54 ./usr/sbin/daemonize
> New package: daemonize-1.7.5

- srcpkgs/openresolv/patches/runit.patch
- srcpkgs/openresolv/template
> New package: openresolv-3.6.1

- srcpkgs/polkit/template
> polkit: add valid homedir to polkitd

- srcpkgs/lxc/files/lxc-autostart/finish
- srcpkgs/lxc/files/lxc-autostart/run
- srcpkgs/lxc/template
> lxc: added runit support

- srcpkgs/discount-devel
- srcpkgs/discount/template
This package adds the "much-needed" C implemented markdown parser for all your shell-based markdown parsing needs.
http://www.pell.portland.or.us/~orc/Code/discount/
> New package: discount-2.1.8

- srcpkgs/libgnomekbd/template
> add missing hostmakedepends for libgnomekbd

- srcpkgs/leiningen/template
> New package: leiningen-2.5.1

- srcpkgs/tpm/template
tpm is basically a small drop-in replacement for pass (which is already included in void).
> New package: tpm-1.2

- srcpkgs/couchdb/template
> couchdb enable cross build

- srcpkgs/xinit/template
> xinit: Use vlicense

- srcpkgs/handbrake/template
please merge after x264, so handbrake can profit from asm optimizations
> handbrake: update to 0.10.1.

- srcpkgs/spl/template
- srcpkgs/zfs/template
Since those two new versions don't appear on the website I just decided to download them from github…
> zfs and spl update

- common/shlibs
- srcpkgs/filteraudio-devel-git
- srcpkgs/filteraudio-git/template
Audio filter library for use with several TOX clients.
> New package: filteraudio-git-20150310_1

- common/shlibs
- srcpkgs/toxcore-devel-git
- srcpkgs/toxcore-git/template
Library for the TOX instant messenger protocol, used by several clients. I will create pull requests for the clients after this and filteraudio are through.
> New package: toxcore-git-20150309_1

- srcpkgs/wpa_supplicant/files/wpa_supplicant/conf
- srcpkgs/wpa_supplicant/files/wpa_supplicant/log/run
- srcpkgs/wpa_supplicant/files/wpa_supplicant/run
- srcpkgs/wpa_supplicant/template
For running supervised `wpa_supplicant`
> wpa_supplicant: add service directory

- srcpkgs/splix-svn/template
> New package: splix-svn-r315

- srcpkgs/wifish/template
Additional documentation added.
> wifish: update to 0.9.4

- srcpkgs/wifish/template
> wifish: update to 0.9.5

- srcpkgs/afl/template
- srcpkgs/caribou/template
- srcpkgs/exiftool/template
- srcpkgs/glm/template
- srcpkgs/lgi/template
- srcpkgs/libchamplain/template
- srcpkgs/obmenu-generator/template
- srcpkgs/potrace/template
- srcpkgs/qjackctl/template
- srcpkgs/qsynth/template
I'm too tired to push this without review. :)
> Random updates

- srcpkgs/newsbeuter/patches/podbeuter.patch
- srcpkgs/newsbeuter/template
> newsbeuter: added podbeuter patch

- srcpkgs/spotify/INSTALL
- srcpkgs/spotify/template
@Gottox Sorry for making you push the 64bit update. I was holding that back, hoping they would also update the 32bit version and I could do both together. But it seems they won't do that anytime soon :)
> spotify: Fixed extraction for 32bit

- srcpkgs/pulseaudio/files/pulseaudio/run
- srcpkgs/pulseaudio/template
> pulseaudio: add systemwide service.

- srcpkgs/soulseekqt
Hi,
I think Void needs a soulseek client.
I would have prefered to make a nicotine-plus package, but it's too complex for me.
It's my first attempt to make a Void package, so be indulgent, please.
I don't know how to upload the Files directory with the png and the desktop files, I'll try later.
> New package: : SoulseekQt-2014-11-30

- srcpkgs/distcc/files/distccd/run
- srcpkgs/distcc/template
Improvement as discussed in issue #1367
TODO: update README.md to explain how to add a host list or network mask to /etc/distcc/clients.allow
> Make /etc/sv/distccd/run use /etc/distcc/clients.allow

- srcpkgs/axel/template
Doesn't compile on mips and mipsel.
> New package: axel-2.4

- hatari/template
I'm sorry, I don't know how to rebase.
And there were no reasons to justify the updated templates, I'm just discovering the whole thing.
> New package: hatari-1.8.0

- srcpkgs/rng-tools/files/rngd/finish
- srcpkgs/rng-tools/files/rngd/run
- srcpkgs/rng-tools/patches/rngd-test-signal-in-loop.patch
- srcpkgs/rng-tools/template
> New package: rng-tools-5

- srcpkgs/pdftk/files/Makefile
- srcpkgs/pdftk/template
> New package: pdftk-2.02

- srcpkgs/darktable/template
hopefully they are not falling back to dayly releases again :)
> darktable: update to 1.6.6.

- srcpkgs/libcgroup/files/cgred/run
- srcpkgs/libcgroup/libcgroup-utils.INSTALL
- srcpkgs/libcgroup/template
* added system group cgred
* added service /etc/sv/cgred
* Two conf files, /etc/cgrules.conf and /etc/cgconfig.conf
> libcgroup: add cgred service and group

- srcpkgs/qtcreator/files/qtcreator.desktop
- srcpkgs/qtcreator/template
> New package: qtcreator-3.4.0

- srcpkgs/glibc/patches/glibc-32bit-regression.patch
- srcpkgs/glibc/patches/glibc-security-buflen.patch
- srcpkgs/glibc/template
> glibc: Add security buflen and 32bit regression patches

- xbps-src
> xbps-src: Use CCACHE_PREFIX for ccache+distcc

- srcpkgs/iputils/patches/net-misc_iputils_files_iputils-20131208-remove-working_recverr-checks.patch
- srcpkgs/iputils/template
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=709052
> iputils: patch working_recverr

- srcpkgs/sdlmame/files/sdlmess.sh
- srcpkgs/sdlmame/template
- srcpkgs/sdlmess
+ Depend on lua-devel for new build system (genie)
+ Fix xlint warnings
+ Add sub package sdlmess for Multi Emulator Super System
> sdlmame: update to 0.161

- srcpkgs/zfs/files/zfs-import/finish
- srcpkgs/zfs/files/zfs-import/run
- srcpkgs/zfs/template
This is necessary  for LUKS encrypted pools.
> add pool import service

- srcpkgs/thinkfan/files/thinkfan/run
- srcpkgs/thinkfan/template
add the service script for thinkfan, configuration must be create by user
> thinkfan: add service script

- srcpkgs/freefall
- srcpkgs/linux-tools/files/freefall/run
- srcpkgs/linux-tools/template
Moved the package to a linux-tools subpkg as per xtraeme's recommendation. Also, fixed the service file to read the ./conf file and options from it.
> linux-tools: added a freefall subpkg

- srcpkgs/xfce4-whiskermenu-plugin/template
> New package: xfce4-whiskermenu-plugin-1.5.0

- srcpkgs/drbd-utils/files/drbd/finish
- srcpkgs/drbd-utils/files/drbd/run
- srcpkgs/drbd-utils/template
drbd is messy. So I did my best to clean up. :)
> New package: drbd-utils-8.9.2

- srcpkgs/mpfr/patches/mpfr-3.1.2-upstream_fixes-2.patch
- srcpkgs/mpfr/template
Imported from LFS (http://www.linuxfromscratch.org/lfs/view/development/chapter06/mpfr.html)
For the source see: http://www.mpfr.org/mpfr-current/allpatches
> mpfr: Import upstream fixes for 3.1.2 (p11)

- srcpkgs/bc/patches/bc-1.06.95-memory_leak-1.patch
- srcpkgs/bc/template
Imported from LFS (http://www.linuxfromscratch.org/lfs/view/development/chapter06/bc.html)
> bc: fix memory leak patch from LFS

- srcpkgs/cubietruck-base/INSTALL
- srcpkgs/cubietruck-base/template
> New package: cubietruck-base

- srcpkgs/pidgin-libnotify/patches/pidgin-libnotify-0.14-libnotify-0.7.patch
- srcpkgs/pidgin-libnotify/patches/pidgin-libnotify-getfocus.patch
- srcpkgs/pidgin-libnotify/patches/pidgin-libnotify-showbutton.patch
- srcpkgs/pidgin-libnotify/template
> New package: pidgin-libnotify-0.14

- srcpkgs/smplayer/template
Note:
Since this version smplayer is able to work against mpv. I have no idea how to make it depend on mplayer OR smplayer since I haven't noticed anything like this in docs.
> smplayer: update to 14.9.0.6887

- srcpkgs/subtle/template
> New package: subtle-0.11

- srcpkgs/monkey/template
This commit should, hopefully, fix the remaining issues with monkey, and making it work across platforms too.
Musl support has not yet been enabled, but should hopefully be a breeze too.
> monkey: fix cross-compilation issues.

- srcpkgs/nomacs-qt5/template
- srcpkgs/nomacs/template
Is ${_pkg} a good way to do it?
//Thanks devs, it's probably the distro I was wishing for a long time
> New packages: nomacs, nomacs-qt5

- srcpkgs/units/template
Tells you how to convert between different units.
> New package: units-2.11

- srcpkgs/re2c/template
This program partially builds itself and isn't meant to be cross compiled, but if the host compiler is the same as the target compiler it should be fine.
> New package: re2c-0.14.2

- srcpkgs/inetutils/template
> inetutils: fix typo in ifconfig package

- srcpkgs/dhcp/template
https://crux.nu/bugs/index.php?do=details&task_id=746
> dhcp: fix missing dhclient-script

- srcpkgs/deutex/patches/32ebc7c-freedoom.patch
- srcpkgs/deutex/patches/f4f4176-segfault.patch
- srcpkgs/deutex/patches/fix-cross-compile.patch
- srcpkgs/deutex/patches/fix-musl.patch
- srcpkgs/deutex/template
Includes 2 upstream commits as patches and minimal changes by me.
> New package: deutex-4.4.902

- common/shlibs
- srcpkgs/codeblocks-devel
- srcpkgs/codeblocks/template
> New package: codeblocks-13.12

- srcpkgs/ipset/template
I accidentally the -devel, sorry about that :sob:
> ipset: fix broken dependency for -devel

- srcpkgs/deutex/update
Update file adapted from the docker package.
> deutex: fix update checking

- srcpkgs/radeontop/template
> New Package: radeontop-0.8

- srcpkgs/starplot/template
Need a star chart, adding that in as soon as this builds correctly.
> New package: starplot-0.95.5

- srcpkgs/dmraid/patches/25_musl-libc.patch
- srcpkgs/dmraid/patches/series
- srcpkgs/dmraid/template
> dmraid: fixes for musl

- srcpkgs/arptables/files/arptables/finish
- srcpkgs/arptables/files/arptables/run
- srcpkgs/arptables/patches/makefile-cflags.patch
- srcpkgs/arptables/template
- srcpkgs/arptables/update
Runit service shamelessly lifted from ``ebtables``.
> New package: arptables-0.0.4

- common/hooks/pre-configure/02-script-wrapper.sh
- srcpkgs/network-ups-tools/template
This also fixes cross compiles against net-snmp
> network-ups-tools: enable snmp module

- srcpkgs/vte3/template
I hope this doesn't break the revdeps:
```
anjuta-3.14.1_1
gnome-color-manager-3.14.2_1
gnome-terminal-3.14.3_1
vinagre-3.14.3_1
```
> vte3: update to 0.40.2

- srcpkgs/hooktftp/template
I'm currently getting the latest git version even if they are preparing to release the 1.0.0 version.
#1687
> New package: hooktftp-1.0.0

- srcpkgs/cinnamon-control-center/template
- srcpkgs/cinnamon-desktop/patches/fix-build.patch
- srcpkgs/cinnamon-desktop/template
- srcpkgs/cinnamon-menus/template
- srcpkgs/cinnamon-screensaver/template
- srcpkgs/cinnamon-session/template
- srcpkgs/cinnamon-settings-daemon/template
- srcpkgs/cinnamon-translations/template
- srcpkgs/cinnamon/patches/set_wheel.patch
- srcpkgs/cinnamon/template
- srcpkgs/muffin/template
- srcpkgs/nemo/template
Tested x86_64 in virtualbox and native
Not tested on musl though.
> Cinnamon 2.6

- srcpkgs/lutris/template
> New Package: lutris-0.3.6.3

- srcpkgs/font-hanazono/template
Correcting the problem of commits. #1741
> New Package: font-hanazono-20141012

- srcpkgs/qtpass/template
> New package: qtpass-0.8.3 

- srcpkgs/OpenXcom/INSTALL.msg
- srcpkgs/OpenXcom/template
Won't build on ARM because it uses GL.
Requires [data files from the original game](http://www.myabandonware.com/game/x-com-ufo-defense-1pl).
> New package: OpenXcom-1.0

- srcpkgs/libgit2-glib-devel
- srcpkgs/libgit2-glib/template
This is for ``gitg`` as requested by #1207. It doesn't want to build without gir.
> New package: libgit2-glib-0.22.8

- srcpkgs/fcron/INSTALL
- srcpkgs/fcron/files/fcron/run
- srcpkgs/fcron/files/systab.orig
- srcpkgs/fcron/patches/fcron.patch
- srcpkgs/fcron/template
> New package: fcron-3.2.0

- srcpkgs/kpcli/template
- srcpkgs/perl-Clone/template
- srcpkgs/perl-Crypt-Rijndael/patches/use-stdint_h.patch
- srcpkgs/perl-Crypt-Rijndael/template
- srcpkgs/perl-File-KeePass/template
- srcpkgs/perl-Sort-Naturally/template
- srcpkgs/perl-Term-ShellUI/template
> Add kpcli package

- common/shlibs
- srcpkgs/skalibs-devel
- srcpkgs/skalibs/template
Need to figure out how we want to work the skalibs.cfg for cross building. See http://www.skarnet.org/software/skalibs/crosscompile.html
> New package: skalibs-2.3.5.1

- srcpkgs/cdecl/template
- srcpkgs/cdecl/update
Can translate c type definitions into English and back.
> New package: cdecl-2.5

- srcpkgs/python-Pyro4/template
- srcpkgs/python-serpent/template
- srcpkgs/python3.4-Pyro4
- srcpkgs/python3.4-serpent
python-Pyro4 depends on New package: python-serpent
> New package: python-Pyro4

- srcpkgs/cheese/template
- srcpkgs/liferea/template
- srcpkgs/mousetweaks/template
- srcpkgs/nautilus-sendto/template
- srcpkgs/rhythmbox/template
- srcpkgs/rygel/template
- srcpkgs/sushi/template
- srcpkgs/totem/template
Make some more packages possibly cross compilable.
> gnome: add build option gir

- srcpkgs/gpm/files/gpm.service
- srcpkgs/gpm/patches/musl-fcntl.patch
- srcpkgs/gpm/patches/musl-gpm_h.patch
- srcpkgs/gpm/patches/musl-linux_major_h.patch
- srcpkgs/gpm/patches/musl-select.patch
- srcpkgs/gpm/patches/musl-sigaction.patch
- srcpkgs/gpm/template
This has to be tested on a musl box. I'm not sure the SA_INTERRUPT flag bit for sigaction works and causes no harm.
> gpm: unbreak musl

- srcpkgs/vte290/template
Thank you @thypon for the simpler fix.
> vte290: unbreak musl

- srcpkgs/signify/files/void.h
- srcpkgs/signify/template
Travis fails because of @Ypnose email addy
> signify: unbreak build (#1779)

- srcpkgs/file/patches/001-fix-bug-with-long-options.patch
- srcpkgs/file/template
https://github.com/file/file/commit/21f9d5f0e0340ada998f7f9d316368c7167a4afa
> file: fix long options

- srcpkgs/mame/template
+ Also adopt maintainership from Juan RP per his suggestion.
> mame: update to 0.163

- srcpkgs/obs/patches/0001-musl.patch
- srcpkgs/obs/template
Open Broadcaster Software Alpha Release
> New package: obs-0.10.1

- srcpkgs/net-tools/template
+ The home page returns _403: Forbidden_ thus switch to sourceforge
+ The most recent update to the repo was on 2015-05-26
> net-tools: unbreak musl

- srcpkgs/rsyslog/patches/musl-glob.patch
- srcpkgs/rsyslog/template
+ The next update (0.8.11) is coming soon
> rsyslog: unbreak musl + remove systemd option

- srcpkgs/enlightenment/template
> enlightenment: remove systemd build option (#1736)

- common/xbps-src/shutils/purge_distfiles.sh
- xbps-src
> xbps-src: Add purge-distfiles command

- common/shlibs
- srcpkgs/qupzilla/patches/musl-execinfo.patch
- srcpkgs/qupzilla/template
Closes #1968
Should be merged after #1957
> New package: qupzilla-1.8.6

- srcpkgs/gnome-icon-theme-xfce/template
> New package: gnome-icon-theme-xfce-0.6

- common/shlibs
- srcpkgs/libgadu-devel
- srcpkgs/libgadu/patches/musl-sys_types.h
- srcpkgs/libgadu/template
This is required for kadu (request #1969)
> New package: libgadu-1.12.1

- srcpkgs/linux/template
> Linux: update to 4.1.

- srcpkgs/parole/template
> New package: parole-0.8.0

- srcpkgs/xscreensaver/template
The checksum doesn't match anymore. No version change, though.
Perhaps someone who has the old version can find out what changed?
> xscreensaver: distfile checksum changed

- srcpkgs/xmlrpc-c/template
This fixes the issue for *-musl
> xmlrpc-c: Fix building of shlibs for musl libc

- srcpkgs/libinput/template
- srcpkgs/xf86-input-libinput/template
No shlib bump for this version.
> Libinput 0.19

- srcpkgs/hunspell-hr_HR/template
It's not very new, but there is no better option and it works - tested within Weechat.
Sincerely,
Gour
> New package: hunspell-hr_HR-20030928

- common/shlibs
- srcpkgs/anthy/template
- srcpkgs/ibus-anthy/template
and anthy-9100h
Maybe I should have done 2 PR for this?
> New package: ibus-anthy-1.5.6

- srcpkgs/partclone/patches/musl.patch
- srcpkgs/partclone/template
It's generally a good idea to make a backup of your old OS before installing a new OS. This can help tremendously with that.
> New package: partclone-0.2.79

- srcpkgs/vte/patches/scroll_region.patch
- srcpkgs/vte/template
> vte: add patch for fixing scroll region glitches

- srcpkgs/vlc/template
Compiling vlc with lua can be useful for the web interface and probably other things.
> vlc: change lua to a build option.

- srcpkgs/nwipe/patches/musl.patch
- srcpkgs/nwipe/template
When you see a black van parked outside and a wifi network named ``FBI_SURVEILLANCE_VAN``, this is for you.
> New package: nwipe-0.17

- srcpkgs/bogofilter/template
bumping revision due to rm-ing extra sample file.
> bogofilter: rm sample conf file

- srcpkgs/albatross-themes/template
- srcpkgs/blackbird-themes/template
- srcpkgs/bluebird-themes/template
- srcpkgs/greybird-themes/template
- srcpkgs/numix-themes/template
Some of greatest GTK themes from [Shimmer Project](https://github.com/shimmerproject) - Numix and rest of family.
Fixes #1717
> Shimmer themes

- srcpkgs/tarsnap/template
New package with 'proprietary' license and 'restricted' for distribution, but ready for local builds.
Sincerely,
Gour
> New package: tarsnap-1.0.35

- srcpkgs/alsa-lib/patches/stdint_compat.patch
- srcpkgs/alsa-lib/template
> alsa-lib: Patch pcm.h for musl libc compatibility

- srcpkgs/apulse/template
> New package: apulse-0.1.6

- common/hooks/post-extract/00-patches.sh
- common/xbps-src/libexec/xbps-src-dobuild.sh
- common/xbps-src/libexec/xbps-src-doconfigure.sh
- common/xbps-src/libexec/xbps-src-doextract.sh
- common/xbps-src/libexec/xbps-src-doinstall.sh
- srcpkgs/quimup/patches/quimup.patch
- srcpkgs/quimup/template
:musical_note: A pretty good qt5 mpd client. It currently does have a space in place of ``-`` in the ``wrksrc``, which broke xbps-src. This is fixed in a separate commit. :musical_note:
> New package: quimup-1.4.0

- README.md
Closes #1367
Native speakers please proof read :beers:
> README.md: Improve description of distcc usage

- srcpkgs/dovecot-plugin-pigeonhole-devel
- srcpkgs/dovecot-plugin-pigeonhole/template
This depends on https://github.com/voidlinux/void-packages/pull/2195
> Add dovecot pigeonhole plugin

- srcpkgs/love/template
fix https://github.com/voidlinux/void-packages/pull/2106
> New package: love-0.9.2 (thanks @anarat)

- srcpkgs/octoxbps/template
> New package: octoxbps-0.1.0

- srcpkgs/opencl2-headers/template
They changed them! No idea what's different, perhaps someone with old sources could compare?
> opencl2-headers: fix checksums

- srcpkgs/supertux2-data
- srcpkgs/supertux2/template
- srcpkgs/supertux2/update
> New package: supertux2-0.3.5a

- srcpkgs/gogs/INSTALL
- srcpkgs/gogs/files/gogs.ini
- srcpkgs/gogs/files/gogs/conf
- srcpkgs/gogs/files/gogs/run
- srcpkgs/gogs/template
Gogs is a self-hosted git service written in Go.
http://gogs.io/
I'm not sure if my 'export CGO_ENABLED=1' is redundant or not.
> New package: gogs

- srcpkgs/supertuxkart-data
- srcpkgs/supertuxkart/patches/musl_no_sys_sysctl_h.patch
- srcpkgs/supertuxkart/patches/musl_valist.patch
- srcpkgs/supertuxkart/template
+ Split data into noarch subpkackage
> supertuxkart: unbreak musl

- srcpkgs/gradle/files/gradle
- srcpkgs/gradle/template
The load script was back in 2.3...
> gradle: update to version 2.6

- srcpkgs/ecryptfs-utils/template
Several of these utilities use <code>gettext</code> to display messages/prompts
> ecryptfs-utils: Add gettext to depends

- srcpkgs/abcm2ps/template
the makefile/configure doesn't honor destdir and the makefile installs to /usr/local/bin, so i decided to do the install manually.
> New package: abcm2ps-7.8.14

- srcpkgs/libtirpc/patches/fix_missing_rpc_get_default_domain+fix_musl.patch
- srcpkgs/libtirpc/template
fixes musl build, but I'm not 100% sure if it has any side effects as I'm a autoconf noob.
> libtirpc: fix musl.

- srcpkgs/lmms/template
> New Package: lmms-1.1.3

- Manual.md
- common/build-style/qmake.sh
Tested it with qtcreator and qupzilla which looked good.
I'll adapt the templates later on when this pr got merged.
> xbps-src: New build-style qmake

- srcpkgs/ulatencyd/patches/0003-ulatencyd-lua_binding-.c-removed-unused-headers.patch
- srcpkgs/ulatencyd/patches/0004-fts-add-bsd-implementation.patch
- srcpkgs/ulatencyd/template
@pullmoll this should fix also musl problems.
> ulatencyd: fix musl

- srcpkgs/ent/template
A Public-Domain pseudo random number quality tester.
http://www.fourmilab.ch/random/
> New package: ent-2008.01.28

- srcpkgs/pdf2htmlEX/template
> New Package: pdf2htmlEX-0.14.6

- srcpkgs/libmemcached-devel
- srcpkgs/libmemcached-docs
- srcpkgs/libmemcached/patches/libmemcached-fix-linking-with-libpthread.patch
- srcpkgs/libmemcached/patches/musl-fixes.patch
- srcpkgs/libmemcached/template
> New package: libmemcached

- common/shlibs
- srcpkgs/Cutegram/template
- srcpkgs/TelegramQML-devel
- srcpkgs/TelegramQML/template
- srcpkgs/libqtelegram-ae-devel
- srcpkgs/libqtelegram-ae/template
> New Package: Cutegram

- srcpkgs/rmlint/patches/musl-fts.patch
- srcpkgs/rmlint/template
> New package: rmlint-2.2.0

- srcpkgs/massren/template
@dominikh go-sqlite3 is a problem. nocross is necessary?
> New package: massren-1.3.0

- srcpkgs/firejail/files/musl_defs.h
- srcpkgs/firejail/template
+ Also fix musl libc
Closes #2193
> firejail: update to 0.9.28

- srcpkgs/gflags/template
The directory doc/ contains a html and css files, that is why I install it's files.
> New package: gflags-2.1.2

- srcpkgs/dracut/patches/musl-__wordsize.patch
- srcpkgs/dracut/template
See http://build.voidlinux.eu/builders/armv7l-musl_builder/builds/3824/steps/shell_3/logs/stdio
> dracut: fix cross compiling for musl

- srcpkgs/mimms/template
Downloads mms(h) streams to a wmv file
> New package: mimms-3.2

- srcpkgs/moe/template
New text editor, yay!
(PS, haven't forgotten about tidy5, will do that too)
> New package: moe-1.7

- common/shlibs
- srcpkgs/alsa-tools-devel
- srcpkgs/alsa-tools/patches/musl-__sighandler_t.patch
- srcpkgs/alsa-tools/template
- srcpkgs/python-alsa/template
- srcpkgs/python-alsa/update
> New package: alsa-tools-1.0.29

- srcpkgs/faad2/patches/fix-stack_usage.patch
- srcpkgs/faad2/template
> faad2: try to fix crash in icecat/firefox

- common/shlibs
- srcpkgs/spectrwm/template
Small dynamic tiling window manager, nice BSD-style makefiles :>
Fixes #2506
> new package: spectrwm

- srcpkgs/bomi/template
Qt5 multimedia player with good appearance, supports many formats locally, as well as streaming (youtube and so on)
Fixes #1556
> new package: bomi

- srcpkgs/fpc/template
Originally done by @chneukirchen , but he didn't want to maintain it due to upcoming 3.0.0 release,
We can merge it now, but I should look up into unwrapping ARM archives in the next days.
Fixes #2509 and opens way to do #2126
> new package: fpc

- srcpkgs/duff/template
Useful command-line tool for finding identical files - duplicate file finder.
> New package: duff-0.5.2

- srcpkgs/burp-client
- srcpkgs/burp-server/files/burp-server/run
- srcpkgs/burp-server/patches/00.burp_ca.patch
- srcpkgs/burp-server/template
- srcpkgs/burp-server/update
backup and restore program with a client/server architecture. 
Storage is disk based, simplier than bacula.
Home Page: http://burp.grke.net
> New package: burp 1.4.40

- srcpkgs/ampache/files/nginx-example.conf
- srcpkgs/ampache/template
> New package: ampache-3.8.0

- srcpkgs/xinput_calibrator/template
Very useful package for calibrating touchscreen devices.
> New Package: xinput_calibrator 0.5.7

- srcpkgs/ntp/template
Needed for setting up a Stratum-1 ntp server...
> ntp: add pps-tools-devel makedepends to try and get ATOM PPS working

- srcpkgs/freeplane/files/freeplane.desktop
- srcpkgs/freeplane/template
> New package: freeplane-1.3.15

- srcpkgs/hedgewars-data
- srcpkgs/hedgewars/template
Finally :)
One of my favourite games, closes one of many tasks in #2097
> new package: hedgewars

- srcpkgs/font-awesome/template
Install the font font awesome, an iconic font.
Hi,
This is my first package. I got the inspiration from font-sourcecodepro package.
I hope it is good. If not I am ready to change my template to make it perfect :)
Thank you!
> new package: font-awesome

- srcpkgs/gnurobbo/files/gnurobbo.desktop
- srcpkgs/gnurobbo/template
> New package: gnurobbo-0.66

- srcpkgs/wiggle/template
wiggle is like patch but will apply patches that patch would reject.
> New package: wiggle-1.0

- srcpkgs/wvstreams/patches/wvstreams-4.6.1-argp-fpic.patch
- srcpkgs/wvstreams/patches/wvstreams-4.6.1-modulemgr-limits.patch
- srcpkgs/wvstreams/patches/wvstreams-4.6.1-wvconfemu-execinfo.patch
- srcpkgs/wvstreams/patches/wvstreams-4.6.1-wvcrash-basename.patch
- srcpkgs/wvstreams/patches/wvstreams-4.6.1-wvcrash-execinfo.patch
- srcpkgs/wvstreams/patches/wvstreams-4.6.1-wvtask-libc_stack_end.patch
- srcpkgs/wvstreams/patches/wvstreams-4.6.1-wvtask-ucontext.patch
- srcpkgs/wvstreams/template
I'm pretty sure that some of these patches are inadequate, but it builds, so I'd like to know how I can make them better please. Thanks.
> wvstreams: add musl support

- srcpkgs/sl/template
Okay, it's unnecessary, but fun.
> New package: sl-5.02

- srcpkgs/openimageio/template
- srcpkgs/openimageio/update
> openimageio: update to 1.5.20.

- srcpkgs/xf86-video-mga/patches/composite-fixup.patch
- srcpkgs/xf86-video-mga/patches/fix-exa-support.patch
- srcpkgs/xf86-video-mga/patches/fix-function-call-type.patch
- srcpkgs/xf86-video-mga/patches/remove-download-from-screen.patch
- srcpkgs/xf86-video-mga/patches/write-combining.patch
- srcpkgs/xf86-video-mga/template
Yes, I really have a box with a Matrox PCI card here and VESA just doesn't cut it.
> New package: xf86-video-mga-1.6.4

- srcpkgs/python-requests-toolbelt/template
- srcpkgs/python3.4-requests-toolbelt
Another dependency I need to get vdirsyncer working
> New package: python-requests-toolbelt-0.4.0

- srcpkgs/python-colorama/template
- srcpkgs/python3.4-colorama
Another (transitive) dependency needed for vdirsyncer.
> New package: python-colorama-0.3.3

- srcpkgs/radicale/files/radicale/log/run
- srcpkgs/radicale/files/radicale/run
- srcpkgs/radicale/template
first time creating system account and service files, maybe someone should have a look before merge :)
> New package: radicale-1.0.1

- srcpkgs/actiona/files/actiona.desktop
- srcpkgs/actiona/patches/fix-progress_dlg.patch
- srcpkgs/actiona/patches/fix-qt5.5.0.patch
- srcpkgs/actiona/patches/no-updater.patch
- srcpkgs/actiona/template
> New package: actiona-3.9.0

- srcpkgs/freshplayerplugin/template
Just FYI, I haven't tested this (couldn't get the previous versions to work).
> freshplayerplugin: update to 0.3.3

- srcpkgs/jhead/template
simple program for showing and editing JPEG EXIF data
> New package: jhead-3.00

- common/shlibs
- srcpkgs/libvterm-devel
- srcpkgs/libvterm/template
Neovim dep. I asked the author about a versioned release, he wasn't too interested to do so.
> New package: libvterm-0.0.20151005

- srcpkgs/freetype/template
> freetype: update ultimate patchset to 2015-10-05.

- srcpkgs/xdebug/INSTALL.msg
- srcpkgs/xdebug/template
close https://github.com/voidlinux/void-packages/pull/2492
> New package: xdebug-2.3.3 (thanks @asafo)

- srcpkgs/anki/template
> New package: anki-2.0.33

- srcpkgs/python-click-threading/template
- srcpkgs/python3.4-click-threading
This is a new dependency for the latest version of vdirsyncer.
> New package: python-click-threading-0.1.2

- srcpkgs/python-click-log/template
- srcpkgs/python3.4-click-log
another new vdirsyncer dependency
> New package: python-click-log-0.1.1

- srcpkgs/linux3.18/template
Update package linux3.18 from 3.18.22 to 3.18.23
> linux3.18: update to 3.18.23

- srcpkgs/linux3.14/template
Update the linux3.14 package from 3.14.54 to 3.14.56
> linux3.14: update to 3.14.56

- srcpkgs/w3m/patches/form.patch
- srcpkgs/w3m/patches/perl.patch
- srcpkgs/w3m/template
Some patches to fix:
- w3m help menu
- w3mman
- form field issues
> w3m: patch to fix w3mhelp.cgi and w3mman2html.cgi.

- srcpkgs/autoconf-archive/template
- srcpkgs/workrave/patches/configure_ac.patch
- srcpkgs/workrave/patches/musl-nl_langinfo.patch
- srcpkgs/workrave/template
> New package: workrave-1.10.8.

- srcpkgs/zulip-desktop/template
zulip desktop app, see: https://zulip.org/
> New package: zulip-desktop-0.5.1

- srcpkgs/pgadmin3/template
> New package : pgadmin3 1.20.0

- srcpkgs/chef-client/template
Using PR to see if travis likes it.
> New package: chef-client-12.5.1

- srcpkgs/libu2f-server-devel
- srcpkgs/libu2f-server/patches/disable-help2man.patch
- srcpkgs/libu2f-server/template
- srcpkgs/libu2f-server/update
Furthur package additions moving torwards U2F support in Void's PAM-stack.
> New Package: libu2f-server v1.0.1

- srcpkgs/yandex-disk/template
https://github.com/voidlinux/void-packages/issues/2943
> New package: yandex-disk-0.1.5.940

- srcpkgs/thefuck/template
This time I tested it, sorry for making you fix it last time @xtraeme (so basically it works now)
> New Package: thefuck-3.2

- common/hooks/do-fetch/00-distfiles.sh
We're already done after the first loop, if all distfiles
were found and their checksums verified ok.
> 00-distfiles.sh: avoid unnecessary second loop

- srcpkgs/libmediainfo/template
- srcpkgs/libzen/template
- srcpkgs/libzen/update
- srcpkgs/mediainfo/template
Is this ok? Package update and revision bump to rebuild in a single pull request.
> libzen: update to 0.4.32

- Manual.md
Referenced to me in #2995, I didn't see it in the manual, so here it is.
New PR due to extraneous commits.
> Add nopie to the manual

- common/environment/install/extglob.sh
- common/environment/pkg/extglob.sh
- common/hooks/do-pkg/00-gen-pkg.sh
- common/hooks/pre-pkg/99-pkglint.sh
Depends on https://github.com/voidlinux/void-packages/pull/2934
> globs files defined in conf_files=

- srcpkgs/links/template
> New package: links-2.12.

- srcpkgs/haproxy/patches/haproxy-1.6.2-libressl.patch
- srcpkgs/haproxy/template
> haproxy: update to 1.6.2.

- srcpkgs/javahelp2/patches/fix-build_xml.patch
- srcpkgs/javahelp2/template
- srcpkgs/lightzone/patches/fix-openmp.patch
- srcpkgs/lightzone/template
I'm not sure if the `replaces="lightzone-bin>=0"` is acceptable. If it is, please merge.
> New package: lightzone-4.1.4

- common/shlibs
- srcpkgs/libpam-mount
- srcpkgs/libpam-mount-devel
- srcpkgs/pam-mount/template
> New package: pam-mount-2.15

- srcpkgs/i3-gaps/template
Git sucks, so I needed to recreate this brach. Now with correct musl fixes.
> new package: i3-gaps

- common/shlibs
- srcpkgs/libosmgpsmap-devel
- srcpkgs/libosmgpsmap-doc
- srcpkgs/libosmgpsmap/template
> New package: libosmgpsmap-1.1.0

- common/shlibs
- srcpkgs/flickcurl-devel
- srcpkgs/flickcurl-doc
- srcpkgs/flickcurl/template
> New package: flickcurl-1.26

- srcpkgs/love/template
> love: update to 0.10.0.

- srcpkgs/rofi/template
> rofi: update to 0.15.12

- srcpkgs/quasselcore/files/quasselcore/run
- srcpkgs/quasselcore/template
Compiles the server part for the already existing package `quasselclient`
> New package: quasselcore-0.12.2

- srcpkgs/retroshare/files/retroshare.desktop
- srcpkgs/retroshare/patches/retroshare06-libupnp.patch
- srcpkgs/retroshare/patches/retroshare06-novoip.patch
- srcpkgs/retroshare/template
Skipped voip plugin for now because the build is broken
> New package: retroshare-0.6.0.RC2

- srcpkgs/perl-B-Hooks-EndOfScope/template
- srcpkgs/perl-Class-Load/template
- srcpkgs/perl-Class-Singleton/template
- srcpkgs/perl-DateTime-Locale/template
- srcpkgs/perl-DateTime-TimeZone/template
- srcpkgs/perl-DateTime/template
- srcpkgs/perl-Dist-CheckConflicts/template
- srcpkgs/perl-Module-Implementation/template
- srcpkgs/perl-Package-Stash-XS/template
- srcpkgs/perl-Package-Stash/template
- srcpkgs/perl-Params-Validate/template
- srcpkgs/perl-namespace-clean/template
* perl-DateTime-1.21
* perl-DateTime-TimeZone-1.94
* perl-Class-Singleton-1.5
* perl-Class-Load-0.23
* perl-namespace-clean-0.26
* perl-Package-Stash-0.37
* perl-Package-Stash-XS-0.28
* perl-Dist-CheckConflicts-0.11
* perl-B-Hooks-EndOfScope
* perl-DateTime-Locale 1.02
* perl-Params-Validate-1.18
* perl-Module-Implementation-0.09
> New perl packages

- .gitattributes
This will reduce merge conflicts for common/shlibs.
> set merge driver union for common/shlibs.

- srcpkgs/mpv/template
enable nnedi prescaler for example
> mpv: --enable-gpl3, change license for more features

- srcpkgs/ibus-anthy/template
> ibus-anthy: fix libexec path

- srcpkgs/diction/template
GNU writing style checkers diction/style.
> New package: diction-1.11

- srcpkgs/mypaint/template
This is the stable build of MyPaint.
> mypaint: update to 1.2.0

- srcpkgs/NetworkManager/patches/musl.patch
- srcpkgs/NetworkManager/template
- srcpkgs/network-manager-applet/template
Patches are taken from alpine.
> NetworkManager update to 1.0.10

- srcpkgs/cross-aarch64-linux-gnu/template
- srcpkgs/cross-aarch64-linux-musl/template
- srcpkgs/cross-arm-linux-gnueabi/template
- srcpkgs/cross-arm-linux-gnueabihf/template
- srcpkgs/cross-arm-linux-musleabi/template
- srcpkgs/cross-arm-linux-musleabihf/template
- srcpkgs/cross-armv7l-linux-gnueabihf/template
- srcpkgs/cross-armv7l-linux-musleabihf/template
- srcpkgs/cross-i686-linux-musl/template
- srcpkgs/cross-i686-pc-linux-gnu/template
- srcpkgs/cross-mips-linux-musl/template
- srcpkgs/cross-mipsel-linux-musl/template
- srcpkgs/cross-mipsel-linux-muslhf/template
- srcpkgs/cross-x86_64-linux-musl/template
- Do not remove SYSROOT/bin symlink.
- Update glibc and linux headers.
- Sensible licenses=.
Should fix #3395.
> cross-*: update to 0.21.

- srcpkgs/smali/template
- code moved to github.com/JesusFreke/smali
- downloads moved to bitbucket.org/JesusFreke/smali
- added license
> smali: update to 2.1.1.

- srcpkgs/xbattmon/template
> xbattmon: update distfiles

- srcpkgs/openvpn/patches/fix-build-with-libressl.patch
- srcpkgs/openvpn/template
Patch taken from upsteam git master for libressl compat.
> openvpn: update to 2.3.10.

- srcpkgs/SDL2/template
The old url 404s.
**NOTE**: the checksum changed.
> SDL2: update distfiles

- srcpkgs/irssi/template
> irssi: update distfiles

- srcpkgs/mhddfs/template
> New package: mhddfs-0.1.39

- srcpkgs/giblib/template
- srcpkgs/scrot/template
`http://linuxbrit.co.uk/` is down and has been down for, at least , a few weeks now.
> {giblib,scrot}: use debian distfiles mirror.

- srcpkgs/tagainijisho/template
This is my first time using git, or doing anything for any linux distribution; if I did anything wrong, please help me correct it.
> New package: tagainijisho-1.0.3

- srcpkgs/pfff/patches/lang_js-analyze-module_js.ml-Fix-invalid-documentati.patch
- srcpkgs/pfff/patches/lang_js-analyze-utils_js.mli.patch
- srcpkgs/pfff/template
This depends on  #2381 and  #2382
> New package: pfff

- srcpkgs/nvidia-stable/template
> nvidia-stable: updated to 352.79

- srcpkgs/arpwatch/files/LICENSE
- srcpkgs/arpwatch/template
> New package: arpwatch-2.1a15

- srcpkgs/cairo/template
- srcpkgs/fontconfig/template
Update cairo and fontconfig to match infinality ultimate version on
freetype.
> Update infinality ultimate to 2015-11-30

- srcpkgs/virt-manager/template
Throws internal error without this.
> Virt missing dependency

- srcpkgs/perl-Net-DBus/template
> New Package: perl-Net-DBus-1.1.0

- common/shlibs
- srcpkgs/libsearpc-codegen
- srcpkgs/libsearpc-devel
- srcpkgs/libsearpc/template
Following PR #2612: split Seafile package(s) in 2 distincts PR to avoid troubles with Travis CI. This is PR 1/2
> New package: libsearpc-3.0.7

- srcpkgs/freeciv-qt5
- srcpkgs/freeciv/template
If no one minds, I'll maintain this package.
> freeciv: update to 2.5.3.

- common/shlibs
- srcpkgs/arpack-ng-devel
- srcpkgs/arpack-ng/template
> arpack-ng: Add shlib and -devel package

- srcpkgs/chromium-widevine/template
> chromium-widevine: update to 48.0.2564.109

- srcpkgs/gromit-mpx/template
> New package: gromit-mpx-1.1

- srcpkgs/postgresql/files/postgresql/run
- srcpkgs/postgresql/template
> postgresql : fix permission PGDATA

- srcpkgs/hex2hcd/template
> New Package: hex2hcd

- srcpkgs/innoextract/template
> New Package: innoextract

- common/shlibs
- srcpkgs/libmwaw-devel
- srcpkgs/libmwaw-doc
- srcpkgs/libmwaw/template
https://github.com/voidlinux/void-packages/issues/3716
> New package: libmwaw-0.3.7

- srcpkgs/armagetronad-dedicated
- srcpkgs/armagetronad/files/armagetronad-dedicated/run
- srcpkgs/armagetronad/template
Different templates only because the configure script can not configure both dedicated server roles and a game client at the same time.
> New package: armagetronad-0.2.8.3.3

- srcpkgs/flannel/files/flannel/run
- srcpkgs/flannel/template
@dominikh could you help debugging this one?
> New package: flannel-0.5.5

- srcpkgs/synergy/files/synergyc/run
- srcpkgs/synergy/files/synergys/run
- srcpkgs/synergy/patches/qt5-build-musl.patch
- srcpkgs/synergy/patches/qt5-build.patch
- srcpkgs/synergy/template
- srcpkgs/synergy/update
- Update version to 1.7.5
- Fix build with Qt 5.5
- Install services
> synergy: update to 1.7.5 and install service files

- srcpkgs/lastpass-cli/template
Package for command line interface to LastPass.com
> New package: lastpass-cli-0.9.0

- srcpkgs/conky/template
Title says it all (well, most of it)- this sets up the Lua-Cairo binding for Conky.
> conky: add lua-cairo binding

- srcpkgs/uzbl/template
> New package: uzbl-0.9.0

- srcpkgs/sudo/template
> sudo: update to 1.8.16.

- .travis.yml
- common/travis/bootstrap.sh
- common/travis/build.sh
- common/travis/consistency_check.sh
- common/travis/show_files.sh
- common/travis/xlint.sh
- common/xbps-src/shutils/consistency_check.sh
- xbps-src
`xbps-src consistency-check` iterates over all templates and looks for
potentially broken dependencies.
> xbps-src: add consistency check

- CONTRIBUTING.md
Nobody cared about creating those packages and honestly most issues request packages of questionable quality. So remove this secion
> CONTRIBUTING.md: Remove package request section

- srcpkgs/pgadmin3/template
> pgadmin3: update to 1.22.1

- common/shlibs
- srcpkgs/crypto++/patches/arm-native.patch
- srcpkgs/crypto++/patches/soname.patch
- srcpkgs/crypto++/template
> crypto++: update to 563

- srcpkgs/gucharmap/template
unicode data files have to be downloaded separately now.
> gucharmap: update to 8.0.0.

- common/hooks/post-install/07-rewrite-python-shebang.sh
https://github.com/voidlinux/void-packages/issues/3879
> hooks/post-install: add hook to rewrite unversioned python shebangs.

- srcpkgs/neofetch/template
> New package: neofetch-1.5

- srcpkgs/allegro5-devel
- srcpkgs/allegro5/template
I created this template basead on Allegro4.
> New package: allegro5-5.0.11

- srcpkgs/gpgme/template
Closes #3567 and removes extra variable.
> gpgme: change to gnupg2

- srcpkgs/monkey/template
File list for simpler review: https://gist.github.com/anonymous/75ac2c51ab2797ccaecd
> monkey: update to 1.6.8.

- srcpkgs/vivaldi/template
This is stable version the Vivaldi Browser.
> vivaldi: update to 1.0.435.40

- srcpkgs/ccnet/template
- srcpkgs/seafile-client-qt/template
- srcpkgs/seafile-libclient/template
> seafile-client-qt: update to 5.1.0 (and dependencies)

- srcpkgs/jeti-filemanager/template
ok i hate to do these pull request all the time, wheen i know i bother you. but i want this up!
i am a noob ok. i know i should have just the jeti branch and not closed it. but i just got so tired of seeing all those 30 commits that i didn't know hove exactly thy got there, or how to get rid of them.. at least i am rid of them now, and have removed the wrk.. what ever the line said..
> New package: jeti-filemanager-1.1.2

- srcpkgs/pd/template
> pd: enable alsa output

- srcpkgs/jeti-filemanager/template
fixed segmentation fault... hopefully;
at least what i could find :)
> jeti-filemanager: update to 1.1.3.

- srcpkgs/meson/template
> New package: meson-0.30.0

- common/shlibs
- srcpkgs/kdevelop/patches/kdevelop-4.7.3.cmake-allow-dup-targets-in-po-subdirs.patch
- srcpkgs/kdevelop/template
- srcpkgs/kdevplatform-devel
- srcpkgs/kdevplatform/patches/kdevplatform-1.7.3.cmake-allow-dup-targets-in-po-subdirs.patch
- srcpkgs/kdevplatform/template
runtime is fine with x64_64/glibc, let's see if cross-building with Travis is fine.
2nd commit (79c73a8) is related to issue #4037 .
> New package: kdevelop-1.7.3

- srcpkgs/libvirt/files/virtlogd/run
- srcpkgs/libvirt/template
> libvirt: add service for virtlogd

- srcpkgs/brasero/template
- srcpkgs/cdrdao/patches/fix-stat-includes.patch
- srcpkgs/cdrdao/template
https://forum.voidlinux.eu/t/burning-cds/560
Untested, as I don't own a cd-burner anymore.
> New package: cdrdao-1.2.3 +fix brasero

- srcpkgs/fontmanager/template
> New package: fontmanager-0.7.2

- srcpkgs/bluez/patches/0003-bluetooth-group-can-use-bluez.patch
- srcpkgs/bluez/template
> bluez: remove need for consolekit

- srcpkgs/openldap/template
Currently a lot of functionality for openldap just isn't being built.
> openldap: Enable more modules

- common/shlibs
- srcpkgs/chromium/template
- srcpkgs/flashrom/template
- srcpkgs/hexchat/template
- srcpkgs/hwloc/template
- srcpkgs/intel-gpu-tools/template
- srcpkgs/kde-workspace/template
- srcpkgs/libdrm/template
- srcpkgs/libvirt/template
- srcpkgs/linux-tools/template
- srcpkgs/net-snmp/template
- srcpkgs/powertop/template
- srcpkgs/radeontop/template
- srcpkgs/spice-vdagent/template
- srcpkgs/xen/template
- srcpkgs/xf86-video-ati/template
- srcpkgs/xf86-video-intel/template
- srcpkgs/xorg-server/template
> Fix chromium

- srcpkgs/wps-office-bin/template
> wps-office-bin: nopie=yes

- srcpkgs/adobe-flash-plugin/template
Set nopie=yes for adobe-player-properties binary.
> adobe-flash-plugin: update to 11.2.202.621.

- srcpkgs/opendoas/INSTALL
- srcpkgs/opendoas/files/doas.pam
- srcpkgs/opendoas/patches/fixes.patch
- srcpkgs/opendoas/template
> New package: OpenDoas-0.1

- srcpkgs/dhewm3/INSTALL.msg
- srcpkgs/dhewm3/template
Doom 3 source port that I've been playing. :)
> New package: dhewm3-1.4.0

- srcpkgs/jeti-filemanager/template
i might have gotten a little bit rosty
> jeti-filemanager: update to 1.2.0

- srcpkgs/ccnet/template
- srcpkgs/seafile-client-qt/template
- srcpkgs/seafile-libclient/template
> seafile-client-qt: update to 5.1.2

- srcpkgs/jeti-filemanager/template
thank you for your time, you are awsome! :)
> jeti-filemanager: update to 1.2.1

- srcpkgs/rstudio/template
I don't like the install scripts and should probably rewrite them in the template.
Also the hardcoded mathjax version is wrong. But fixing all this would require a patch, so it's ugly either way.
> New package: rstudio-0.99.902

- srcpkgs/moreutils/INSTALL.msg
- srcpkgs/moreutils/template
> moreutils: move ts, issue #4282

- common/shlibs
- srcpkgs/liburcu-devel
- srcpkgs/liburcu/template
- srcpkgs/liburcu/update
- srcpkgs/lttng-ust-devel
- srcpkgs/lttng-ust/template
Reopens #3979 in response to #4377
> New packages: lttng-ust-2.7.2 liburcu-0.9.1

- srcpkgs/slstatus/INSTALL.msg
- srcpkgs/slstatus/files/config.h
- srcpkgs/slstatus/template
A package for [slstatus][1] to satisfy my own package request (https://github.com/voidlinux/void-packages/issues/4389).
[1]: https://github.com/drkh5h/slstatus
> New package: slstatus-1.0

- srcpkgs/spectrwm/template
> spectrwm: update to 3.0.2.

- srcpkgs/rmilter/files/rmilter/run
- srcpkgs/rmilter/template
> rmilter: update to 1.8.6

- srcpkgs/paper-gtk-theme/template
Adding paper theme to gtk.
https://snwh.org/paper/theme
> New package: paper-gtk-theme

- srcpkgs/asciiquarium/template
- srcpkgs/perl-Term-Animation/template
One of my favorite useless packages, this draws an aquarium drawn entirely from ascii characters on your terminal.
> Asciiquarium

- srcpkgs/paper-icon-theme/template
Adding paper icon theme
https://snwh.org/paper/icons
> New package: paper-icon-theme

- srcpkgs/qt5/files/cross-gcc.patch
- srcpkgs/qt5/files/cross-ninja.patch
- srcpkgs/qt5/files/moc/moc.pro
- srcpkgs/qt5/files/qdbuscpp2xml/qdbuscpp2xml.pro
- srcpkgs/qt5/files/qdbusxml2cpp/qdbusxml2cpp.pro
- srcpkgs/qt5/files/qlalr/qlalr.pro
- srcpkgs/qt5/files/rcc/rcc.pro
- srcpkgs/qt5/files/uic/uic.pro
- srcpkgs/qt5/template
Cross compile support ... now working.
Waiting for someone to test the results, see #4579
> qt5: update to 5.6.1-1 + enable cross

- srcpkgs/cowsay-temoc/template
Assuredly the most frivilous PR I've made all week.
> New package: cowsay-temoc-1.0

- srcpkgs/opera/template
- srcpkgs/opera/update
Update version and added file update.
> opera: update to opera-39.0.2256.48

- srcpkgs/virtualbox-ose/patches/009-libressl-compat.patch
- srcpkgs/virtualbox-ose/template
This includes the switch to Qt5.
> virtualbox-ose: update to 5.1.2

- srcpkgs/lua-luadbi/template
- srcpkgs/lua51-luadbi
- srcpkgs/lua52-luadbi
Includs lua51-luadbi and lua52-luadbi
> New package: lua-luadbi-0.5

- srcpkgs/cmst/template
This is a Qt based GUI with system tray icon functionality, which I believe will prove useful for users constructing a lightweight Qt desktop (e.g. LXQt, Lumina, etc.)
> New package: cmst-2016.04.03

- srcpkgs/prelink/template
> prelink: add config file

- srcpkgs/mergerfs/template
Is it OK now?
Sorry for the last one...
> mergerfs: update to 2.15.0

- srcpkgs/font-mplus-ttf/template
This package provides TrueType font for Japanese.
> New package: font-mplus-ttf

- srcpkgs/dcraw/template
> New package: dcraw

- srcpkgs/bitcoin/template
Sorry for the late update (I was on holiday for two weeks).
I also added the `bitcoin-tx` cli utility to the _bitcoin_ package.
> bitcoin: update to 0.13.0.

- srcpkgs/glibc/patches/glibc-upstream-01.patch
- srcpkgs/glibc/patches/glibc-upstream-02.patch
- srcpkgs/glibc/patches/glibc-upstream-03.patch
- srcpkgs/glibc/patches/glibc-upstream-04.patch
- srcpkgs/glibc/patches/glibc-upstream-05.patch
- srcpkgs/glibc/patches/glibc-upstream-06.patch
- srcpkgs/glibc/patches/glibc-upstream-07.patch
- srcpkgs/glibc/patches/glibc-upstream-08.patch
- srcpkgs/glibc/patches/glibc-upstream-09.patch
- srcpkgs/glibc/patches/glibc-upstream-10.patch
- srcpkgs/glibc/patches/glibc-upstream-11.patch
- srcpkgs/glibc/patches/glibc-upstream-12.patch
- srcpkgs/glibc/patches/glibc-upstream-13.patch
- srcpkgs/glibc/patches/glibc-upstream-14.patch
- srcpkgs/glibc/patches/glibc-upstream-15.patch
- srcpkgs/glibc/template
> glibc: sync with upstream release branch

- srcpkgs/calligra/template
> calligra: -flow depends on -plugins

- srcpkgs/CellWriter/template
Very useful for pen-driven systems.
> New package: CellWriter-1.3.5

- srcpkgs/coccigrep/template
coccigrep is a semantic grep for the C language based on coccinelle.
> New package: coccigrep-1.16

- srcpkgs/drive/template
> New package: drive-0.3.8.1

- common/shlibs
- srcpkgs/knemo/patches/knemo-gcc6.patch
- srcpkgs/knemo/template
- srcpkgs/knemo/update
This pull request adds the new package knemo-0.7.7 requested by me in #4754 . Since the package couldn't be installed after my first build attempt because libksignalplotter.so.4 couldn't be resolved, I also added that library to common/shlibs.
> New Package: knemo-0.7.7

- common/shlibs
- srcpkgs/kmymoney-devel
- srcpkgs/kmymoney/patches/backported-fix-for-bug-364355.patch
- srcpkgs/kmymoney/template
- srcpkgs/libalkimia-devel
- srcpkgs/libalkimia/template
This pull request introduces the new package kmymoney requested by me in #4670 . I also added the new package libalkimia which is a necessary dependency for kmymoney and added the libraries provided by both packages to common/shlibs. After testing the build I noticed that the binary packages couldn't be installed because libgwengui-qt4.so.0 couldn't be resolved to package so I moved the entry in common/shlibs to the -qt package the contains the .so file.
> New package: kmymoney-4.8.0

- srcpkgs/fdupes/patches/makefile-fix.patch
- srcpkgs/fdupes/template
- srcpkgs/fdupes/update
Let's see if Tracis CI builds are fine with musl libc.
> fdupes: update to 1.6.1

- common/environment/setup/install.sh
> common/environment/setup/install.sh: quote filename in vinstall

- srcpkgs/cairo/template
- srcpkgs/fontconfig/template
- srcpkgs/freetype/template
> freetype, cairo, fontconfig: drop ultimate buildoption

- srcpkgs/zaproxy/patches/build.patch
- srcpkgs/zaproxy/template
zaproxy is a web application vulnerability scanner written by
OWASP.
> New package: zaproxy-2.5.0_1

- common/xbps-src/shutils/common.sh
- xbps-src
> xbps-src: allow show of broken pkgs

- srcpkgs/base-files/INSTALL
- srcpkgs/base-files/template
And remove it if it was created by previous versions.
> base-files: do not create broken var/spool/mail/mail symlink.

- .travis.yml
> travis: build aarch64 instead of armv6

- .travis.yml
- common/travis/prepare.sh
In the hope this fixes/improves #5148 and #4909...
> travis: switch to xbps-uchroot and newer os

- srcpkgs/Bear/template
- srcpkgs/dex/template
- srcpkgs/sound-icons/template
These are my first few contributions to Void Linux, I hope that these packages are welcome. Any comments or suggestions are very welcome.
> New packages: Bear-2.2.1, sound-icons-0.1, dex-0.7

- srcpkgs/sklogw/files/sklogw/finish
- srcpkgs/sklogw/files/sklogw/log/run
- srcpkgs/sklogw/files/sklogw/run
- srcpkgs/sklogw/template
> New package: sklogw

- srcpkgs/electrum/INSTALL.msg
- srcpkgs/electrum/template
- srcpkgs/electrum/update
- srcpkgs/python-jsonrpclib/template
- srcpkgs/python-pbkdf2/template
- srcpkgs/python-protobuf/template
- srcpkgs/python-qrcode/INSTALL.msg
- srcpkgs/python-qrcode/template
- srcpkgs/python-slowaes/template
[Electrum Bitcoin Wallet](https://electrum.org)
I didn't package the optional/plugin dependencies zbar, btchip, trezor, keepkey as they are more complex and can be added later.
> New packages: Electrum and dependencies

- srcpkgs/pgpdump/template
pgpdump is a PGP packet visualizer.
> New package: pgpdump-0.31

- srcpkgs/google-chrome/template
This PR updates google chrome to the latest stable version.
> google-chrome: update to 55.0.2883.75-1

- srcpkgs/pgadmin3/template
> pgadmin3 : update to 1.22.2

- srcpkgs/python-pycryptodome/template
- srcpkgs/python3-pycryptodome
- srcpkgs/streamlink/template
Streamlink: update to 0.2.0
New package: python-pycryptodome-3.4.3
> streamlink: update to 0.2.0 + new dependency

- srcpkgs/rstudio/update
Maybe wait to merge this until there is a new version anyway? It's just a convenience for me not the users.
> rstudio: add update file

- srcpkgs/jeti-filemanager/template
> jeti-filemanager: update to 2.0.0

- srcpkgs/unzip/update
bump package revision is needed ?
> unzip: fix update check

- srcpkgs/google-chrome/template
> google-chrome: update to 55.0.2883.87.

- srcpkgs/lemonbar-xft/template
> New package: lemonbar-xft-1.0.20170116

- srcpkgs/zathura-cb/template
- srcpkgs/zathura-djvu/template
- srcpkgs/zathura-pdf-mupdf/template
- srcpkgs/zathura-pdf-poppler/template
- srcpkgs/zathura-ps/template
> Include zathura as dependency for zathura-*

- srcpkgs/libdill/template
> libdill: update to 1.2.

- srcpkgs/nfs-utils/files/start-statd
- srcpkgs/nfs-utils/template
> nfs-utils: add start-statd replacement

- srcpkgs/blueman/INSTALL.msg
- srcpkgs/blueman/template
- srcpkgs/bluez-qt5/INSTALL.msg
- srcpkgs/bluez-qt5/template
- srcpkgs/bluez/INSTALL.msg
- srcpkgs/bluez/template
This is so when people install something bluetooth they know why it may not be working.
> Add a install message for bluetooth

- srcpkgs/python-ndg_httpsclient/template
- srcpkgs/python3-ndg_httpsclient
I'm not sure if I'm handling `build_options` correctly here.
> New package: python-ndg_httpsclient-0.4.2

- srcpkgs/wireguard/template
Simple version bump.
@chneukirchen
> wireguard: update to 0.0.20170223

- srcpkgs/swarp/template
The packaged software is rather trivial, but quite useful at times - so it makes sense to include it in the repos IMO.
> New package: swarp-0.1

- srcpkgs/elogind/files/007-fix-non_portable_percent_m.patch
- srcpkgs/elogind/files/parse-printf-format.c
- srcpkgs/elogind/files/parse-printf-format.h
- srcpkgs/elogind/patches/001-fix-label-selinux.patch
- srcpkgs/elogind/patches/002-fix-logind-action-constify_args.patch
- srcpkgs/elogind/patches/003-musl-missing.patch
- srcpkgs/elogind/patches/004-musl-program_invocation_short_name.patch
- srcpkgs/elogind/patches/005-musl-selinux-util-sys_types_h.patch
- srcpkgs/elogind/patches/006-musl-strerror_r.patch
- srcpkgs/elogind/patches/008-fix-loginctl_help.patch
- srcpkgs/elogind/patches/009-fix-faccessat-flags.patch
- srcpkgs/elogind/template
Compiles but is yet untested.
Closes #5887
> elogind: fix musl

- srcpkgs/i3blocks/INSTALL.msg
- srcpkgs/i3blocks/template
this fixes #5684 since those packages probably should not be hard dependencies
> i3blocks: add an INSTALL.msg

- srcpkgs/oath-toolkit/template
> oath-toolkit : missing pam depedency

- srcpkgs/elasticsearch/INSTALL
- srcpkgs/elasticsearch/template
EHLO!
could someone review this?
some points you may yell at me for:
* split into elasticsearch5 instead of updateing elasticsearch because it may break stuff
* kinda followed teh directory structure from teh debian package
im in a hurry these days but will try to fix asap.
> elasticsearch: update to 5.2.1

- srcpkgs/cantata/template
This update ports it over to Qt5.
> cantata: update to 2.0.1.

- srcpkgs/libGL/template
Add wayland build option to libGL.
New version of https://github.com/voidlinux/void-packages/pull/5580 pull request. Because I have to learn how to update a fork properly.
> libGL: make wayland optional

- srcpkgs/vidcutter/template
> New package: vidcutter-3.0.1

- srcpkgs/blender/patches/1a01ef4ae903f05ae4ff14bd585ed909e35fc089.diff
- srcpkgs/blender/patches/blender-2.78a-musl.patch
- srcpkgs/blender/template
Patches from Alpine and upstream. jemalloc seems broken on musl (seen this in other packages too), so added a buildoption to disable it on musl.
> blender: unbreak musl (Alpine patch)

- srcpkgs/perl-CheckLib/template
- srcpkgs/perl-DBD-mysql/template
- srcpkgs/perl-IO-CaptureOutput/template
> perl-DBD-mysql: unbreak

- srcpkgs/libcacard-devel
- srcpkgs/libcacard/template
- srcpkgs/qemu/template
- srcpkgs/spice/template
> qemu: add smartcard support

- srcpkgs/spt/template
A simple pomodoro timer. Also quite useful at times. `libnotify` integration compiled in.
> New package: spt-0.4

- srcpkgs/gvim-huge/template
- srcpkgs/vim/template
gvim with python, perl and lua support (see #5902)
> gvim: huge version

- srcpkgs/gnome-music/template
- srcpkgs/tracker/template
> gnome-music: update to 3.24.0

- srcpkgs/gegl3/template
- srcpkgs/gnome-photos/template
> gnome-photos: update to 3.24.0

- srcpkgs/jack/template
#6006 
Letting travis test.
This does not do a rebuild so we can merge this without worrying about the builders.
> jack: change distfiles location

- srcpkgs/i2pd/files/i2pd/run
- srcpkgs/i2pd/template
this is how this is done, right?
> i2pd: add runit service and system user

- srcpkgs/etckeeper/template
The original PR  #4744 it's very messy.
> New package: etckeeper-1.18.6

- srcpkgs/dovecot-plugin-pigeonhole/template
- srcpkgs/dovecot/template
> dovecot: update to 2.2.29

- srcpkgs/cool-retro-term/template
- srcpkgs/qmltermwidget/template
Also added `qt5-quickcontrols` to runtime deps, since CRT does not start without it.
> cool-retro-term: Added new package qmltermwidget, fixed various things

- srcpkgs/polari/template
> new package: polari-3.24.1

- srcpkgs/twemoji/template
> New package: twemoji-1.1

- srcpkgs/font-iosevka/template
Uses the pack distribution to include most of the variants of iosevka.
> font-iosevka: Add 01-08 variants

- srcpkgs/pgadmin3/patches/pgadmin3-fix-segfault.patch
- srcpkgs/pgadmin3/template
> pgadmin3: fix startup and distfile

- srcpkgs/dina-font/template
Dina is a monospace bitmap font, based on the Proggy font.
https://www.donationcoder.com/Software/Jibz/Dina/
Template adapted from Kyle Keen's Arch Linux dina-font PKGBUILD.
https://www.archlinux.org/packages/community/any/dina-font/
> New package: dina-font-2.92

- srcpkgs/postgresql/template
Signed-off-by: Gerardo  Di Iorio <arete74@gmail.com>
> postgresql: update to 9.5.7.

- common/shlibs
- remove entries for no longer existing packages
- remove entries for shlibs no longer provided by any package
> common/shlibs: cleanup

- srcpkgs/kdelibs/patches/CVE-2017-8422.patch
- srcpkgs/kdelibs/template
taken from upstream git commit 264e97625abe2e0334f97de17f6ffb52582888ab
KDE security advisory: https://www.kde.org/info/security/advisory-20170510-1.txt
> kdelibs: add CVE-2017-8422.patch

- srcpkgs/libsass/template
Signed-off-by: Gerardo  Di Iorio <arete74@gmail.com>
> libsass: update to 3.4.5

- srcpkgs/gajim/patches/include-root-cert.patch
- srcpkgs/gajim/template
The plugin-installer plugin in gajim has a few minor build problems that prevent it from working. I believe that this should fix it.
> gajim: fix plugin installer

- srcpkgs/nvidia340/files/linux-4.11.patch
- srcpkgs/nvidia340/template
patch via pld-linux/xorg-driver-video-nvidia-legacy-340xx
> nvidia340: fix building with linux-4.11

- srcpkgs/ngircd/template
- srcpkgs/ngircd/update
And add an update file so update-check will work.
> ngircd: update to 24.

- srcpkgs/twemoji/template
The package now also installs in font configuration file
> twemoji: update to 1.3

- srcpkgs/linux4.1/template
Seems to be a _significant_ update. I use it since yesterday.
> linux4.1: update to 4.1.40

- srcpkgs/etckeeper/template
> etckeeper: add perl dependency

- srcpkgs/zziplib/patches/CVE-2017-5974.patch
- srcpkgs/zziplib/patches/CVE-2017-5975.patch
- srcpkgs/zziplib/patches/CVE-2017-5976.patch
- srcpkgs/zziplib/patches/CVE-2017-5978.patch
- srcpkgs/zziplib/patches/CVE-2017-5979.patch
- srcpkgs/zziplib/patches/CVE-2017-5981.patch
- srcpkgs/zziplib/patches/zziplib-unzipcat-NULL-name.patch
- srcpkgs/zziplib/template
fixes for CVE-2017-5974, CVE-2017-5975, CVE-2017-5976, CVE-2017-5978,
CVE-2017-5979, CVE-2017-5980 and CVE-2017-5981. Patches from SuSe via
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854727#35
> zziplib: add patches to fix multiple CVEs

- srcpkgs/ettercap/patches/CVE-2017-6430.patch
- srcpkgs/ettercap/patches/CVE-2017-8366.patch
- srcpkgs/ettercap/template
fixes CVE-2017-8366 and CVE-2017-6430. Patches from upstream,
git revisions 1083d604930ebb9f350126b83802ecd2cbc17f90 and
7f50c57b2101fe75592c8dc9960883bbd1878bce
> ettercap: add CVE-2017-8366.patch and CVE-2017-6430.patch

- srcpkgs/libmwaw/patches/CVE-2017-9433.patch
- srcpkgs/libmwaw/template
fixes CVE-2017-9433, patch from upstream git,
revision 68b3b74569881248bfb6cbb4266177cc253b292f
> libmwaw: add CVE-2017-9433.patch

- srcpkgs/heimdall/template
New: a Qt5 frontend for heimdall.
> heimdall: update to 1.4.2

- srcpkgs/hg-git/template
Modified "short_desc=" to be less than 72 chars.
> hg-git: update to 0.8.6

- srcpkgs/electrum/template
- srcpkgs/python-pyaes/template
- srcpkgs/python-pysocks/template
- srcpkgs/python3-pyaes
- srcpkgs/python3-pysocks
This also adds two new python packages as electrum now depends on them
> electrum: Update to 2.8.3

- srcpkgs/libnl3/patches/musl.patch
- srcpkgs/libnl3/template
I've tested this on glibc/musl using wireshark and everything seems to work fine
> libnl3: update to 3.3.0

- srcpkgs/python-pathspec/template
- srcpkgs/python-yamllint/template
- srcpkgs/python3-pathspec
* Added a the package python-pathspec as this package now depends on it
> python-yamllint: update to 1.8.1

- srcpkgs/corebird/template
* Tried on armv7l-musl and it seems to work fine ( Only launched it, i didn't go any deeper )
> corebird: fix cross compiling

- srcpkgs/fuse-emulator/template
- srcpkgs/fuse-emulator/update
- srcpkgs/libspectrum/template
* Also update libspectrum as the fuse update requires it to also be updated
* Fixed fuse-emulator update check
> fuse-emulator: update to 1.3.7

- common/build-style/meson.sh
- srcpkgs/budgie-desktop/template
- srcpkgs/gnome-recipes/template
also use build_style=meson in all templates that use meson.
> common/build-style: add meson build style

- srcpkgs/vim/template
My first PR using git command-line. :)
> vim: update to 8.0.0765

- srcpkgs/vivaldi/template
> vivaldi: update to 1.10.867.48

- srcpkgs/oxygen-icons5/template
Trying to solve [#7189](https://github.com/voidlinux/void-packages/issues/7189).
> oxygen-icons5: prevent conflict

- srcpkgs/xlennart/template
> New package: xlennart

- srcpkgs/fillets-ng-data
- srcpkgs/fillets-ng/template
A little game found on [the forum](https://forum.voidlinux.eu/t/made-my-first-void-package-usokoban/2989/6).
> New package: fillets-ng

- srcpkgs/subuser/template
Forum [request](https://forum.voidlinux.eu/t/cool-apps-for-new-packagers/1642/19).
> New package: subuser

- srcpkgs/dropbox/template
> dropbox: add missing dependency

- srcpkgs/ranger/template
> ranger: switch to python 3

- srcpkgs/polari/template
> polari: add missing dependency

- srcpkgs/nano/template
* Also removed a $pkgname from distfiles
> nano: update to 2.8.7

- srcpkgs/gnome-photos/template
* Also cleaned up the template a bit
> gnome-photos: update to 3.24.3

- srcpkgs/postgresql/template
- srcpkgs/postgresql/update
> postgresql: update to 9.6.4 and switch to use https

- srcpkgs/armadillo/template
- update to 7.960.0
- enable HDF5 support
- improve openblas wrapping
> armadillo: update to 7.960.0

- srcpkgs/notepadqq/template
Template based on the Arch [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/notepadqq).
> New package: notepadqq

- srcpkgs/texstudio/template
( unfortunately, upstream changed the source-archive ..., I already complained about this.)
updated checksum, wkrsrc
+ consolidated build options while at it
> texstudio: fix checksum + template cleanup

- srcpkgs/csync/template
> csync: add makedepends to build plugins

- srcpkgs/Adapta/template
* Also removed `$homepage` from distfiles
> Adapta: update to 3.91.2.136

- srcpkgs/bluedevil/template
- srcpkgs/kde-gtk-config5/template
- srcpkgs/khotkeys/template
- srcpkgs/kmenuedit/template
- srcpkgs/kscreen/template
- srcpkgs/kwallet-pam/template
- srcpkgs/kwayland-integration/template
- srcpkgs/kwrited/template
- srcpkgs/plasma-desktop/template
- srcpkgs/plasma-nm/template
- srcpkgs/plasma-pa/template
- srcpkgs/plasma-workspace-wallpapers/template
- srcpkgs/polkit-kde-agent/template
- srcpkgs/powerdevil/template
Another part of KDE Plasma with its dependencies, updates and fixes, previous part is #5843
> New package: plasma-desktop-5.8.7

- srcpkgs/dialog/template
This solves issue #7589. Upstreams DNS settings seem to have beem changed lately.
> dialog: fix distfiles url

- srcpkgs/kde5/template
- srcpkgs/kdeplasma-addons5/template
- srcpkgs/kgamma5/template
- srcpkgs/ksshaskpass/template
- srcpkgs/plasma-sdk/template
- srcpkgs/sddm-kcm/template
- srcpkgs/user-manager/template
Last part of KDE Plasma with kde5-metapackage, previous is #5849
> New package: kde5-5.8

- srcpkgs/keybase/template
@the-eater is it really worth keeping track of commit messages for this?
> keybase: update to 1.0.29.

- common/environment/build-style/meson.sh
- common/shlibs
- srcpkgs/gnome-boxes/template
- srcpkgs/gnome-online-miners/template
- srcpkgs/gnome-photos/template
- srcpkgs/grilo-plugins/template
- srcpkgs/nautilus/template
- srcpkgs/rygel/template
- srcpkgs/tracker/template
> tracker: update to 2.0.0

- srcpkgs/bluez/template
Hope this is acceptable, don't know if it's ok to modify and update packages at the same time
> bluez: update to 5.47, added sixaxis support, removed pie flag

- srcpkgs/gnupg2/template
* Just a bugfix update [Changelog](https://lists.gnupg.org/pipermail/gnupg-announce/2017q3/000415.html)
> gnupg: update to 2.2.1

- srcpkgs/gandi-cli/template
Command line interface to Gandi.net
> New package: gandi-cli-0.22

- srcpkgs/postgresql/template
Signed-off-by: Gerardo  Di Iorio <arete74@gmail.com>
> postgresql: update 9.6.5

- srcpkgs/cmake-gui/template
- srcpkgs/cmake/template
Someone wants to run a bulk build for all build_style=cmake packages?
> cmake: update to 3.9.2.

- srcpkgs/wmutils-core/template
> wmutils-core: make it conflict with lsw

- common/shlibs
- srcpkgs/gutenprint-devel
- srcpkgs/gutenprint/template
Top quality printer drivers for POSIX systems
> New package: gutenprint

- srcpkgs/kakoune/template
The current template is about 6 months old.
Sadly, mawww isn't still in the mood to tag a fscking release, despite many people asking for it.
> kakoune: update to git@20170928

- srcpkgs/openssh/patches/werror.patch
- srcpkgs/openssh/template
Tested on x86_64, someone else test it too please.
> openssh: update to 7.6p1.

- srcpkgs/vala/template
while we're at it, also fix identation on line 16
> vala: update to 0.38.2.

- srcpkgs/gnome-todo/template
Tested succesfully seems to work fine on x86_64
> gnome-todo: update to 3.26.1.

- srcpkgs/nautilus-sendto/template
related to #8010 one of the packages needed by gnome-apps
> nautilus-sendto: update to 3.8.6.

- srcpkgs/gnome-tweak-tool/template
This was not tested since i don't run a gnome-shell
> gnome-tweak-tool: update to 3.26.2.1.

- srcpkgs/ladish/patches/aarch64.patch
- srcpkgs/ladish/template
> ladish: fix aarch64

- srcpkgs/alsa-firmware/template
To help [#8113](https://github.com/voidlinux/void-packages/issues/8113)
> alsa-firmware: prevent conflict with linux-firmware

- srcpkgs/bluedevil/template
- srcpkgs/breeze-gtk/template
- srcpkgs/kde-gtk-config5/template
- srcpkgs/kde5/template
- srcpkgs/kdecoration/template
- srcpkgs/kdeplasma-addons5/template
- srcpkgs/kgamma5/template
- srcpkgs/kinfocenter/template
- srcpkgs/kscreen/template
- srcpkgs/ksshaskpass/template
- srcpkgs/ksysguard/template
- srcpkgs/kwallet-pam/template
- srcpkgs/kwayland-integration/template
- srcpkgs/kwrited/template
- srcpkgs/libkscreen/template
- srcpkgs/libksysguard/template
- srcpkgs/oxygen/template
- srcpkgs/plasma-desktop/template
- srcpkgs/plasma-nm/template
- srcpkgs/plasma-pa/template
- srcpkgs/plasma-sdk/template
- srcpkgs/plasma-workspace-wallpapers/template
- srcpkgs/plasma-workspace/template
- srcpkgs/powerdevil/template
- srcpkgs/sddm-kcm/template
- srcpkgs/user-manager/template
* Just a bugfix release. [log](https://www.kde.org/announcements/plasma-5.11.1-5.11.2-changelog.php)
> kde5: update to 5.11.2

- srcpkgs/MoarVM/template
- srcpkgs/nqp/template
- srcpkgs/rakudo/template
> rakudo: update to 2017.10.

- common/xbps-src/libexec/xbps-src-docheck.sh
- common/xbps-src/shutils/build_dependencies.sh
- common/xbps-src/shutils/chroot.sh
- srcpkgs/binutils/template
use the common convention as described in etc/defaults.conf
@Vaelatern please take a look, in case you depend on setting 0/"no" in dxpb somewhere.
> common: drop 0/no logic from XBPS_{CHECK_PKGS,BUILD_ONLY_ONE_PKG}

- common/xbps-src/shutils/common.sh
Fixes #9454, hopefully doesn't break something else.
> xbps-src: evaluate build_options before setting default flags

- srcpkgs/xbps-triggers/files/gtk-immodules
- srcpkgs/xbps-triggers/files/gtk3-immodules
- srcpkgs/xbps-triggers/template
> xbps-triggers: conform to new gtk-immodules cache locations.

- srcpkgs/navit/template
See files installed. Advice on fixing the new root level directory would be welcome.
It also downloads a file during the build, can that be fixed easily? I couldn't see how.
> New package: navit-0.5.1+rc1

- srcpkgs/mirage/template
Adding new package: mirage-0.9.5.2-1
> New package: mirage-0.9.5.2-1

- common/shlibs
- srcpkgs/hivex/template
- srcpkgs/libguestfs/template
- srcpkgs/rrdtool/template
- srcpkgs/ruby/template
- srcpkgs/subtle/template
- srcpkgs/vagrant/template
- srcpkgs/vim/template
- srcpkgs/weechat/template
> Ruby 2.5.0

- srcpkgs/mbedtls-utils
- srcpkgs/mbedtls/template
Just get rid of that little pollution, fixes issue #7934
cc: @chneukirchen
> mbedtls: separate toys/utilities to mbedtls-utils

- srcpkgs/qtikz/patches/fix-version.patch
- srcpkgs/qtikz/template
> qtikz: change qt version to qt5

- srcpkgs/katarakt/template
> katarat: change qt version to qt5

- srcpkgs/gitea/patches/daemon_config.patch
- srcpkgs/gitea/template
Version bump, adapted `conf/app.ini` for changed location `custom/conf/app.ini.sample`
> gitea: update to 1.4.0

- srcpkgs/libwhich/template
Will probably be needed for a future julia update.
> New package: libwhich-1.0.0

- srcpkgs/python-jupyter_ipywidgets/template
- srcpkgs/python-jupyter_widgetsnbextension/template
Also update python-jupyter_widgetsnbextension to 3.2.0
> python-jupyter_ipywidgets: update to 7.2.0.

- srcpkgs/upower/template
Also updated license to SPDX compliance.
> upower: rev bump to fix upower0 replacement

- srcpkgs/openrazer-meta/template
- srcpkgs/python-pyudev/template
and 
> openrazer-meta: remove python3-six dependency
Picked from #13146
> python-pyudev: add missing python-six dependency 

- srcpkgs/deluge/patches/001-deluge-gtk-settings.patch
- srcpkgs/deluge/template
https://forum.deluge-torrent.org/viewtopic.php?f=7&t=54517
> deluge-gtk: patch settings dialog not working for version 1.3.15

- srcpkgs/perl-Class-Accessor/template
- srcpkgs/perl-IO-CaptureOutput/template
- srcpkgs/perl-Stream-Buffered/template
- srcpkgs/perl-WebService-MusicBrainz/template
This sets the remaining packages from #15056 to `noarch`.
> Set some perl packages to noarch
