- srcpkgs/apache/template
Work around errors:
AH00526: Syntax error on line 31 of /etc/httpd/extra/httpd-multilang-errordoc.conf:
Invalid command 'LanguagePriority', perhaps misspelled or defined by a module not included in the server configuration
AH00526: Syntax error on line 78 of /etc/httpd/extra/httpd-languages.conf:
Invalid command 'LanguagePriority', perhaps misspelled or defined by a module not included in the server configuration
AH00526: Syntax error on line 10 of /etc/httpd/extra/httpd-userdir.conf:
Invalid command 'UserDir', perhaps misspelled or defined by a module not included in the server configuration
[Tue Jan 06 01:34:14.130358 2015] [proxy_balancer:emerg] [pid 24013:tid 140060053915520] AH01177: Failed to lookup provider 'shm' for 'slotmem': is mod_slotmem_shm loaded??
[Tue Jan 06 …
> apache-2.4.10: fix default httpd.conf

- srcpkgs/apache/template
Just add missing dependencies instead of removing broken features.
> apache-2.4.10: revert and fix httpd.conf

- srcpkgs/tlp/files/tlp/finish
- srcpkgs/tlp/files/tlp/run
- srcpkgs/tlp/template
Also removed 2 lines which changed the absolute path to /usr/bin in udev config and systemd services, while tlp is located in /usr/sbin.
> tlp: add runit services

- srcpkgs/base-files/files/vkpurge
- srcpkgs/base-files/template
I have some kernels from another distro on my boot partition and "vkpurge list" always throws "Invalid string..." errors when trying to list them. I re-used an apparently discarded local variable and dropped another in the process.
> base-files: Prevent 'vkpurge list' from displaying errors at unknown kernel files

- srcpkgs/spotify/INSTALL
- srcpkgs/spotify/template
Sorry for the new pull request, but just now a second version of libssl was added and my library version detection probably would not have liked that.
> spotify: Limited library search to 1 result

- srcpkgs/weechat/template
this fixes ``/usr/lib/weechat/plugins/python.so: undefined symbol: forkpty`` in weechet while trying ``/plugin load python``
> weechat: fix python plugin

- srcpkgs/zpaq/template
Dropped pod2mdoc dependency, and use perl (=> /usr/bin/pod2man) instead, due to issues with pod2mdoc.
Appearantly it generated an empty file with only date and title, and this fixes that. The manual is now working (proper testing has been done on my end).
> zpaq: fix empty manual

- srcpkgs/runit-void/INSTALL
- srcpkgs/runit-void/template
When a user has deactivated a service with a `down` file, I think it is prudent to not install it by default.
> runit-void: Install only active services by default

- srcpkgs/openjdk/files/003_nonreparenting-wm.patch
- srcpkgs/openjdk/template
Make openjdk respect the `_JAVA_AWT_WM_NONREPARENTING` environment variable for use with unknown nonreparenting windowmanagers.
> openjdk: Fix for nonreparenting windowmanagers

- srcpkgs/zpaq/template
Changes:
Jan. 30, 2015. Adds compression methods to libzpaq. Removes -quiet, -fragment, -fragile, -since, -duplicates, -newkey. Allows add -to, extract -all, list files (compare).
> zpaq: update to 7.00

- srcpkgs/lilo/files/kernel.d/lilo.post-install
- srcpkgs/lilo/files/kernel.d/lilo.post-remove
- srcpkgs/lilo/files/lilo.conf
- srcpkgs/lilo/template
This adds a post-install and a post-remove kernel hooks for LILO. For each image that gets installed a file in in `/etc/lilo.d/` is created. Furthermore, a file called `/etc/lilo.d/default.conf` is created, this particular file just specifies the default image to boot. The files in `/etc/lilo.d` are not parsed by LILO by default, thus a temporary file is created to concat `/etc/lilo.conf` with `/etc/lilo.d/*.conf` this temporary file is passed to LILO using the `-C` flag. That's it.
> lilo: add kernel hooks

- srcpkgs/xdm/files/xdm/run
- srcpkgs/xdm/template
This adds a runit service for the standard X log manager xdm. Furthermore, it also adds a configure flag which forces xdm to keep its configuration files in `/etc/X11/xdm`.
> xdm: runit service and updated config path

- srcpkgs/xdm/files/xdm.pam
- srcpkgs/xdm/template
This adds PAM support for xdm. The file `/etc/pam.d/xdm` was copied from Arch Linux (with minimal modifications).
> xdm: add pam support.

- srcpkgs/micropython/template
This commit contains the simple addition of a package known as micropython, which is essentially a Python for embedded systems. It contains a very slim standard library (although the entire library of Python is available in a seperate repo, and may be added as a seperate package I suppose), and is very performant in comparison to CPython.
In addition, this also allows users of low-power devices, such as ARM developer boards, to produce great content without having to sacrifice performance.
Please let me know where this package doesn't work. Compiled it on ARM, x86_64, and cross (for ARM on x86_64), and it seems to work out of the box.
> New package: micropython 1.3.10

- srcpkgs/plan9port/files/plan9.sh
- srcpkgs/plan9port/template
I couldn't determine any use-case for setting `ROOTPATH` in fact I couldn't even determine the package which reads this environment variable so I decided to remove it. The problem with `MANPATH` is a bit more complicated…our `/etc/profile` doesn't set `MANPATH` because OpenBSDs `man(1)` doesn't require it. Since `MANPATH` was empty before `plan9.sh` sets it to `:/opt/plan9/man` this will completely override `MANPATH` and `man(1)` will only look in `/opt/plan9/man` for man pages. Furthermore it isn't really necessary to append `/opt/plan9/man` to `MANPATH` because the recommended way to read a plan9port man page is using the `9` script e.g: `9 man intro`, therefore I decided to remove that environment variable as well.
> plan9port: Don't modify $ROOTPATH and $MANPATH

- srcpkgs/xdm/files/xdm/run
- srcpkgs/xdm/template
By logging errors to `stdout` as well.
> xdm: Don't create a separate log file for errors

- srcpkgs/bash/template
this enables bash to source a system-wide bashrc.
currently set to /etc/bash/bashrc.
> bash: add -DSYS_BASHRC to CFLAGS

- srcpkgs/mpv/template
Warning: mpv was compiled against a different version of ffmpeg than the shared library it is linked against.
> mpv: revbump: rebuild against new ffmpeg

- srcpkgs/base-system-busybox/template
`base-system` also does it this way, thus I figured that `base-system-busybox` should do that as well, right?
> base-system-busybox: Depend on glibc-locales when not built with musl

- srcpkgs/libstrophe/template
The initial libstrophe package used git to fetch the sources. The current version doesn't so git isn't required as a hostmakedependency anymore.
> libstrophe: remove git make dependency

- srcpkgs/tvheadend/template
minimal template for tvheadend. i tried version 3.9 at first but seems not stable. so i went back to 3.4 (works stable for me), it is also the version in portage. 
tvheadend is able to generate a default config, but i'm not sure how to exploit that within the template.
> New package: tvheadend-3.4

- srcpkgs/xmp/template
This is an extended module player which uses libxmp.
I'm going to package `uade` and `asap` aso.
> New package: xmp 4.0.10

- srcpkgs/blender/template
still missing optional OpenShadingLanguage, but depends on llvm-3.5
> blender: +cycles +jemalloc

- common/xbps-src/shutils/common.sh
This ensures that packages with custom build functions also use our provided MAKEFLAGS. Without this commit it was necessary to always append the "${makejobs}" variable manually to make. For compatibility reasons that is still possible but should probably be removed in the future by making "makejobs" a local variable.
See also:
https://projects.archlinux.org/pacman.git/tree/scripts/makepkg.sh.in#n1538
---
This also means that the `${makejobs}` variable can be removed from build-styles. I noticed that some build-styles also use a `${make_build_args}` variable. I am not 100% sure what this variable does but maybe it should be append to `MAKEFLAGS` as well?
> xbps-src: Set the MAKEFLAGS environment variable

- srcpkgs/opencolorio/template
does this need revbump for openimageio and blender?
> opencolorio: update to 1.0.9.

- srcpkgs/jbigkit-devel
- srcpkgs/jbigkit/template
There is a little bug with the build system. I can build with `make` moving to the target directory while ./xbps-src cannot end a vanilla make command w/o errors.
```
cd libjbig && make -e
make[1]: Entering directory '/builddir/jbigkit-2.1/libjbig'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/builddir/jbigkit-2.1/libjbig'
cd pbmtools && make -e
make[1]: Entering directory '/builddir/jbigkit-2.1/pbmtools'
cc -O2 -W -Wno-unused-result      -c -o pbmtojbg.o pbmtojbg.c
pbmtojbg.c:11:18: fatal error: jbig.h: No such file or directory
#include "jbig.h"
```
jbig.h is provided by jbigkit itself.
> New package: jbigkit-2.1

- srcpkgs/CuteMarkEd/template
- srcpkgs/cutemarked/template
closes #1401 
I want to point out line 5.
I did a "#?" to get rid of the "v" in the version string.  Is this fine?  Or is another way prefered to drop the first letter from the version string?
> New Package: CuteMarkEd-0.11.0

- srcpkgs/vim-colorschemes/template
copies colors/ from https://github.com/flazz/vim-colorschemes to /usr/share/vim/vimfiles/
> New package: vim-colorschemes-20141029

- srcpkgs/libXxf86vm/template
This is similar to issue #1399 - when cross-compiling, you can't test the behavior of malloc(0)
> libXxf86vm: unbreak musl cross compilation

- srcpkgs/argp-standalone/template
This is an implementation of argp, for libc implementations that lack it (musl)
> new package: argp-standalone

- srcpkgs/elfutils/patches/001-elfutils-portability.patch
- srcpkgs/elfutils/patches/002-argp-standalone.patch
- srcpkgs/elfutils/patches/003-libint-stub.patch
- srcpkgs/elfutils/patches/004-maybe-uninitialized.patch
- srcpkgs/elfutils/patches/005-memcpy-def.patch
- srcpkgs/elfutils/patches/006-skip-src-po-tests.patch
- srcpkgs/elfutils/patches/007-libdw-add-libs.patch
- srcpkgs/elfutils/patches/008-musl-compat.patch
- srcpkgs/elfutils/patches/009-no-fts.patch
- srcpkgs/elfutils/template
This depends on #1475 
Most of the patches are from OpenWRT's patchset here: https://github.com/openwrt/packages/tree/master/libs/elfutils/patches along with the Musl-Cross patches from here: https://github.com/GregorR/musl-cross/blob/master/patches/patch-elfutils.sh
This is my first time doing a big patch like this, apologies in advance if I missed anything or did anything incorrectly. I'm using the `$XBPS_TARGET_MACHINE` variable to check if the system is musl-based or not, no idea if that's the right way to check. I expect I'll need to make some changes before this gets merged.
> elfutils: update to latest, fix compilation for musl libc

- srcpkgs/llvm/files/patches/cfe/cfe-001-fix-stdint.patch
- srcpkgs/llvm/files/patches/cfe/cfe-002-default-runtime-compiler-rt.patch
- srcpkgs/llvm/files/patches/cfe/cfe-003-fix-unwind-chain-inclusion.patch
- srcpkgs/llvm/files/patches/cfe/cfe-004-add-musl-triples.patch
- srcpkgs/llvm/files/patches/cfe/cfe-005-fix-dynamic-linker-paths.patch
- srcpkgs/llvm/files/patches/cfe/cfe-006-no-use-cxa-atexit.patch
- srcpkgs/llvm/files/patches/cfe/cfe-007-musl-use-init-array.patch
- srcpkgs/llvm/files/patches/cfe/cfe-008-remove-lgcc-when-using-compiler-rt.patch
- srcpkgs/llvm/files/patches/compiler-rt/compiler-rt-002-musl-no-dlvsym.patch
- srcpkgs/llvm/files/patches/compiler-rt/compiler-rt_musl_001-disable-sanitizers.patch
- srcpkgs/llvm/files/patches/llvm/llvm-001-fix-gcc-4.9.patch
- srcpkgs/llvm/files/patches/llvm/llvm-002-musl-triple.patch
- srcpkgs/llvm/files/patches/llvm/llvm-003-musl.patch
- srcpkgs/llvm/template
This uses patches from Alpine Linux's LLVM package, with the Alpine-specific stuff removed: http://git.alpinelinux.org/cgit/aports/tree/testing/llvm
> llvm: fix cross-compilation under musl

- srcpkgs/livestreamer/template
https://github.com/chrippa/livestreamer/releases new version released 4 days ago.
> livestreamer: updated to 1.12.2

- srcpkgs/distcc/files/distccd/run
- srcpkgs/distcc/template
With --no-fork distccd will only ever run one job at a time.
> distcc: remove --no-fork option

- srcpkgs/mediainfo-gui
- srcpkgs/mediainfo/template
I tried a workaround to keep the -gui package with setting a variable in -gui_package and then check for it in do_{build,install}. Didn't work, thus combined them.
> mediainfo: combine -gui package

- srcpkgs/gnome-disk-utility/template
parted is required to format or alter partitions.
https://bugs.archlinux.org/task/41446
https://lists.alioth.debian.org/pipermail/pkg-utopia-maintainers/2014-October/017093.html
> gnome-disk-utility: add parted as a dependency

- srcpkgs/buildbot/patches/terse-irc.patch
- srcpkgs/buildbot/template
Yeah, it sucks to patch buildbot...
Example output:
Success:
```
ec76dbe/x86_64-musl_builder OK: http://build.voidlinux.eu/builders/x86_64-musl_builder/builds/227
```
Failure:
```
76d2ec6/x86_64_builder Fail: http://build.voidlinux.eu/builders/x86_64_builder/builds/12260 blame: Juan RP <xtraeme@voidlinux.eu>
```
> buildbot: terser IRC messages

- srcpkgs/darktable/patches/0001-musl.patch
- srcpkgs/darktable/template
the patch removes unused stderr from the openmp pragma. 
musl defines stderr as (stderr). somehow this is not a valid identifier anymore.
> darktable: enable on musl

- srcpkgs/kbd/patches/kbd-2.0.2-backspace-1.patch
- srcpkgs/kbd/template
Imported from LFS (http://www.linuxfromscratch.org/lfs/view/development/chapter06/kbd.html)
The behaviour of the Backspace and Delete keys is not consistent across the keymaps in
the kbd package. This patch fixes the issue for i386 keymaps.
> kbd: consistent backspace and delete for i386 maps

- srcpkgs/qemu/patches/qemu-2.3.0-security-fdc.patch
- srcpkgs/qemu/template
The qemu git repository contains a patch to address the Venom vulnerability.
This patch applies the upstream changes to hw/block/fdc.c
> qemu: patch to fix Venom vulnerability (CVE-2015-3456)

- srcpkgs/wine/template
This adds staging patches comprehending pulseaudio driver, NPAPI compatibility (needed by pipelight) and other patches. It's currently employed by the default distribution of wine in fedora.
> wine: added staging patchset

- srcpkgs/cubietruck-uboot/files/cubietruck.bootcmd
- srcpkgs/cubietruck-uboot/files/cubietruck.fex
- srcpkgs/cubietruck-uboot/template
This is only the first step of trying to create a cubietruck-base system similar to the already existing cubieboard2. The fex file was taken from [Igor Pecovnik](https://github.com/igorpecovnik/lib/blob/next/config/cubietruck.fex). The bootcmd is probably going to change for the newer uboot, but can only be tested after the SD card image is ready.
> New package: cubietruck-uboot-2015.04

- xbps-src
- I turns out that ccache is very well capable of recognizing different
compilers and using only files stored to the cache by each compiler.
- To avoid large parts of a cache becoming useless just because a compiler
was rebuilt during some (bootstrap) stage, rely on the contents of
the compiler binary for identification instead of mtime + size.
> xbps-src: unified ccache directory

- srcpkgs/edbrowse/patches/0001-glob-fixes.patch
- srcpkgs/edbrowse/template
This also contains a patch from upstream, so that edbrowse will
build under musl.  This will go away with the next release.
> edbrowse: update to 3.5.4.

- srcpkgs/mopidy/template
1.0.4 fixes inability to stream (at least) mp3 over HTTP - https://discuss.mopidy.com/t/mopidy-not-playing-anything-since-last-apt-get-upgrade/704/8
> mopidy: update to 1.0.4

- srcpkgs/cubietruck-uboot/files/cubietruck.bootcmd
- srcpkgs/cubietruck-uboot/template
- The cubietruck-kernel is compressed, thus we load zImage and do bootz
> cubietruck-uboot: fix cubietruck.bootcmd

- srcpkgs/monkey/template
This fixes monkey not building with musl.
Additionally, as can easily be seen in the commit, it also disables the backtrace feature for the musl build of monkey. Likely this won't be a major issue, but it is simply due to the fact that `src/mk_utils.c` will include a header only provided by glibc-devel ( `/usr/include/execinfo.h` ), which is not available on musl-platforms.
Unlikely to be an issue, but worth mentioning. Other than that, it should be good to go.
> monkey: add musl-compilation support.

- srcpkgs/qtcreator/template
A developer using qtcreator will most probably want the majority of available qt-*-devel packages.
qt5-doc contains the *.qch help files and qt5-plugin-sqlite is required to access them.
> qtcreator: depend on qt5-*-devel and qt5-doc

- common/shlibs
- srcpkgs/http-parser-devel
- srcpkgs/http-parser/patches/fix-destdir.diff
- srcpkgs/http-parser/template
- srcpkgs/iojs/template
- srcpkgs/nodejs/template
Node.js and io.js now support build options to enable/disable shared dependencies. As the node/iojs dependencies happily break APIs every now and then this makes maintainance easier.
> Node add build options

- srcpkgs/re2c/template
Upstream changes:
- applied patch '# 27 re2c crashes reading files containing %{ %}' by Rui
- dropped distfiles for MSVC (they are broken anyway)
> re2c: update to 0.14.3

- srcpkgs/gdb/template
gdb/configure doesn't find .../python2.7/Python.h without this.
Configure also tells it doesn't find expat, so perhaps `makedepends+=" expat-devel"`?
> gdb: Make python detection work in cross builds

- srcpkgs/linux4.0/template
Build failed in x86_64-musl masterdir when running `./xbps-src -m /tmp/musl -N pkg base-system`
> linux4.0: make sure $hdrdest dirs exist

- srcpkgs/abduco/template
From failing build:
```
abduco build options:
CFLAGS   = -mtune=generic -O2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2    -specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1
LDFLAGS  = -Wl,--as-needed -Wl,-z,relro  -specs=/void-packages/common/environment/configure/gccspecs/hardened-ld
```
To:
```
abduco build options:
CFLAGS   = -mtune=generic -O2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2    -specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1 -std=c99 -pedanti
c -Wall -I. -DVERSION="0.4" -DNDEBUG -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700
LDFLAGS  =   -Wl,--as-needed -Wl,-z,relro  -specs=/void-packages/common/environment/configure/gccspecs/hardened-ld -lc -lutil
```
> abduco: fix building

- common/shlibs
- srcpkgs/libopenraw-devel
- srcpkgs/libopenraw/template
With this and ffmpegthumbnailer the tumbler package can be completed.
Why the cross builds don't find boost escapes me. Perhaps because the package doesn't recognize `--with-libtool-sysroot`?
> New package: libopenraw-0.0.9

- srcpkgs/widelands/patches/fix-execinfo.patch
- srcpkgs/widelands/patches/fix_nl_msg_cat_cntr.patch
- srcpkgs/widelands/template
+ execinfo.h missing and no backtrace() in musl libc
+ `extern int _nl_msg_cat_cntr;` reference doesn't work (hidden in libintl.so?)
> widelands: unbreak musl build

- srcpkgs/gnome-keyring/patches/sys-select-h.patch
- srcpkgs/gnome-keyring/template
To get evolution compiled with musl libc, this patch is required as well, because evolution depends on gnome-keyring for authenticating with servers.
Then the evolution-data-server pr #1703 is required and finally evolution #1704 should build.
The result can be previewed when installing `evolution` from `--repository=http://muslrepo.voidlinux.de/current` which has all required packages.
> gnome-keyring: fix build on musl

- srcpkgs/ebtables/patches/musl-fixes.patch
- srcpkgs/ebtables/template
[Original source](http://git.alpinelinux.org/cgit/aports/commit/main/ebtables/musl-fixes.patch?id=0f5076024a9700644ac9d542d2ca643fa38e77da). Thanks to Natanael Copa.
> ebtables: include patch from Alpine to fix *-musl

- srcpkgs/beets/template
ImportError: No module named pkg_resources
> beets: depends on python-setuptools

- srcpkgs/chroot-util-linux/template
If the host has ``pam-devel`` installed, bootstrapping fails because chroot-util-linux builds programs that rely on pam. This PR disables those programs explicitly.
> chroot-util-linux: disable programs that use pam

- srcpkgs/libenet/template
This commit simply updates libenet from 1.3.12 to 1.3.13.  No major changes happened there.
> libenet: update to 1.3.13

- common/environment/configure/autoconf_cache/musl-linux
- srcpkgs/evolution-data-server/patches/iconv_10646.patch
- srcpkgs/evolution-data-server/template
The evolution-data-server configure script doesn't trust musl iconv() implementation.
Tell it to assume it's good by setting `ac_cv_libiconv_utf8=hopefully`
A missing macro `ICONV_10646` is conditionally defined in camel/camel-inconv.h to `iso-10646`, which I hope is right for musl's iconv as well.
> evolution-data-server: revbump, patch + hook to build with musl

- srcpkgs/evolution/template
Similar to evolution-data-server also evolution is not happy with musl iconv()
Convince configure to go ahead and write a default iconv-detect.h
Also add gnome-icon-theme to hostdepends and depends, as configure wants either gnome-icon-theme or adwaita-icon-theme installed.
The dependency on gnome-keyring is required for authentication with servers.
> evolution: revbump + hook to build with musl

- srcpkgs/qt5/files/resolv_compat.h
- srcpkgs/qt5/patches/qt-musl-mallinfo.patch
- srcpkgs/qt5/patches/qt-musl-pthread_getattr_np.patch
- srcpkgs/qt5/patches/qt-musl-resolve.patch
- srcpkgs/qt5/patches/qt-musl-rtld_deepbind.patch
- srcpkgs/qt5/patches/qt-musl-siginfo_t.patch
- srcpkgs/qt5/patches/qt-musl-sys_errno_h.patch
- srcpkgs/qt5/template
It built locally on musl, but untested yet. Specificially the `resolv_compat.h` code may be doing something wrong. You get the idea, anyway.
> qt5: unbreak musl

- srcpkgs/mame/patches/musl-sched.patch
- srcpkgs/mame/template
Here's what a companion developer on mamedev list said regarding this topic:
> We should just drop defining free and malloc as macros in corealloc.h.
> Instead, we should on a regular basis scan the source for uses of free
> and malloc.
The patch entirely disables mem tracking for non-`__GLIBC__` now.
> mame: testing musl fix on travis

- srcpkgs/libvirt/template
/usr/share/polkit-1/rules.d/50-libvirt.rules:
```
// Allow any user in the 'libvirt' group to connect to system libvirtd
// without entering a password.
polkit.addRule(function(action, subject) {
if (action.id == "org.libvirt.unix.manage" &&
subject.isInGroup("libvirt")) {
return polkit.Result.YES;
}
});
```
> libvirt: add libvirt group

- srcpkgs/epson-inkjet-printer-escpr/template
had to change the download link to epson directly. i'm not a lawyer, maybe someone has a look at the license stuff at http://download.ebz.epson.net/dsc/du/02/DriverDownloadInfo.do?LG2=EN&CN2=&DSCMI=35219&DSCCHK=01a2288d3ec549615b1491db99fd832d75b73aac# before merging.
> epson-inkjet-printer-escpr: update to 1.4.5.

- srcpkgs/nodejs/template
I fixed the ``http-parser-devel`` package, this build_option isn't broken anymore :space_invader: :space_invader:
> nodejs: use shared http-parser by default

- srcpkgs/diffutils/template
Since autoreconf is not run, mkdir_p remains undefined (@mkdir_p@).
Patch it to get the translations installed.
> diffutils: revive po/Makefile

- srcpkgs/xcruiser/template
Cross compilation is done by ignoring the ``INSTALL`` file instructions and generating a Makefile on the fly instead.
> New package: xcruiser-0.30

- srcpkgs/gtkspell3-devel
- srcpkgs/gtkspell3/template
This builds gtkspell 3.0.7 for GTK+3 only. The API is incompatible with 2.x versions, packages using that API can continue using the existing gtkspell packages.
With this package, it should be possible to build gnome applications (e.g. evolution) with spell check support.
> New package: gtkspell3

- srcpkgs/qtcreator/template
Also qt5-quickcontrols is required for qtcreator. Without it qtcreator
won't display the Welcome screen lists of sessions and projects.
> qtcreator: Add missing dependency

- common/environment/configure/autoconf_cache/arm-common
- common/environment/configure/autoconf_cache/common-glibc
- common/environment/configure/autoconf_cache/ix86-common
- srcpkgs/socat/template
musl's termios doesn't have c_ispeed.
> socat: unbreak musl builds for arm*, i686

- srcpkgs/dunelegacy/template
Data files can be found [over here](https://github.com/katlogic/dunelegacy/tree/115a5723176092966cef4fe1729abb2c1cb56cd5/data) ([download](https://github.com/katlogic/dunelegacy/archive/115a5723176092966cef4fe1729abb2c1cb56cd5.tar.gz)). Copy the ``PAK`` files to ``~/.config/dunelegacy/data``.
> New package: dunelegacy-0.96.3

- srcpkgs/gnome-desktop/template
Like in other packages disable gobject-introspection for cross builds.
> gnome-desktop: add build option 'gir'

- srcpkgs/libgnomekbd/template
Also fix cross building by setting LDFLAGS to the appropriate
${XBPS_CROSS_BASE}/usr/lib
> libgnomekbd: add build option 'gir'

- common/environment/setup/options.sh
I'm don't know if there is an easy way to obtain the function name for the msg_error.
The hint should suffice to detect erroneous use of `vopt_enable` as in #1862.
> vopt_enable: check for excess parameters

- srcpkgs/libgweather/template
Fix a possible typo: $(vopt_enable ...) doesn't expect true/false parameters,
but $(vopt_if ...) does.
> libgweather: fix cross building

- srcpkgs/gnome-disk-utility/template
This makes gnome-disk-utility build with musl libc.
> gnome-disk-utility: disable compile warnings

- srcpkgs/xorg-server/patches/musl-io.patch
- srcpkgs/xorg-server/template
In musl libc sys/io.h does not define in/out functions
> xorg-server: fix cross arm*-musl builds

- srcpkgs/gnome-menus/template
> gnome-menus: add build option 'gir'

- srcpkgs/gnome-bluetooth/template
- srcpkgs/gnome-boxes/template
- srcpkgs/gnome-clocks/template
- srcpkgs/gnome-contacts/template
- srcpkgs/gnome-documents/template
- srcpkgs/gnome-initial-setup/template
- srcpkgs/gnome-maps/template
- srcpkgs/gnome-music/template
- srcpkgs/gnome-online-accounts/template
- srcpkgs/gnome-online-miners/template
- srcpkgs/gnome-photos/template
- srcpkgs/gnome-shell/template
- srcpkgs/gnome-sound-recorder/template
- srcpkgs/gnome-weather/template
+ This should allow more gnome-* packages to be cross compiled
+ Some will still fail due to prerequisites not cross compilable
> gnome-*: add build option 'gir'

- srcpkgs/gnome-control-center/patches/musl-nofail-tests.patch
- srcpkgs/gnome-control-center/template
The test-datetime-gfx check fails because it is missing a not yet
installed data file. This causes the musl build process to abort,
while the glibc build continues.
This patch makes the Makefile continue on errors in datetime checks.
> gnome-control-center: Don't abort on failing check

- srcpkgs/minicom/patches/musl-sys_param_h.patch
- srcpkgs/minicom/patches/musl-vc_music.patch
- srcpkgs/minicom/template
Here xlint wanted me to use $DEBIAN_SITE while the original download was on a `alioth.debian.org`, not `ftp.debian.org`.
I switched to $DEBIAN_SITE's corresponding minicom-2.7-orig.tar.gz file to silence xlint :)
> minicom: unbreak musl

- srcpkgs/mesa-demos/template
The mesa-demos code including EGL/eglext.h expects some interfaces
which no longer exist in Mesa-10.6.0. Disable that code.
Closes #1871
> mesa-demos: exclude broken eglut/opengl code

- srcpkgs/apr/template
Without the dependency I saw this:
```
xml/apr_xml.c:35:19: fatal error: expat.h: No such file or directory
#include <expat.h>
^
compilation terminated.
```
It may have worked before because expat was always there or a dependency of libuuid-devel?
> apr: add missing make dependency expat-devel

- common/shlibs
- srcpkgs/libtorrent1-devel
- srcpkgs/libtorrent1/template
Create a new major version package of libtorrent(-rasterbar)
and switch to the new homepage http://www.libtorrent.org/
The license also changed from GPL-2 to BSD.
> New package: libtorrent1-1.0.5

- srcpkgs/qtcreator-full
- srcpkgs/qtcreator/patches/musl-no_execinfo_h.patch
- srcpkgs/qtcreator/template
+ Split into basic and full dependencies (qtcreator-full)
+ Patch to unbreak musl by removing references to execinfo.h + backtrace()
> qtcreator: update to 3.4.1

- srcpkgs/pcsc-ccid-contrib
- srcpkgs/pcsc-ccid-examples
- srcpkgs/pcsc-ccid/template
- srcpkgs/pcsc-ccid/update
The generic PC/SC CCID compliant smart card readers driver from the pcsclite author Ludovic Rousseau. Should work with most (read: more than pcsc-acsccid) USB card readers.
> New package: pcsc-ccid-1.4.19

- srcpkgs/ffmpeg/template
We have faac-devel and can thus enable AAC encoding in ffmpeg.
> ffmpeg: Enable AAC audio encoder

- common/hooks/do-fetch/00-distfiles.sh
- common/xbps-src/shutils/update_hash_cache.sh
- xbps-src
Closes #1952
Any successfully verified distfile is hard linked into `$XBPS_SRCDISTDIR/by_sha256/$cksum`. Before trying to download a distfile, an exsiting `$XBPS_SRCDISTDIR/by_sha256/$cksum` is hard linked to the `$distfile`.
There is a new xbps-src command `update-hash-cache` which will hard link your existing distfiles to their corresponding cache entries. You may run this once to initially setup the cache, while it isn't mandatory. It will merge distfiles from different directories with identical sha256sum and should thus reduce the space required on disk.
> xbps-src: implement a by_sha256 hash cache

- srcpkgs/vorbisgain/template
Out of the man-page:
-r, --recursive
Enter directories (recursively) and search for files, if
directories or file patterns are specified.  Note: Only
available if vorbisgain was configured with --enable-recursive.
> vorbisgain: enable recursive flag

- srcpkgs/tracebox/template
+ Use libcrafter git revision, because tracebox fails to build with libcrafter-0.3
> tracebox: update to 0.3

- srcpkgs/qupzilla/patches/fix-qtlocalpeer.patch
- srcpkgs/qupzilla/patches/fix-tldextractor.patch
The two fixes to build with Qt5-5.5.0 are already included in upstream and will become obsolete with the next version.
> qupzilla: fixes for Qt5-5.5.0

- srcpkgs/qca-qt5/patches/fix-qiodevice.patch
- srcpkgs/qca-qt5/template
Since Qt5-5.5.0 it seems to be necessary to explicitly `#include <QIODevice>`
if this class is used. In previous versions this header may have been included as a
side-effect by other Qt headers.
Also silence the exessive warnings regarding the macro _BSD_SOURCE by
replacing it with _DEFAULT_SOURCE.
> qca-qt5: Fixes for Qt5-5.5.0

- srcpkgs/fortune-mod/files/error.c
- srcpkgs/fortune-mod/files/error.h
- srcpkgs/fortune-mod/template
librecode expects to link against something which defines a function `void error(int status, int errnum, const char* format, ...);` which gnu libc defines. This is despite the fact that musl libc does not have error.h.
The easiest way around this is to add a function to the fortune-mod object files for musl builds which mimicks what glibc error(3) does.
> fortune-mod: unbreak musl

- common/shlibs
- srcpkgs/libxfce4ui/template
The gtk+3 libs are required for parole
> libxfce4ui: add gtk+3 and new shlibs

- srcpkgs/gst-plugins-bad/template
Not sure about
```
=> WARNING: gst-plugins-bad-0.10.23_12: libgstphotography-0.10.so.23 not found in common/shlibs!
=> WARNING: gst-plugins-bad-0.10.23_12: libgstsignalprocessor-0.10.so.23 not found in common/shlibs!
=> WARNING: gst-plugins-bad-0.10.23_12: libgstbasecamerabinsrc-0.10.so.23 not found in common/shlibs!
=> WARNING: gst-plugins-bad-0.10.23_12: libgstvdp-0.10.so.23 not found in common/shlibs!
```
> gst-plugins-bad: makedepends needs gettext-devel

- srcpkgs/libcdr/template
The `Makefile`s contain a trailing `-O0` in the `CXXFLAGS` which prevents`_FORTIFY_SOURCE`.
> libcdr: -O0 prevents _FORTIFY_SOURCE

- srcpkgs/proot/files/ptrace_compat.h
- srcpkgs/proot/patches/linux_wait_h.patch
- srcpkgs/proot/patches/musl_execinfo.patch
- srcpkgs/proot/patches/ptrace_compat.patch
- srcpkgs/proot/template
This makes proot build on musl, but requires testing to make
sure the resulting binary works as expected.
Also the glibc result need review, because my changes
to the objcopy parameters may be wrong:
man objcopy(1) does not list `--input` or `--ouput` parameters,
but just `--input-target` and `--output-target`.
> proot: unbreak musl

- srcpkgs/libtorrent/template
The homepage does not exist anymore, thus migrate to github
Use the github download location and rename file to include pkgname
Partially closes #1924
> libtorrent: update to 0.13.5

- srcpkgs/rtorrent/patches/no_xmlrpc_c_compile.patch
- srcpkgs/rtorrent/template
cross armv6hf-musl is broken. It doesn't find `__write` when linking the executable.
For now I'll leave it broken, as I don't know where to look for the problem.
> rtorrent: update to 0.9.5 and move to github

- .travis.yml
- common/travis/bootstrap.sh
- common/travis/build.sh
- common/travis/show_files.sh
- common/travis/xlint.sh
This PR adds an extra build job which only runs xlint on changed templates and disables xlint for all others.
Fixes #2017
> run xlint parallel

- srcpkgs/couchdb/files/couchdb/run
- srcpkgs/couchdb/patches/0001-build-support-OTP-18.0.patch
- srcpkgs/couchdb/patches/fix-configure.patch
- srcpkgs/couchdb/template
Upstream couchdb has a patch to fix building on Erlang 18. Additionally, the service file has couchdb fork to a background process which breaks how runit expects services to run.
> couchdb: fix build and runit file

- srcpkgs/openjdk/template
- The hotspot OS version tests supported at most Linux-3.x; add 4 and 4.1
- The -D_FORTIFY_SOURCE=2 conflicts with CXX_O_FLAG_NONE="-O0", thus remove it
> openjdk: fix building in current environment

- srcpkgs/gnome-mplayer/template
arm* targets require a fix for `gmtk` which is more than just adding `glib-devel` and runinng `autoreconf -if` in `pre_configure()`... there is some m4 macro missing (...GCONF.. whatever :)
> gnome-mplayer: unbreak x86_64-musl

- srcpkgs/libasr/patches/musl-inline-res_randomid.patch
- srcpkgs/libasr/template
The libasr from http://www.opensmtpd.org/archives/libasr-1.0.2.tar.gz has already had ./bootstrap ran, which seems to use autoconf/automake 1.14.1. This breaks the current build script, it tries to find aclocal-1.14, automake-1.14, etc.
Instead, this pulls the release from Github and runs ./bootstrap and now compiles correctly.
Interesting sidenote: the [libasr-1.0.2 announcement](https://www.opensmtpd.org/announces/libasr-1.0.2.txt) mentions that Github is the primary location for libasr information.
The other fix is for usage on musl - OpenSMTPD fails to get through ./configure on musl, because libasr uses the `res_randomid()` function from glibc/uclibc. I made a patch that implements the workaround from this issue: https://github.com/OpenSMTPD/libasr/issues/8
Note: this does not fix …
> fix compile w/ automake-1.15, inline res_randomid on musl

- srcpkgs/transmission/template
- Add missing includes which happen as side-effects with glibc
- Move usr/lib/locale to usr/share/locale for musl libc (better fix?)
> transmission: unbreak musl

- srcpkgs/bogofilter/template
I created bogofilter package which uses sqlite3 as database back-end.
Usually, other distros have bogofilter pacakge built with Berkeley DB as default and then create other (sub)packages with other back-ends.
I have old sqlite3 wordlist.db and have need for it; the package works for me, built on x86_64. 
Sincerely,
Gour
> New package: bogofilter-1.2.4

- srcpkgs/expat/patches/xmlparse.patch
- srcpkgs/expat/template
Description [is here](http://www.security-database.com/detail.php?alert=CVE-2015-1283)
We should perhaps scan for packages which include local (i.e. 3rdparty) versions of expat instead of using the system provided libs.
> expat: Patch to fix CVE-2015-1283

- common/shlibs
- srcpkgs/hiawatha/template
- srcpkgs/mbedtls/template
* Updates hiawatha to 9.14 and mbedtls to 2.0.0.
* Uses cmake for mbedtls instead of make
> Hiawatha 9.14

- srcpkgs/libstatgrab/patches/configure-musl.patch
- srcpkgs/libstatgrab/patches/os_info-musl.patch
- srcpkgs/libstatgrab/template
configure needs to know about `linux-musl`, and musl doesn't implement `_SC_LONG_BIT`
> libstatgrab: unbreak musl

- srcpkgs/lxqt-qtplugin/template
The gpg signature looks good, and gentoo uses the same hash:
https://github.com/gentoo/gentoo-portage-rsync-mirror/blob/master/lxqt-base/lxqt-qtplugin/Manifest
I can't find any information about the 0d996abc2081b9c77f5dc9c1d24b14ee44c47b9b906ee3f71fb2d28d04c72bb7 hash.
> lxqt-qtplugin: fix checksum

- srcpkgs/lxqt-panel/patches/int64-musl.patch
- srcpkgs/lxqt-panel/template
Together with https://github.com/voidlinux/void-packages/pull/2120 and https://github.com/voidlinux/void-packages/pull/2119 lxqt builds now with musl.
> lxqt-panel: unbreak musl

- srcpkgs/kdepimlibs/patches/gpgme_largefile.patch
- srcpkgs/kdepimlibs/template
The newer gpgme.h requires _FILE_OFFSET_BITS=64 to be defined,
because gpgme-devel was built with this configuration.
> kdepimlibs: Fix build with newer gpgme-devel

- srcpkgs/boost/patches/fix_poll_h.patch
- srcpkgs/boost/template
One example is the `openimageio` package which fails even after patching `#include <sys/poll.h>` to `#include <poll.h>` in the source, because it also includes boost's `socket_types.hpp`.
In glibc headers `/usr/include/poll.h` includes `/usr/include/sys/poll.h` so this patch shouldn't affect anyone, but silence or even unbreak some packages for musl libc.
> boost: fix incorrect include path

- srcpkgs/ilmbase/files/eLut.sh
- srcpkgs/ilmbase/files/toFloat.sh
- srcpkgs/ilmbase/template
The shell scripts produce the exact same output as their cpp couterparts.
Yes, `toFloat.sh` is pretty slow, because it generates 64K values.
> ilmbase: Workaround for cross compiling

- srcpkgs/bash/files/bash.sh
- srcpkgs/bash/template
This adds /etc/profile.d/bash.sh
```
```
> bash: source system bashrc on login

- srcpkgs/gstreamer/patches/fix_bison_grammar_y.patch
- srcpkgs/gstreamer/template
This patch fixes the compile error. I have no confirmation, if it
is the "Right Thing (tm)" to do, until upstream publishes their
own fix for this issue.
Fixes #2162
> gstreamer: fix grammar.y for bison >= 3.0.4

- srcpkgs/deluge/template
xdg-utils is needed to make sure that the "open folder" button works in the context menu of a torrent. If there is no xdg-utils installed then it will simply do nothing which is confusing. I think deluge uses (or tries to use) "xdg-open" which is in the xdg-utils package.
> deluge: add xdg-utils as a dependency

- srcpkgs/webkit2gtk/patches/fix_armv6l.patch
- srcpkgs/webkit2gtk/template
This is a yet untested try to fix the armv6l build - [see build log](http://build.voidlinux.eu/builders/armv6l_builder/builds/16220/steps/shell_3/logs/stdio).
The outcome should be tested by someone who owns an armv6l machine.
The assembler output generated by Source/JavaScriptCore/offlineasm/arm.rb
for the `mvlbl` pseudo opcode for armv6l is similar to that in the
`armMoveImmediate` function in the final else branch.
The difference is that it uses `.equ label, (x - y)` to define the
actual value, the difference between two labels, for `ldr reg, =label`.
See https://bugs.webkit.org/show_bug.cgi?id=131612 for a discussion
and https://bugs.webkit.org/show_bug.cgi?id=141288 if this works out.
FWIW: The generated output can be seen in the file …
> webkit2gtk: unbreak armv6l

- srcpkgs/espeak/template
The library is unusable without its data files.
Also fix typo.
> espeak: move data files into the library package (libespeak).

- srcpkgs/fail2ban/files/fail2ban/run
- srcpkgs/fail2ban/template
This provides the current stable version of fail2ban, with no batteries included.
Critiques and comments, lets have 'em!
> New package: fail2ban-0.8.14.

- srcpkgs/cross-aarch64-linux-musl/template
- srcpkgs/cross-arm-linux-musleabihf/template
- srcpkgs/cross-armv7l-linux-musleabihf/template
- srcpkgs/cross-i686-linux-musl/template
- srcpkgs/cross-mips-linux-musl/template
- srcpkgs/cross-mipsel-linux-musl/template
- srcpkgs/cross-mipsel-linux-muslhf/template
- srcpkgs/cross-x86_64-linux-musl/template
- srcpkgs/gcc/files/gcc-4.9.2-musl.diff
When linking against libgcc.a, there is an unresolved (in musl libc) external
__write() referenced from libgcc/config/arm/linux-atomic-64bit.c,
so make the patch replace it with libc write(2).
See: http://build.voidlinux.eu/builders/armv6l-musl_builder/builds/2991/steps/shell_3/logs/stdio
> cross-arm-linux-musleabihf: fix unresolved extern

- srcpkgs/sslh/files/sslh/run
- srcpkgs/sslh/patches/enable-pcre.patch
- srcpkgs/sslh/template
This adds a patch to sslh - it enables using PCRE as the regex library instead of using POSIX regex.
On musl, sslh doesn't compile w/ regex enabled because sslh makes use of a non-POSIX regex feature.
I have a PR open upstream for this fix - https://github.com/yrutschle/sslh/pull/62
> sslh: add pcre support (fixes musl)

- common/shlibs
- srcpkgs/cups-filters/template
- srcpkgs/evas_generic_loaders/template
- srcpkgs/inkscape/template
- srcpkgs/ipe/template
- srcpkgs/poppler-qt4/template
- srcpkgs/poppler-qt5/template
- srcpkgs/poppler/template
+ revbump packages depending on libpoppler.so.53 -> 54
> poppler{,-qt4,-qt5}: update to 0.35.0

- srcpkgs/gnome-games/template
This doesn't include aisleriot, because it can't be cross built due to guile(c).
> New package: gnome-games-1.0 (meta package)

- srcpkgs/ccache/template
Fix for cross compiling according to this mail:
```
Joel Rosdahl <joel@rosdahl.net> writes:
> I'm happy to announce ccache version 3.2.3.
Hate to be the bearer of bad news, but this fails to build for me on
late-model OS X:
$ ./configure
$ make 
gcc -DHAVE_CONFIG_H  -DSYSCONFDIR=/usr/local/etc -I. -I.  -g -O2 -Wall -W -c -o main.o main.c
...
gcc -DHAVE_CONFIG_H  -DSYSCONFDIR=/usr/local/etc -I. -I.  -g -O2 -Wall -W -c -o conf.o conf.c
make: *** No rule to make target `-lz', needed by `ccache'.  Stop.
The reason appears to be that the Makefile gets generated like so:
$ grep extra_libs Makefile
extra_libs = -lz
ccache$(EXEEXT): $(ccache_objs) $(extra_libs)
$(CC) $(all_cflags) -o $@ $(ccache_objs) $(all_ldflags) $(extra_libs) $(LIBS)
test/main$(EXEEXT): $(base_objs) $(test_objs) $(extra_libs) …
```
> ccache: update to 3.2.3

- srcpkgs/wireshark/INSTALL
- srcpkgs/wireshark/template
Permissions on dumpcap were too permissive.
> wireshark: restrict capturing to root and members of the wireshark group.

- srcpkgs/mps-youtube/template
mps-youtube was broken for awhile and I noticed the mps changelog mentioning a switch to python3.
> mps-youtube: fixed module error by changing python version

- srcpkgs/ca-certificates/files/remove-expired-certs.sh
- srcpkgs/ca-certificates/template
This is inspired by (beyond) linux from scratch ca-certificates build description.
The script is slightly modified for this pr.
Currently there are 3 expired certificates removed.
> ca-certificates: remove expired certificates

- srcpkgs/vim/template
The template failed to fetch `7.4.763` using `hg clone` for me:
```
requesting all changes
adding changesets
adding manifests
adding file changes
added 7030 changesets with 33364 changes to 2802 files
abort: unknown revision 'v7-4-763'!
```
Thus changed template to download from github.com
> vim: update to 7.4.827

- srcpkgs/fontforge/template
The needless `#include <execinfo.h>` should probably be reported upstream.
> fontforge: unbreak musl

- srcpkgs/openexr/template
The result needs testing on the cross platforms, though.
There is no guarantee the shipped tables `IlmImf/dwaLookup.h`
and `IlmImf/b44ExpLogTable.h` are okay to use as is.
Looking at the source generating the tables a minor difference in float
functions or floating point accuracy between the system which generated
the shipped tables and the cross targets *may* ruin the idea.
So only testing programs in this pkg or pkgs using libopenexr-devel on
arm* can eventually tell if this is ok.
> openexr: unbreak cross

- srcpkgs/musl-fts/template
This is intended to standardize handling of packages for musl libc
which require an fts(3) implementation. Adding musl-fts to the
makedepends and linking /usr/lib/libfts.a to the target (i.e.
`LIBS="-lfts"`) should suffice.
> New package: musl-fts-1.0

- srcpkgs/memcached-devel
- srcpkgs/memcached/patches/memcached-1.4.24-fix-signal.patch
- srcpkgs/memcached/template
The current build fails on musl - `#include <sys/signal.h>` generates a compiler warning and the build fails.
The warning is just that the correct include is `#include <signal.h>` - same for glibc.
The included patch has been submitted to upstream mailing list: https://groups.google.com/forum/#!topic/memcached/ThyxJORhxh0
> memcached: fix build in musl, add -devel subpkg

- srcpkgs/icecat/template
The cause for the annoying error message generated by
the spyblock@gnu.org overlay.xul was due to installed
resource had wrong permissions (0600 instead of 0644).
> icecat: fix resources permissions

- srcpkgs/firefox-esr/template
This adds the same presets for CFLAGS, CXXFLAGS and LDFLAGS as
in icecat (31.8.0) and fixes cross building for arm*-musl for me.
It could help firefox as well.
> firefox-esr: fix arm*-musl

- srcpkgs/runit/template
Fix a warning about the wrong type short being used for
getgroups(2) and setgroups(2) parameter 2 which causes the
i686 build to fail here, probably because of -Werror.
Also "modernize" the template's indentation and use
vbin, vman ...
> runit: fix -Werror failure for i686

- srcpkgs/base-system-busybox/template
- srcpkgs/runit-void/template
Fixing "initrd + busybox' switch_root" based boots
> base-system-busybox+runit-void: Using relative symbolic link to for /sbin/init

- srcpkgs/libreoffice-bin/template
I updated to 4.4.5 already, since 4.4.3 was no longer available.
We may update to 5.0.0 while I'm not sure a major version jump is desired.
> libreoffice-bin: update to 5.0.0

- srcpkgs/gogs/files/gopm-lite
- srcpkgs/gogs/template
The gogs build process relies on a tool called "gopm" - it allows for specifying specific versions of dependencies. Without it, "go get" pulls down the latest code from the needed dependencies and the build can break.
Instead of installing and using gopm, I wrote a short script (`misc/generate-distfiles`) to parse the .gopm file and generate distfiles lines, checksum lines, and the do_extract() function.
That's why the distfiles is so huge - it captures all the dependencies from the .gopm file in the source repo.
> gogs: update to 0.6.5

- README.md
- common/hooks/do-fetch/00-distfiles.sh
- xbps-src
The idea is to remove some burden from the original download
locations for distfiles by specifying one or more mirror locations.
+ Works with `http://` or `ftp://` mirrors for all supported `$XBPS_CHROOT_CMD` variants
+ Works with `file://` mirrors together with `uchroot` and `proot` (fixed a typo and it works now)
> Implement XBPS_DISTFILES_MIRROR (second try)

- Manual.md
This just adds a note about supplying licenses with packages. Are there any other licenses I should include?
> Manual.md: add note about supplying licenses

- srcpkgs/zile/template
Also fix *-musl by disabling the regeneration of the zile.1.in file.
The shipped version should be recent enough AFAICT.
@chneukirchen please merge if you agree.
> zile: fix cross compiling

- common/xbps-src/shutils/common.sh
- srcpkgs/gcc-multilib/patches/fix-inline_vfprintf.patch
- srcpkgs/gcc-multilib/template
Trying to build `gcc-multilib` failed because `glibc-32bit`
has no separate `srcpkg/glibc-32bit/template`, but is a
result of building `glibc` for target arch `i686`.
+ Also update gcc-multilib to gcc-4.9.3
> setup_pkg(): fix check for pkgname-32bit + update gcc-multilib

- srcpkgs/chroot-distcc/template
- srcpkgs/distcc/template
Distributing cpp is not possible (see man page example for
symbolic links), thus the symlink from cpp to distcc was wrong.
On the other hand it is very well possible to distribute cross
compiler jobs. For this to work the cross compiler must be
available on the slave host(s) as well.
> distcc: can't distribute cpp; add cross-gcc

- srcpkgs/mcomix/template
pkg_resources, a module imported from /usr/bin/mcomix, is from python-setuptools.
> mcomix: Added python-setuptools to depends

- srcpkgs/vpnc/patches/0001-fix-musl.patch
- srcpkgs/vpnc/template
commit 1779dabd7d1ac181f2fee102f55e9f8360c33006 causes:
vpnc: can't initialise tunnel interface: No such file or directory
> vpnc: revert part of musl patch

- srcpkgs/libdwarf/patches/add-soname.patch
- srcpkgs/libdwarf/template
This is to make sure libdwarf.so is added to the shlib-provides
> libdwarf: add soname to package

- srcpkgs/reiserfsprogs/files/musl-configure_ac.patch
- srcpkgs/reiserfsprogs/files/prints.c
- srcpkgs/reiserfsprogs/patches/musl-__compar_fn_t.patch
- srcpkgs/reiserfsprogs/patches/musl-long_long_min_max.patch
- srcpkgs/reiserfsprogs/patches/musl-prints.patch
- srcpkgs/reiserfsprogs/template
The modified source based on reiserfscore/prints.c is included in
files/prints.c to make it easily possible to apply fixes and create
a new diff against the original.
First test on a Void Linux musl box seem to indicate success.
There is still a chance of the prints.c conversion missing some aspects.
> reiserfsprogs: try to fix musl libc

- srcpkgs/vim/template
I added to the template came to flag [ClientServer](http://vimdoc.sourceforge.net/htmldoc/remote.html#clientserver).
The reason I added this flag is for the operation of [vmail] (https://github.com/danchoi/vmail/), an email client that uses vim as backend.
Oh, I took and updated version of vim for the latest.
https://github.com/danchoi/vmail/issues/173
> vim: Added flag clientserver and update version for 7.4.865

- srcpkgs/libclc-git/template
Update to git hash f9b8aac70c01a85cf70267320a97fe0c51fb15da
because the previous does no longer build with llvm-3.7.0
> libclc-git: update to 20150912

- srcpkgs/guilt/template
This is like quilt or mercurial queues but for git. Similar to stgit (stacked git) but patches are stored in plain text which means you can but them in turn in a separate git repository.
> New package: guilt-0.36

- srcpkgs/git-annex/template
Discovered that the git-annex build was missing the man pages and helper scripts. This patch should fix that.
> git-annex: Fix missing man pages and helper scripts

- srcpkgs/spotify/template
Currently an install of spotify without xz will result in this:
```
eater@eaterofvoiddesktop ~/projects/void-packages $ sudo xbps-install spotify                                                                                               <!127><g:origin/fixSpotifyInstall> 
Name    Action    Version           New version            Download size
spotify install   -                 0.9_7                  - 
Size required on disk:        5598KB
Free space on disk:             17GB
Do you want to continue? [Y/n] Y
[*] Downloading binary packages
[*] Verifying package integrity
spotify-0.9_7: verifying RSA signature...
[*] Running transaction tasks
spotify-0.9_7: unpacking ...
[*] Configuring unpacked packages
spotify-0.9_7: configuring ...
looking up repository.spotify.com
connecting to …
```
> spotify: add xz dependency so install doesn't fail at extracting tar.xz

- srcpkgs/boswars/template
Fixed location the boswars.desktop and boswars.png.
/home/travis/build/voidlinux/void-packages/masterdir/destdir//boswars-2.7/usr/share/applications/boswars.desktop/boswars.desktop
/home/travis/build/voidlinux/void-packages/masterdir/destdir//boswars-2.7/usr/share/pixmaps/boswars.png/boswars.png
> boswars: Fix location boswars.desktop and icon file

- srcpkgs/gpsd/files/gpsd/run
- srcpkgs/gpsd/template
Previously, I removed the /usr/lib/udev files from this package, but later realized they could be useful... Change reverted, runit script added.
> gpsd: add runit script

- srcpkgs/nodejs/patches/fix-libressl.patch
- srcpkgs/nodejs/template
Adds a patchset maintained at https://github.com/Gottox/node to build node with libressl.
This patch reverts some changes made in iojs-2.0.0 and and fixes some failing tests that were caused by incompatibilities between openssl and libressl.
> nodejs: add patch to build nodejs with libressl

- srcpkgs/avidemux/patches/musl-execinfo.patch
- srcpkgs/avidemux/patches/musl-memcpy.patch
- srcpkgs/avidemux/patches/musl-uint.patch
- srcpkgs/avidemux/template
Closes #2626
Disabled MesaLib, vdpau and libva for now.
I couldn't get vdpau/libva to work right. I could make avidemux link
against the packages, but there was no video frame image displayed in
the UI when the output was set to va or vdpau.
Perhaps I was just missing some additional dependency.
> New package: avidemux-2.6.10

- srcpkgs/patchutils/template
This includes useful utilities such as interdiff (for comparing two patches), lsdiff (list affected files), splitting, combining etc.
> New package: patchutils-0.3.4

- srcpkgs/task/template
By default, the function goes in /usr/share/doc/task/scripts/zsh. Installing it in /usr/share/zsh/site-functions means zsh users don't have to do anything to be able to use it.
> task: install zsh completion where zsh will find it

- srcpkgs/python-atomicwrites/template
- srcpkgs/python3.4-atomicwrites
This is one of the dependencies of vdirsyncer. I don't really need the Python 3.4 variant but I guess it is good form to build both, right?
> New package: python-atomicwrites-0.1.8

- srcpkgs/gtkmm2/template
Some header file which is included when building gtkmm2
now requires the c++ compiler to support c++11.
> gtkmm2: compile with -std=c++11

- srcpkgs/trinity/patches/arch.h.patch
- srcpkgs/trinity/template
When I use ```build_style=gnu-makefile```, occurs this errors:
```
=> trinity-1.5_1: running pre-build hook: 02-script-wrapper ... 
=> trinity-1.5_1: running do_build ... CC  arg-decoder.o arg-decoder.c:5:30: fatal error: arch.h: No such file or directory #include "arch.h" //PAGE_MASK ^ compilation terminated. Makefile:97: recipe for target 'arg-decoder.o' failed make: *** 
[arg-decoder.o] Error 1
```
> New package: trinity-1.5

- srcpkgs/python-keyring/template
- srcpkgs/python3.4-keyring
This is not a hard dependency so I could live without it. Distribution doesn't really come with a proper licence file: details are in the readme.
> New package: python-keyring-5.4

- srcpkgs/python-dbus/template
This is a fix for following error I encountered on `armv7hf`:
```sh
$ python2.7 -c 'import dbus; print dbus.version'  
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/lib/python2.7/site-packages/dbus/__init__.py", line 82, in <module>
import dbus.types as types
File "/usr/lib/python2.7/site-packages/dbus/types.py", line 6, in <module>
from _dbus_bindings import (
ImportError: /usr/lib/python2.7/site-packages/_dbus_bindings.so: undefined symbol: PyBytes_Type
```
From the `python2.7`  `config.log` [here](http://pastebin.com/w7zCVkAh), on lines 344 and 346 you can see there's some cross contamination between `python2.7` and `python3.4`.
> python-dbus: fix arm python2.7 bindings

- srcpkgs/khal/template
Command-line calendar that works with vdirsyncer for accessing caldav servers.
> New package: khal-0.6.0

- srcpkgs/lua52-MessagePack/template
Maybe this should be renamed to `lua52-MessagePack`? Or update it to use use `lua5.3` and add a `lua5.2` subpackage, because I *do* need a `lua5.2` version.
> lua-MessagePack: rename to lua52-MessagePack; fix lua5.2 dependencies

- srcpkgs/python-vobject/template
Needed for khard which is similarish to khal but for carddav rather than caldav.
> New package: python-vobject-0.8.1c

- srcpkgs/base-files/files/lsb_release
- srcpkgs/base-files/template
Some packages rely on FSG compliant output of lsb_release.
Implement according to http://man.cx/lsb_release for v1.4
> base-files: implement lsb_release options

- srcpkgs/fluxbox/template
Unfortunately we don't have gencat for musl libc.
> fluxbox: unbreak musl by disabling nls

- srcpkgs/perl-AnyEvent-I3/template
This is required for i3-save-tree to work which is already included as part of i3.
> New package: perl-AnyEvent-I3-0.16

- srcpkgs/rspamd/patches/enable-curve25519-donna_c.patch
- srcpkgs/rspamd/template
This fixes the [linker error](http://build.voidlinux.eu/builders/armv7l_builder/builds/18562/steps/shell_3/logs/stdio) (missing scalarmult_donna symbol),
but I don't know if it also works.
> rspamd: fix cross armv[67]l

- common/shlibs
- srcpkgs/grantlee5-devel
- srcpkgs/grantlee5/template
Change homepage because gitorious.org is moving to the
Internet Archive. Also create a new package grantlee5,
because newer versions (>5.0.0) link against Qt5.
> grantlee: update to 0.5.1

- srcpkgs/libusb/template
Need to disable paralle builds because they sometimes
fail. This seems to be a general libtool problem.
> libusb: update to 1.0.20

- srcpkgs/zsh-syntax-highlighting/template
i'm getting these errors:
```
/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:33: no such file or directory: /usr/share/zsh/plugins/zsh-syntax-highlighting/.version
/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:34: no such file or directory: /usr/share/zsh/plugins/zsh-syntax-highlighting/.revision-hash
```
> zsh-syntax-highlighting: install version and revision-hash

- srcpkgs/inkscape/template
inkscape needs python-lxml for the optimized svg export to work.
> inkscape: fix optimized export

- srcpkgs/qutebrowser/template
I'm not the maintainer of the package, but the upstream author :wink:
v0.4.0 breaks with later versions of Python 3.4 (and with 3.5) - just got a crash report because of that, so I thought I'd quickly update the package.
cc @uggedal
> qutebrowser: update to 0.4.1.

- srcpkgs/mksh/template
This change registers the MirBSD KornShell `mksh(1)` with the `sh` alternatives group.
> mksh: register 'sh' alternatives group.

- srcpkgs/Ice/template
Unbreaking musl boils down to just a few quick patches.
Enabling cross compilation requires some tools from Ice
for the host. This leads to the cross builds first compiling
a native build, which is probably not ideal.
If `hostmakedepends` would not insist on the current revision
of the package's *own* template, things could go faster.
It works locally and may work on travis-ci and the build hosts.
> Ice: unbreak musl and fix cross build

- common/hooks/do-fetch/00-distfiles.sh
- srcpkgs/drbd-utils/template
If a distfile changed its checksum (SHA256) without at the same time
also changing its version, the distfile cache needs to be purged.
This is done by verifying only for already existing distfiles that the
specified checksum matches. If it does not, the file and its entry in
/host/sources/by_sha256 are purged using the inode number of the file.
The second loop then as usual fetches the distfiles and verifies their
checksum against the list entry.
> 00-distfiles.sh: add code to purge wrong checksum

- srcpkgs/zsh/template
zsh is no POSIX compatible shell. They are working on it, but I think, that it will have many bad implications to use it as an sh alternative.
> Revert "zsh: register 'sh' alternatives group."

- srcpkgs/sun7i-kernel/files/config
- srcpkgs/sun7i-kernel/template
archlinuxarm removed `core/linux-sun7i` in favor of multi-platform, mainline armv7 kernel, so now the link to the patches are dead.
> sun7i-kernel: update to 3.4.104.

- srcpkgs/gumbo-parser-devel
- srcpkgs/gumbo-parser/template
The same source tarball also includes a python module along with a setup.py which should ideally also be packaged. I'm only actually interested in having the C library available myself but if you have suggestions on how to combine the gnu-configure and python-module build styles then let me know.
> New package: gumbo-parser-0.10.1

- srcpkgs/urxvt-perls/template
The clipboard script does not depend upon xsel. It can be configured to use any command.
Sorry, this time with just one commit.
> urxvt-perls: remove xsel dependency

- srcpkgs/libwebsockets/template
Update libwebsockets to 1.5 - note that /usr/lib/cmake is no longer installed due to upstream change:
http://git.libwebsockets.org/cgi-bin/cgit/libwebsockets/commit/CMakeLists.txt?id=3ae1badae7a05e0982e0dfbcb078da3d4b92a81d
> libwebsockets: update to 1.5

- srcpkgs/spim/template
This is a zip file from the creator's homepage, not the project homepage. The code for spim has not changed in a while. It is still often used in university classes, as the creator acknowledges. I took a hint from of Gentoo and FreeBSD's ports, and just built spim from [here](http://pages.cs.wisc.edu/~larus/SPIM/) instead of fiddling with SVN checkouts. Since the page in question belongs to the author (Dr. James Larus), I feel it is an acceptable substitute to the official project page (where there are not zip files or tarballs for easy download).
> New package: spim-8.0

- common/xbps-src/shutils/common.sh
Some autotool files (configure.ac) expect host build flags to be
defined as BUILD_CFLAGS, BUILD_CXXFLAGS, BUILD_CPPFLAGS and
BUILD_LDFLAGS. Especially these files tend to default to
LDFLAGS for BUILD_LDFLAGS, which makes host utilities built
with these flags fail with buildpie=yes because of differing
compiler and linker options.
One example is libatasmart where this patch fixes the build.
> common.sh: set BUILD_XXXFLAGS as autoconf defaults

- srcpkgs/libsasl/patches/0012-fix-ac_cv_names.patch
- srcpkgs/libsasl/template
+ Patch saslauthd/configure.ac to use ac_cv_name variables
+ Remove check for Kerberos4 (we don't support it)
+ Use autoreconf once
Closes #3022
> libsasl: fix for build -fPIE

- srcpkgs/doxygen/patches/fix-version_check.patch
- srcpkgs/doxygen/template
The checks did not take care of a change in YY_FLEX_MINOR_VERSION
and now failed for flex>=2.6.0
> doxygen: fix bogus flex version checks

- srcpkgs/libdca/template
When linking the pow(3) and log(3) functions are not found.
> libdca: add libm to LDFLAGS

- srcpkgs/mozjs24/template
It won't build with PIE, because configure detects a compiler bug.
> mozjs24: set nopie=yes

- srcpkgs/chromium-widevine/template
old url was broken on chromium-pepper-flash, so I ~~stole the pepper flash url & sha~~updated it with the new ones to this since so it works again/
> chromium-widevine: new chrome version 46.0.2490.86

- common/hooks/post-install/02-remove-perl-files.sh
- common/hooks/post-install/02-remove-python-bytecode-files.sh
- common/hooks/post-install/03-remove-empty-dirs.sh
`find` would report an error because PKGDESTDIR didn't exist. This makes sure it exists to run the hooks.
> common/hooks: Fix hooks when build_style=meta

- srcpkgs/strongswan/template
Also ensured subdirectories of `/etc/ipsec.d/` wouldn't just be removed after the tarball extracts them.
> strongswan: updated to 5.3.5.

- srcpkgs/grub/template
I tried to patch include/grub/i386/tsc.h and grub-core/loader/i386/xnu.c
to avoid clobbering %rbx (or %ebx) when using cpuid, but finally the
linking of trig.module would fail due to picking up the LDFLAGS.
Disabling PIE seems to be the only way for now.
If someone wants to try to fix the trig.module linking stage, here's the [modified tsc.h](http://sprunge.us/iKWJ) and [modified xnu.c](http://sprunge.us/QMge)
> grub: set nopie=yes

- srcpkgs/TwitchNotifier/template
One substantial stability problem was fixed so I have released a new minor version and this PR updates the package in voidlinux.
> TwitchNotifier: update to 0.4.2

- srcpkgs/pam-krb5/template
Issue #3119
Upstream calls itself pam-krb5. It seems to be a tossup between
that and libpam-krb5, so I flipped a coin and named with upstream.
> New package: pam-krb5-4.7.

- srcpkgs/python-tables/patches/01_no_utils
- srcpkgs/python-tables/template
- srcpkgs/python3.4-tables
I droped the utils because the bang line is allways changed to `#!/usr/bin/python3.4`.
> New Package python-tables 3.2.2

- srcpkgs/utox/template
This will require the toxcore-git update to build properly.
> utox: update to 0.4.5

- srcpkgs/owncloudclient/template
I had to do the following:
$ ./xbps-src zap
$ ./xbps-src binary-bootstrap
before build would work. Not sure if related to my package, or just an update to void-packages that I haven't noticed.
> owncloudclient: update to 2.1.0

- srcpkgs/libvirt/template
if dnsmasq isn't installed while building libvirt, it wil be unable to find dnsmasq at runtime. and when enabling NAT for example you will be hit with errors like:
```
Cannot check dnsmasq binary dnsmasq: No such file or directory
```
since finding a path doesn't really matter on which architecture it is, I've added it to hostmakedepends. if this is wrong please correct me.
Source of solution: https://bugs.archlinux.org/task/35183 
`./xbps-src pkg libvirt` ran successfully and without error
> make sure that dnsmasq is installed when building libvirt

- srcpkgs/libdbus-c++/patches/fix-mutex-init.patch
- srcpkgs/libdbus-c++/patches/musl-ssize_t.patch
- srcpkgs/libdbus-c++/patches/musl-uint.patch
- srcpkgs/libdbus-c++/template
I found a way to replace the non-portable mutex init through PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP  with this code fragment at http://stackoverflow.com/a/7963765
> libdbus-c++: unbreak musl

- srcpkgs/perl/template
because of broken paths in /usr/lib/perl5/core_perl/Config_heavy.pl
```
/usr/lib/perl5 % grep -ri hardened-
core_perl/Config_heavy.pl:config_arg21='-Doptimize=-specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1  -fstack-protector-strong -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe   -g'
core_perl/Config_heavy.pl:config_args='-des -Dusethreads -Duseshrplib -Dprefix=/usr -Dvendorprefix=/usr -Dprivlib=/usr/share/perl5/core_perl -Darchlib=/usr/lib/perl5/core_perl -Dsitelib=/usr/share/perl5/site_perl -Dsitearch=/usr/lib/perl5/site_perl -Dvendorlib=/usr/share/perl5/vendor_perl -Dvendorarch=/usr/lib/perl5/vendor_perl -Dscriptdir=/usr/bin -Dvendorscript=/usr/bin -Dinc_version_list=none -Dman1ext=1p -Dman3ext=3p -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 …
```
> perl: remove -specs hardened-cc1

- srcpkgs/epson-inkjet-printer-escpr/template
i added cups-filter as runtime dependency because without it's not possible to print anything
> epson-inkjet-printer-escpr: update to 1.6.1.

- srcpkgs/rpi-kernel/template
This fixes a problem with building external modules on a Raspberry Pi 2
> rpi-kernel: fix includes for rpi2

- srcpkgs/dovecot-plugin-pigeonhole/template
Current version of dovecot in the repo is not ABI compatible to the one the pigeonhole plugin is built against. Setting _dovecot_ver fixes this
> dovecot-plugin-pigeonhole: build for current dovecot version

- srcpkgs/salt/files/salt-api/run
- srcpkgs/salt/files/salt-master/run
- srcpkgs/salt/files/salt-minion/run
- srcpkgs/salt/files/salt-syndic/run
- srcpkgs/salt/template
The inclusion of `python-devel` is only because the Manual indicates it is necessary for cross compilation.
I chose not to split into client and server packages because the difference is 1 executable and 1 service folder. Also, neither Gentoo nor Arch split them into different packages.
This is a tool similar to ansible, puppet, and chef. I'm working on including explicit void support (mainly identifying a void system and using xbps) in the Salt code.
> New package: salt-2015.8.3

- srcpkgs/dvdauthor/template
dvdauthor requires that a default video format be set, NTSC for the US, Canada, and most of South America,  or PAL for most of Europe and parts of Asia. This can be done at build time or set in the user's environment.
> dvdauthor: add build_options for default video format (NTSC or PAL)

- srcpkgs/pam_radius_auth/template
Software is called `pam_radius_auth`. All two files to be installed are named that way. To download them, you get them from `pam_radius`. I flipped a coin and went with `pam_radius_auth` and hardcoded `pam_radius` where necessary.
> New package: pam_radius_auth-1.4.0

- srcpkgs/libtirpc/patches/fix_missing_rpc_get_default_domain+fix_musl.patch
- srcpkgs/libtirpc/template
There is one (obsolete) function in rcp_soc that is helps provide des authentication functionality, which we disable on musl. Without this patch, the .so is unusable because it needs `authdes_seccreate`.
> libtirpc: actually fix musl

- srcpkgs/libvirt/template
portablexdr is flaky and often doesn't work, so use libtirpc instead.
> libvirt: use libtirpc

- srcpkgs/bash-completion/template
since we have /etc/bash/bashrc.d/ we could put bash_completion.sh to ensure it's always loaded and not only on login-shells.
> bash-completion: source from bashrc, not profile

- srcpkgs/minidlna/files/minidlnad/run
- srcpkgs/minidlna/template
1. -S runs minidlnad in the foreground without excessing logging (-d)
2. Redirecting stderr to stdout allows users to log output via svlogd
> minidlna: use -S instead of -d, redirect stderr to stdout

- srcpkgs/qtox/template
- srcpkgs/toxcore-git/template
Toxcore 20151225
qtox 1.2.2
These are grouped to prevent needing to rebuild utox and qtox once toxcore pushes.
> Update qtox, and toxcore to their respective new versions.

- srcpkgs/openimageio/template
im skipping the 1.6 branch for now. has to many portability issues atm.
> openimageio: update to 1.5.23.

- srcpkgs/systemtap/template
Unbreaks build for glibc based systems. *-musl still broken.
> systemtap: update to 2.9.

- srcpkgs/meld/template
Without gsettings-desktop-schemas installed meld crashes with:
(meld:29458): GLib-GIO-ERROR **: Settings schema 'org.gnome.desktop.interface' is not installed
Trace/breakpoint trap
> meld: depend on gsettings-desktop-schemas

- srcpkgs/ppsspp/template
[native](https://github.com/hrydgard/native) isn't used anymore and [armips](https://github.com/Kingcom/armips) is now required to build the package.
> ppsspp: update to 1.1.1.

- srcpkgs/memtest86+/patches/00.memtest86+-5.01-no-scp.patch
- srcpkgs/memtest86+/patches/01.memtest86+-5.01-no-optimization.patch
- srcpkgs/memtest86+/patches/02.memtest86+-5.01-compile-fix.patch
- srcpkgs/memtest86+/patches/03.memtest86+-5.01-crash-fix.patch
- srcpkgs/memtest86+/patches/04.memtest86+-5.01-fgnu89-inline.patch
- srcpkgs/memtest86+/template
With the help of Fedora project packaging (http://pkgs.fedoraproject.org/cgit/rpms/memtest86+.git/). Fix #3526
> memtest86+: fix compilation for gcc-4.7.2 and later, fix PCI scan

- common/shlibs
- srcpkgs/gnutls/template
- srcpkgs/nettle/template
- srcpkgs/qemu/template
- srcpkgs/rdfind/template
GnuTLS 3.3 can use Nettle 3 since mid-2015, and recent security fixes are a good reason to do so.
GnuTLS 3.4 is declared stable now, too, but will require rebuilding ~35 packages.
> Nettle 3.2

- srcpkgs/adobe-flash-plugin/template
Despite the `adobe-flash-plugin` being marked as restrictive and [requiring manual building](https://wiki.voidlinux.eu/Flash), the package would always fail to build as the URL was pointing to the wrong location.  This patch points XBPS to the right place and the package can be installed successfully once built.
> adobe-flash-plugin: fixed URL

- srcpkgs/qtox/template
- srcpkgs/toxcore-git/files/toxbootstrapd/run
- srcpkgs/toxcore-git/template
Also split off the toxcore-git bootstrap daemon and create a runit service for it.
> qtox: update to 1.2.4

- srcpkgs/docker/files/docker/run
- srcpkgs/docker/template
Docker has completely abandoned the `-d` daemon option with their version 1.10.0.
This fixes the runit `run` script with the `daemon` option.
> docker: Fix deprecated daemon option (-d)

- srcpkgs/libpurple-facebook/template
I know that version number seems pretty weird - but that seems to be how the author does releases: https://github.com/jgeboski/purple-facebook/releases
> New package: libpurple-facebook-20160125.92885e0456ed

- srcpkgs/fltk/patches/Fl_XFont_On_Demand.patch
- srcpkgs/fltk/template
This patch was merged into fltk subversion, but no release contains it
yet:
http://www.fltk.org/str.php?L3156
Without it, octave will display teh following error message, even with
teh --no-gui option:
```
error: /usr/lib/octave/4.0.0/oct/x86_64-unknown-linux-gnu/PKG_ADD: /usr/lib/octave/4.0.0/oct/x86_64-unknown-linux-gnu/__init_fltk__.oct: failed to load: /usr/lib/libfltk_gl.so.1.3: undefined symbol: _ZN18Fl_XFont_On_Demand5valueEv
error: called from
/usr/lib/octave/4.0.0/oct/x86_64-unknown-linux-gnu/PKG_ADD at line 3 column 1
```
and fail to add '.' (teh current directory) to teh load path.
> fltk-1.3.3: Fl_XFont_On_Demand.patch

- srcpkgs/python3.4-cairo/template
This PR deals with #3602 until such time as upstream fixes the laughably outdated version of waf they are shipping.
> python3.4-cairo: set nocross until upstream fixes waf

- srcpkgs/sessreg/template
For musl define _PATH_UTMPX analogous to _PATH_WTMPX.
Since musl 1.1.13 there's a stub for `utmpxname()` in `/usr/include/utmpx.h` and thus configure sets `#define HAVE_UTMPXNAME 1` in `config.h`. See http://git.musl-libc.org/cgit/musl/tree/WHATSNEW section *1.1.13 release notes*
> sessreg: fix musl build again

- srcpkgs/vim/template
`hostmakedepends+="glib-devel"` since the gvim build now uses `glib-compile-resources`.
> vim: update to 7.4.1376.

- srcpkgs/bitcoin/template
Notes on changes:
* `--with-libressl` flag: required in order to configure
* qt5 gui toolkit: now default in bitcoin
* `--with-gui=qt4` ignored anyway when building with qt5 dependencies so replaced it with `--with-gui`
> bitcoin: update to 0.11.2.

- srcpkgs/samba/files/nmbd/log/run
- srcpkgs/samba/files/smbd/log/run
- srcpkgs/samba/template
Syslog is limited to a set of predefined facilities.  The facility
names nmbd and smbd are not on that list, so the loggers were not
actually working till now.
> samba: fix loggers.

- srcpkgs/clipit/template
Clipit requires xdotools for the "Automatically paste selected item" setting, else the intended functionality will not work, and it will spit error into the console, listing the missing dependency.
> Add xdotool to depends for clipit

- srcpkgs/lollypop/template
Closes #3705 
_Note_: we don't have `python3.4-pylast` and I don't know if using `python3.4-pip`
and running `pip3 install pylast` would be sufficient.
> New package: lollypop-0.9.87

- srcpkgs/libreoffice/patches/0001-poppler-version.patch
- srcpkgs/libreoffice/patches/0002-std-isnan.patch
- srcpkgs/libreoffice/patches/0003-configure_ac-libc-version.patch
- srcpkgs/libreoffice/patches/0004-musl-execinfo_h.patch
- srcpkgs/libreoffice/patches/0005-firebird-glibc.patch
- srcpkgs/libreoffice/patches/0006-firebird-libio.patch
- srcpkgs/libreoffice/patches/0007-firebird-patches.patch
- srcpkgs/libreoffice/patches/0008-musl-sys_time_h.patch
- srcpkgs/libreoffice/patches/0009-musl-unistd_h.patch
- srcpkgs/libreoffice/template
It builds with musl libc. Installed language is just en-US, because
building many or all takes way too long. For i18n support there are
separate packages using the precompiled RPMs from the website.
(I'll create that PR after this one is merged)
Cross compiling does not work yet, but should be possible after some
more tweaking and patching.
Considered WIP because I may be missing some `--with-system-*` options.
> New package: libreoffice-5.1.0.3

- common/environment/build/timestamp-macros.sh
- common/environment/configure/timestamp-macros.sh
- common/environment/install/timestamp-macros.sh
- common/environment/setup/git.sh
- common/hooks/pre-pkg/90-set-timestamps.sh
- common/xbps-src/shutils/chroot.sh
This PR overwrites timestamps that depend on timestamps with the
commit date of a package.
> environment/build: overwrite __DATE__, __TIME__, and __TIMESTAMP__ macros.

- srcpkgs/bitcoin/template
Notes:
* added qrencode for qr code support
* no longer depends on openssl but on libevent
* official changelog [here](https://bitcoin.org/en/release/v0.12.0)
> bitcoin: update to 0.12.0.

- srcpkgs/tcc/template
The x86_64 builds ok, while there are probably critical warnings
for the i686 build. Needs testing by someone who knows how to.
Edit: the warnings did appear here, but not on travis-ci. Strange...
Closes #3717
> tcc: change to use http://repo.or.cz/tinycc.git

- srcpkgs/nss-pam-ldapd/files/nslcd/run
- srcpkgs/nss-pam-ldapd/template
This package allows systems running glibc to pull user and group information from a remote server.  This is part of the large request from issue #3119.
> New Package: nss-pam-ldap_0.9.6

- srcpkgs/rxvt-unicode/template
Using the --enable-unicode3 option allows urxvt to display high-range
unicode characters, including those used by the popular "powerline"
theme.
This time, setting the build option to be enabled by default.
> rxvt-unicode: build with unicode3 by default

- srcpkgs/lightdm-webkit-greeter/template
More of the software for #3119.  Adds the webkit greeter which allows log in forms to be basically webpages with carefully formatted webpages.
> New package: lightdm-webkit-greeter_2.0.0

- srcpkgs/perl-Glib/template
For certain definitions of "fixed".
Builds fail with a myriad of type width errors, then finally with an error trying to load a glib which is the wrong ELFCLASS for the target.
> perl-Glib: fix cross builds

- common/shlibs
- srcpkgs/geany-plugins/template
- srcpkgs/libgit2-glib/template
- srcpkgs/libgit2/template
- srcpkgs/slcp/template
- srcpkgs/stagit/template
libgit2-glib currently broken by incompatible API changes.
> libgit2: update to 0.24.0 (soname bump).

- srcpkgs/pinentry-emacs
- srcpkgs/pinentry/template
This requires some extra code on the emacs side to work.
With 24.5, that's a package from elpa.  So I won't be
the least bit disappointed if this PR gets rejected.
> pinentry: build pinentry-emacs.

- srcpkgs/burp2-client
- srcpkgs/burp2-doc
- srcpkgs/burp2-server/burp2-client.INSTALL.msg
- srcpkgs/burp2-server/files/burp2-server/run
- srcpkgs/burp2-server/template
Along with burp-{client,server} packages (1.4.40): 
* burp-client 2.x does not work with burp-server 1.x, 
* automatic upgrade of XBPS package would not be avoided from 1.4.40 to 2.0.34 (see issue https://github.com/voidlinux/xbps/issues/153)
So create packages with a new  prefix (burp**2**-... instead of burp-..)
> New package: burp2-2.0.34

- srcpkgs/gst-libav/template
- srcpkgs/gst-plugins-bad1/template
- srcpkgs/gst-plugins-base1/template
- srcpkgs/gst-plugins-good1/template
- srcpkgs/gst-plugins-ugly1/template
- srcpkgs/gst1-python/template
- srcpkgs/gstreamer1/template
The gst-libav build triggers a gcc bug on musl:
16700 In file included from libavcodec/hevcdsp_template.c:26:0,
16701                  from libavcodec/hevcdsp.c:111:
16702 libavcodec/hevcdsp_template.c: In function 'put_hevc_qpel_hv_8':
16703 libavcodec/hevcdsp_template.c:655:18: internal compiler error: in vect_analyze_data_ref_accesses, at tree-vect-data-refs.c:2566
16704  static void FUNC(put_hevc_qpel_hv)(int16_t *dst,
16705                   ^
16706 libavcodec/bit_depth_template.c:90:25: note: in definition of macro 'FUNC3'
16707  #define FUNC3(a, b, c)  a ## _ ## b ## c
16708                          ^
16709 libavcodec/bit_depth_template.c:92:18: note: in expansion of macro 'FUNC2'
16710  #define FUNC(a)  FUNC2(a, BIT_DEPTH,)
16711                   ^
16712 …
> gstreamer*: update to 1.8.0

- srcpkgs/tigervnc/patches/xorg118.patch
- srcpkgs/tigervnc/template
My previous packaging of tigervnc didn't properly build the Xvnc program because it requires the xorg-server source to build. The build instructions closely mirror the documented instructions at tigervnc.org, plus a patch from the Arch Linux PKGBUILD to properly support xorg-server-1.18 source trees.
> tigervnc: Integrate xorg source build so that Xvnc is built

- srcpkgs/xastir/template
Some more amatuer radio software.  The build is marked broken on all arm and musl systems.  Years of code cruft mean this is not likely to change anytime soon, however conversations with the upstream project suggest they will consider patching thier build in the next release cycle, which if current rate is any example, should be some time next year.
> New package: xastir-2.0.6

- srcpkgs/python-gtkglext/template
needed by xpra to enable opengl acceleration
> New package: python-gtkglext-1.1.0

- srcpkgs/fs-repo-migrations/template
- srcpkgs/go-ipfs/INSTALL.msg
- srcpkgs/go-ipfs/template
The fs-repo-migrations package isn't really a dependency, but
included here because people will need it when upgrading.
Also added two hostmakedepends.
> go-ipfs: update to 0.4.0.

- srcpkgs/gloobus-preview/template
Making the video codec support complete (via the gstreamer plugins), so videos preview properly.
> gloobus-preview: Update Video Codec Support

- srcpkgs/pixman/patches/musl-static__thread-scanline_buffer.patch
- srcpkgs/pixman/template
Use `static __thread` storage for a large buffer which was
allocated in the stack frame. Musl has a rather small per
thread stack frame size.
> pixman: try to fix musl stack size issue

- srcpkgs/cairo/patches/musl-stacksize.patch
- srcpkgs/cairo/template
Another patch to reduce the stack frame footprint of a core libary to overcome musl libc's tiny per thread stack frame size. See #4133
> cairo: reduce stack size footprint for musl

- common/shlibs
- srcpkgs/edac-utils/files/edac/run
- srcpkgs/edac-utils/template
- srcpkgs/libedac
- srcpkgs/libedac-devel
The service has several flaws:
1) The sequences 'start' and 'start, stop, start' produce different
system states. The first invocation of start will import and mount all
file systems. Stopping the service will unmount them, but not export
them. Running start again will not do anything, leaving the user with
unmounted file systems.
2) It imports all storage pools, not just those that are noted in the
cache. It's usually ill-advised to import all available pools.
3) It is different from all the other file systems and storage layers
that Void supports, which are all handled in stage 1.
This change depends on voidlinux/void-runit#46 for the replacement
solution.
> zfs: remove zfs-import service

- srcpkgs/lua-lpeg/template
- srcpkgs/lua51-lpeg
- srcpkgs/lua51-mpack/template
- srcpkgs/neovim/template
Neovim now depends on `lua-mpack`  (insead `lua-MessagePack`), which is only compatible with Lua 5.1
> neovim: update to 0.1.4

- common/shlibs
- srcpkgs/mit-krb5/template
Since kerberos is often used in conjunction with ldap, it is often preferable to use ldap as the backing database for the master KDC.  This also permits the operation of multi-master KDC environments.
> mit-krb5: enable ldap database support

- srcpkgs/spotify/template
The new version (1.0.31) segfaults in their alsa output driver and the current version (1.0.29) is no longer available on the download server.
> spotify: downgrade to 1.0.28

- srcpkgs/catalyst/files/4.6-void-user_page.patch
- srcpkgs/catalyst/template
Obviously should be an upstream patch, but AMD doesn't care about Linux anyway.
So, here is some ducktape.
Still needs xorg-server-1.7 and xf86-input-evdev-2.10.0 to work. Maybe put them back in the current repo, so users don't have to build it themselves? The archives don't go back that far.
> catalyst: patched for linux4.6 & update to 15.302

- srcpkgs/google-chrome-bin/template
google-chrome as a managed package.  After conversation with @dinoocch this PR replaces #3792 .
> new package: google-chrome-bin-51.0.2704.63

- srcpkgs/libcaca/template
Download source from official github repository tags and add libX11-devel as build depend for the x11 driver.
> libcaca: update source and add x11 driver.

- srcpkgs/adobe-flash-plugin/template
This addresses how Firefox complains that Shockwave Flash is dangerously old.
> adobe-flash-plugin: update to 11.2.202.626.

- srcpkgs/trojita/template
This package also provides `libtrojita_plugins.so`, should I include it in `common/shlibs`? I currently don't see any use of it.
> New package: trojita-0.7

- srcpkgs/musl-bootstrap/template
- srcpkgs/musl/patches/fix-failure-to-obtain-EOWNERDEAD-status-for-process-shared-robust-mutexes.patch
- srcpkgs/musl/template
Added upstream patch:
>Linux's documentation (robust-futex-ABI.txt) claims that, when a
>process dies with a futex on the robust list, bit 30 (0x40000000) is
>set to indicate the status. however, what actually happens is that
>bits 0-30 are replaced with the value 0x40000000, i.e. bits 0-29
>(containing the old owner tid) are cleared at the same time bit 30 is
>set.
>
>our userspace-side code for robust mutexes was written based on that
>documentation, assuming that kernel would never produce a futex value
>of 0x40000000, since the low (owner) bits would always be non-zero.
>commit d338b506e39b1e2c68366b12be90704c635602ce introduced this
>assumption explicitly while fixing another bug in how non-recoverable
>status for robust mutexes was tracked. presumably the tests conducted
>at that …
> musl: fix failure to obtain EOWNERDEAD status for process-shared robust mutexes

- srcpkgs/wps-office/template
There's no patchlevel for this release, but the token is retained to account for future releases.
> wps-office: update to 10.1.0.5672a21

- xbps-src
This results in a more consistent behavior with other base utils.
> xbps-src: Preprocess arguments using getopt in order to allow options before and after XBPS_TARGET.

- srcpkgs/fish-shell/template
2.3.1 is not available from fishshell.com; use the release page instead
> fish: update to 2.3.1

- srcpkgs/rspamd/files/rspamd/run
- srcpkgs/rspamd/template
The run script had a UTF-8 non-breaking space character inside of `rspamd -f`
As far as I know, shell doesn't treat it as a whitespace, so the script fails to run..
The output of xxd, notice there's two bytes being used between `rspamd` and `-f`
```
$ xxd /etc/sv/rspamd/run 
00000000: 2321 2f62 696e 2f73 680a 5b20 2d72 2063  #!/bin/sh.[ -r c
00000010: 6f6e 6620 5d20 2626 202e 202e 2f63 6f6e  onf ] && . ./con
00000020: 660a 6578 6563 2072 7370 616d 64c2 a02d  f.exec rspamd..-
00000030: 6620 247b 4f50 5453 7d0a                 f ${OPTS}.
```
> rspamd: remove non-breaking space from run script

- srcpkgs/google-chrome/template
As merged this template contained some leftovers from the *.deb that
this is repackaged from, as well as the icons were not copied into the
correct place to be usable.  This commit fixes both of these issues.
> google-chrome: Template cleanup and icon fix

- srcpkgs/rspamd/files/rspamd/run
- srcpkgs/rspamd/template
The default rspamd config needs a writable log directory and run
directory.
Additionally, rspamd refuses to start if run as root.
> rspamd: more run script fixes

- srcpkgs/autojump/template
- srcpkgs/autojump/update
Resolves #4438.
This has got a fairly convoluted installer, thus the need for the custom do_install().  As this isn't a python module I don't really see much point in building it against anything but the default system python.
> New package: autojump-22.3.4

- srcpkgs/kodi/patches/fix-curl-750-compatibility.patch
- srcpkgs/kodi/template
Patch taken from xbmc/xbmc#10160 (thanks @fritsch for taking care of it). The patch is from kodi master but the relevant code was not changed since the 16.1 release so it applies cleanly against that version as well. Tested building and running kodi with this patch on my Void i686 VM. Fixes #4497
> kodi: fix building against curl 7.50.0 (#4497)

- srcpkgs/adobe-flash-plugin/template
This addresses Firefox blocking Adobe Flash from running due to being outdated.
> adobe-flash-plugin: update to 11.2.202.632

- common/shlibs
- srcpkgs/fftw/template
Remove the tests for CNTVCT for armv7 and CNTVCT_E0 for armv8 when
cross-compiling, because they will fail. Not supporting a possibly
available cycle counter may be less than optimal, while it should work.
> fftw: enable openmp and fix armv7* build

- srcpkgs/jeti-filemanager/template
changes done from verison 1.2.2 to 1.2.3
* bugfix, sound should now work once again!
* added, posibility to have sound action on startup, quit and fileaction.
* bugfix, prevented jeti to enter a eternal loop that used up the cpu.
* if using succless terminal, and it is deklared in the rc, jeti changes the workdir to the latest changed, in case of bringin up a new terminal from jeti, then the workdir of that terminal will be that of jeti. note this will not cynk when opening a terminal from the other window (only the latest)
* jeti should now remember what file he last enterd
> jeti-filemanager: update to 1.2.3

- srcpkgs/intellij-idea-community-edition/template
- srcpkgs/intellij-idea-community-edition/update
Also changes the update-check config to not use the "Previous releases" page, but the current release
> intellij-idea-community-edition: update to 2016.2.1

- srcpkgs/kdelibs/patches/CVE-2016-6232.patch
- srcpkgs/kdelibs/template
Fix for CVE-2016-6232, taken from the kdelibs4 Debian package, patch originally from upstream (karchive) commit 0cb243f64eef45565741b27364cece7d5c349c37.
> kdelibs: add security fix CVE-2016-6232.patch

- srcpkgs/zerotier-one/template
Remove obsolete sed and remove backslashes which were confirmed by upstream to be a formatting glitch in the readme.
> zerotier-one: update to 1.1.14

- srcpkgs/google-chrome/update
Add an update check for google-chrome.  The whatismybrowser site is the only site I've found that reliably updates the google chrome number and has it in a machine parseable format.
> google-chrome: add update check

- srcpkgs/google-chrome/template
This fixes the issue where certain window managers, most notably cinnamon and xfce wouldn't reliably locate the Google Chrome icon.  The icons now reside in the location as suggested by upstream.
> google-chrome: move icons to upstream location

- srcpkgs/virtualbox-ose/patches/005-gsoap-build.patch
- srcpkgs/virtualbox-ose/template
This one does not work for me with the brand new linux kernel 4.7.1.
After building the modules and when trying to load the `vboxdrv` module I see this in `dmesg` output:
```
[   79.279972] vboxdrv: Unknown symbol mod_timer_pinned (err 0)
[   79.280032] vboxdrv: Unknown symbol __get_vm_area (err 0)
[   79.280066] vboxdrv: Unknown symbol set_pages_nx (err 0)
[   79.280099] vboxdrv: Unknown symbol smp_call_function (err 0)
[   79.280157] vboxdrv: Unknown symbol map_vm_area (err 0)
[   79.280202] vboxdrv: Unknown symbol set_pages_x (err 0)
```
So either the kernel is too new for vbox, or we do not have set some config options which are required.
Do not merge until this is solved.
> virtualbox-ose: update to 5.1.4

- srcpkgs/fish-shell/template
fish depends on bc for the shipped autocompletion files. See https://github.com/fish-shell/fish-shell/blob/master/fish.spec.in#L16
Without bc, typing `sudo x` and hitting tab to autocomplete from the fish-shell with throw an error from the completion file stating "command bc not found". Manually installing bc fixes this - but it should be a package dependency :)
> Add fish's dependency "bc"

- srcpkgs/netdata-plugins-nodejs
- srcpkgs/netdata-plugins-python
- srcpkgs/netdata/INSTALL
- srcpkgs/netdata/files/netdata/run
- srcpkgs/netdata/patches/crosstime.patch
- srcpkgs/netdata/template
Technically this also depends on python now, but only for additional plugins.  Given that the core system still works without it I have not added python as a hard depends relation to this package.
> netdata: update to 1.3.0

- srcpkgs/NetworkManager/template
- srcpkgs/glib/patches/gobject_init_on_demand.patch
- srcpkgs/glib/patches/quark_init_on_demand.patch
- srcpkgs/glib/template
- srcpkgs/gobject-introspection/template
Besides the quark init on demand, a similar thing is required for `gobject_init()` in `gobject/gtype.c` for the commands like `g-ir-scan` etc. to work right with musl libc.
This fixes NetworkManager `build_option="gir"` for musl libc.
> glib: fix on demand init for gquark and gtype

- srcpkgs/icedtea-web/template
For the Firefox browser plugin it requires a pkg-config for mozilla-plugin which I am not sure if anything provides yet. An 'xulrunner' package seems to be the first candidate but I don't know much about it.
> New package: icedtea-web

- common/shlibs
- srcpkgs/jbigkit-libs
- srcpkgs/jbigkit/template
- srcpkgs/splix/template
Created a "fork" of jbigkit-2.1 at github which uses autotools
and libtool to create both, shared and static libraries.
Parallel building fails because test programs which depend on the
libraries are built before these (not yet installed) libs.
Therefore disable_parallel_build=yes
> jbigkit: create shared library + splix: fix PIE

- srcpkgs/firefox/template
The rendering bugs we had with gtk3 seem to be fixed.
> firefox: enable gtk3 again

- srcpkgs/vivaldi/template
Resolves vivaldi no start error ``"/usr/bin/vivaldi-stable" (No such file or directory)`` when clicking on vivaldi shortcut in menu. 
Fix syntax error to correct path/name of vivaldi.png so icon appears in menu.
> vivaldi: enable start from menu, show menu icon

- srcpkgs/opam/patches/fix_url.patch
- srcpkgs/opam/template
In opam-1.2.2 there is a broken url in a Makefile, breaking the build process.
This gets fixed in post_extract.
Also, opam depends on unzip, so it is added as a dependency.
> opam: unbreak build process and add unzip to dependencies

- common/shlibs
- srcpkgs/calligra/template
- srcpkgs/clementine/template
- srcpkgs/clipgrab/template
- srcpkgs/freecad/template
- srcpkgs/gpsbabel/template
- srcpkgs/k3b/template
- srcpkgs/kde-runtime/template
- srcpkgs/kde-workspace/template
- srcpkgs/kdelibs/template
- srcpkgs/kdepim/template
- srcpkgs/kdeplasma-addons/template
- srcpkgs/kdevelop/template
- srcpkgs/kdevplatform/template
- srcpkgs/ktorrent/template
- srcpkgs/kvirc/template
- srcpkgs/libkgapi/template
- srcpkgs/marble/template
- srcpkgs/python-PyQt4/template
- srcpkgs/python-pyside/template
- srcpkgs/qt-webkit-devel
- srcpkgs/qt-webkit/files/fix-execinfo.patch
- srcpkgs/qt-webkit/files/fix-gcc6.patch
- srcpkgs/qt-webkit/files/fix-mallinfo.patch
- srcpkgs/qt-webkit/files/qwebview.patch
- srcpkgs/qt-webkit/template
- srcpkgs/qt/template
- srcpkgs/quassel/template
- srcpkgs/tomahawk/template
Instead of the webkit shipped with `qt-4.8.7` (which is impossible to build with gcc6), add a `qt-webkit-2.3.4` package and revbump packages depending on `libQtWebKit.so.4`, adding the new dependency `qt-webkit-devel`.
> New package: qt-webkit-2.3.4

- srcpkgs/obs/template
needed to remove `vmove usr/lib/*.so` from the devel package, otherwise obs would pull it in.
> obs: update to 0.16.1.

- srcpkgs/wine-gecko/template
The current version of wine in void linux needs this newer version of wine-gecko.
The installer was not available on sourceforge, so I switched to downloading from the wine download site.
> wine-gecko: update to 2.47

- srcpkgs/kcov/patches/musl.patch
- srcpkgs/kcov/template
I needed [kcov](http://simonkagstrom.github.io/kcov/index.html) ([GitHub](https://github.com/SimonKagstrom/kcov)) for checking my coverage, so I had to make a package anyway.
> New package: kcov-31

- srcpkgs/inetutils/template
/etc/xinetd.d, not /etc/xinet.d
Also, according to man 5 xinetd.conf,
config files in a directory processed with includedir, such
as /etc/xinetd.d, will be skipped if their names contain
a dot.  So strip the .xinetd suffix when installing.
> inetutils: fix xinetd configs

- srcpkgs/numix-themes/template
Also changed lines 16 and 12 as the upstream tarballs don't have v in there name anymore.
> numix-themes: update to 2.6.4

- srcpkgs/kdepimlibs/patches/CVE-2016-7966.patch
- srcpkgs/kdepimlibs/template
Fixes CVE-2016-7966 using the patch from [176fee25ca79145ab5c8e2275d248f1a46a8d8cf](https://quickgit.kde.org/?p=kdepimlibs.git&a=commitdiff&h=176fee25ca79145ab5c8e2275d248f1a46a8d8cf) as recommended in the [security advisory](https://www.kde.org/info/security/advisory-20161006-1.txt).
> kdepimlibs: add CVE-2016-7966.patch

- srcpkgs/geary/template
I made quite a few changes as well:
- homepage now redirects to the gnome wiki page
- license was wrong
- gnome-keyring: I noticed that it's not linked against libgnome-keyring at all so libgnome-keyring-devel is not required, but `gnome-keyring` itself for storing passwords (otherwise I ran into [this](https://forums.freebsd.org/threads/50155/) issue). I guess it's handled by libsecret instead.
> geary: update to 0.11.2.

- srcpkgs/streamlink/template
Livestreamer is no longer maintained, and streamlink is a livestreamer
fork that is maintained.
> New package: streamlink-0.0.2

- srcpkgs/w_scan/patches/fix-uint.patch
- srcpkgs/w_scan/template
- Build and tested on 64bit glibc.
- Builds and executes in 32bit glibc test environment, not fully tested since there is no TV card present.
- Not tested on musl libc. Maybe someone else can check?
> w_scan: update to 20161022

- srcpkgs/kdepimlibs/patches/CVE-2016-7966_part2.patch
- srcpkgs/kdepimlibs/template
since the last patch for CVE-2016-7966 did not fix the vulnerability entirely
according to the [information`](https://www.kde.org/info/security/advisory-20161006-1.txt) released by the KDE project, this commit adds the
[second patch]( https://quickgit.kde.org/?p=kdepimlibs.git&a=commitdiff&h=8bbe1bd3fdc55f609340edc667ff154b3d2aaab1) released to fix CVE-2016-7966.
> kdepimlibs: add CVE-2016-7966_part2.patch

- srcpkgs/ntp/files/isc-ntpd/run
- srcpkgs/ntp/template
ntpd currently prints it output to tty which is not necessary since ntpd
itself already logs to syslog if a syslog daemon is running. By redirecting
output of the process to /dev/null (stdout and stderr), this is avoided.
> ntpd: redirect output to /dev/null

- srcpkgs/spotify/template
Currently on install you get the following:
```
eater@chino ~ $ sudo xbps-install -Syf spotify                                                                                                                                                                                          
[*] Updating `https://repo.voidlinux.eu/current/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/nonfree/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/nonfree/x86_64-repodata' ...
Name    Action    Version           New version            Download size
spotify reinstall 1.0.42_1          1.0.42_1               -
Size required on disk:          229B
Free space on disk:             23GB …
```
> spotify: fix download link

- srcpkgs/efibootmgr/INSTALL.msg
- srcpkgs/efibootmgr/files/kernel.d/efibootmgr.post-install
- srcpkgs/efibootmgr/files/kernel.d/efibootmgr.post-remove
- srcpkgs/efibootmgr/template
efibootmgr is tool to manipulate the EFI boot entries but thanks to [EFISTUB](https://wiki.archlinux.org/index.php/EFISTUB) it can also be used to create entries to directly boot the kernel which this hook basically does.
I have to note that efibootmgr assumes for example that the disk is `/dev/sda`, this can only be configured through the execution parameters. If you want to I could modify the script so that these options can be defined by the user in something like `/etc/efibootmgr.conf` instead of just the kernel cmdline options.
> efibootmgr: add xbps kernel hook

- srcpkgs/efibootmgr/INSTALL.msg
- srcpkgs/efibootmgr/files/efibootmgr-kernel-hook.confd
- srcpkgs/efibootmgr/files/kernel.d/efibootmgr.post-install
- srcpkgs/efibootmgr/files/kernel.d/efibootmgr.post-remove
- srcpkgs/efibootmgr/template
Also changed the name of the config file, since the syntax
is much different.
See issue #5165 for the discussion.
> efibootmgr: make modifying of boot records optional, disabled by default.

- srcpkgs/gst-plugins-bad/patches/fix-CESA-2016-0002.patch
- srcpkgs/gst-plugins-bad/template
patch taken from the upstream master branch from the following commit
https://cgit.freedesktop.org/gstreamer/gst-plugins-bad/commit/?id=4cb1bcf1422bbcd79c0f683edb7ee85e3f7a31fe
This fixes the vulnerability currently known as CESA-2016-0002, full details available at:
https://scarybeastsecurity.blogspot.de/2016/11/0day-poc-risky-design-decisions-in.html
> gst-plugins-bad: add fix-CESA-2016-0002.patch

- srcpkgs/wireshark/patches/musl.patch
- srcpkgs/wireshark/template
Fixes CVE-2016-9372, CVE-2016-9374, CVE-2016-9376, CVE-2016-9373,
CVE-2016-9375
> wireshark: update to 2.2.2.

- srcpkgs/bash/template
This is a workaround for the problems described in #5204 assuming the bash update is always ordered before the readline update.
> bash: use static readline

- srcpkgs/fish-shell/template
When I press ctrl+c in fish-shell, occurs the error below.
This error doesn't show when groff is installed. 
I added in PR fish-shell how depends on groff
```
⟩ fish: Unknown command 'nroff'
/usr/share/fish/functions/__fish_print_help.fish (line 1): nroff -man -c -t $rLL "$__fish_datadir/man/man1/$item.1" ^/dev/null
^
in command substitution
called on line 0 of file /usr/share/fish/functions/__fish_print_help.fish
in function '__fish_print_help'
called on line 354 of file ~/.config/fish/functions/fish_prompt.fish
with parameter list '--tty-width 169 set'
in command substitution
called on line 352 of file ~/.config/fish/functions/fish_prompt.fish
in function '__dangerous_detach_session'
called on line 103 of file ~/.config/fish/functions/fish_prompt.fish
in function …
```
> fish: add groff runtime dependency.

- srcpkgs/base-chroot-musl/template
If you look at the pkgs set up by ./xbps-src binary-bootstrap x86_64-musl,
you will see kernel-libc-headers being installed, so they should be built
as part of base-chroot-musl.
> base-chroot-musl: add kernel-libc-headers

- srcpkgs/neofetch/template
Turns out when you closed a PR you can't reopen it if you force-push it..
> neofetch: update to 2.0.2

- srcpkgs/net-tools/template
- srcpkgs/traceroute/template
- srcpkgs/util-linux/template
Here are descriptions of the conflicts and my fixes.
inetutils-ifconfig and net-tools:
Both provide the ifconfig alternative group, but the manpage symlink
in net-tools is broken.  It is named ifconfig.1, and it points to
net-tools-ifconfig.8 in /usr/share/man/man1.
Fixed by pointing the ifconfig.1 symlink to
/usr/share/man/man8/ifconfig.8.
inetutils-syslog:
Provides the logger group, which will clobber logger from util-linux when
installed.  Added the logger alternative group to util-linux.
inetutils-traceroute:
Provides the traceroute group, which clobbers things installed by
the traceroute package.
Renamed traceroute's binary and manpage, and the
traceroute package now provides the alternative group.
> Fix various packages that conflict with inetutils alternatives.

- srcpkgs/FreeRADIUS-devel
- srcpkgs/FreeRADIUS/files/FreeRADIUS/run
- srcpkgs/FreeRADIUS/template
Currently marked nocross as the build is very much convinced it needs to execute build artifacts while configuring that have been cross compiled.
> New package: FreeRADIUS-3.0.12

- common/shlibs
- srcpkgs/wps-office/template
Update wps-office to use the packaged libpng instead of the builtin one.
> wps-office: refactor and update

- srcpkgs/adobe-flash-plugin/template
Provides npapi plugin for mozilla browsers.
> adobe-flash-plugin: update to 24.0.0.186

- srcpkgs/salt/patches/fix-grain-init-runit-2016.11.0.patch
- srcpkgs/salt/template
.. while waiting fix in next salt 2016.11.x release.  
See PR  https://github.com/saltstack/salt/pull/38326 for more details
> salt: fix runit support as grain 'init'

- srcpkgs/lutris/template
Removed `python3-xdg` from runtime dependencies.
See [here](https://github.com/lutris/lutris/blob/master/debian/changelog):
>  * Remove dependencies to python3-xdg and xdg-user-dirs
> lutris: update to 0.4.4.1.

- srcpkgs/mpv/template
The last `libass-0.13.5` update causes this error in mpv:
> [osd/libass] [0x7f57a0360560]: Warning: no style named 'Default' found
> mpv: rebuild for libass 0.13.5

- srcpkgs/liblxqt/template
- srcpkgs/libqtxdg/template
- srcpkgs/lxqt-panel/template
- srcpkgs/lxqt-qtplugin/template
Applications like lxqt-powermanagement, qtox, qbittorrent or vlc crash at launch since last Qt5 update due to their tray icon.
Killing lxqt-panel and launching these apps don't crash them anymore.
Rebuilding the following packages fix the issue. Maybe a global rebuilding of LXQt could be wise.
> LXQt: some rebuild in order to fix Qt apps crashes

- srcpkgs/zlib/template
The release announcement for zlib 1.2.10 says:
"zlib 1.2.9 had two serious bugs that are fixed in 1.2.10. If you installed 1.2.9, it would behoove you to replace it as soon as possible with 1.2.10. Thank you, and sorry for any mess this might have created."
/cc @xtraeme
> zlib: update to 1.2.10

- srcpkgs/noto-fonts-cjk/template
- srcpkgs/noto-fonts-emoji/template
- srcpkgs/noto-fonts-ttf/template
This updates noto-fonts-ttf to the latest commit, adds the complementary Noto CJK and Noto Emoji fonts as separate packages, and places all of the Noto fonts into `/usr/share/fonts/noto` folder (mimicking the Cantarell font package).
The source tarball for the Noto CJK fonts is huge (750MB), but the final xbps package comes out to (75MB).  I'd understand if we did not want to put a big file like this in the repository.
> Noto fonts update and reorganization

- common/shlibs
- srcpkgs/glew/template
use `make install.all` instead of `make install` to also install the glewmx lib (see http://glew.sourceforge.net/build.html)
> glew: also install glewmx

- common/chroot-style/proot.sh
This seems to fix #5184 (thanks @ackalker), but in my limited testing also made #4909 occur more often...
> common/chroot-style/proot.sh: disable seccomp

- srcpkgs/libressl/patches/CVE-2016-7056.patch
- srcpkgs/libressl/template
CVE-2016-7056 ECDSA P-256 timing attack key recovery
http://seclists.org/oss-sec/2017/q1/52
> libressl: add patch for CVE-2016-7056

- srcpkgs/xorg-server/template
This option used to be in the template, but was removed again. I wasn't able to find out why.
afaict it's default on most distros, and I use it a whole lot myself.
> xorg-server: enable security extension

- common/shlibs
- srcpkgs/dotherside-devel
- srcpkgs/dotherside/patches/fix-solib-versions.patch
- srcpkgs/dotherside/template
This package is required by some programming languages librairies in order to make Qt QML bindings. This way, for example it is possible to implement some basic GUI with Qt Quick Controls in these languages.
For more informations: https://github.com/filcuc/DOtherSide
> New package: dotherside-0.5.2

- srcpkgs/k3b/template
Dependencies needed to use the application in a meaningful way. Cannot be automatically detected since these are separate binaries and not shared libraries, also see #5438.
> k3b: add cdrtools, cdrdao and dvd+rw-tools into depends

- srcpkgs/mailpile/template
Mailpile won't launch without python-setuptools. It has been a while since I've messed with templates, not sure if I need to remove it from hostmakedepends.
> mailple: Added python-setuptools to depends

- srcpkgs/msttcorefonts/template
I'm not sure if this needs to rebuild the font-cache after it installs.  I didn't have to on my machine, but I can't find a definitive answer of if you need to rebuild the cache after installing fonts.
> New package: msttcorefonts-1.3.4

- srcpkgs/9base/files/plan9.sh
- srcpkgs/9base/template
Alternative plan9 userspace port to plan9port from suckless.  Advantage of this version is that it compiles with musl and can cross-compile using bison (I supply a couple of patches to make the YACC grammars compilable with bison).
> New package: 9base

- srcpkgs/sigil/template
The application throws a ton of errors before startup and then crashes without this python3 package being installed.
> sigil: add necessary python3 dependency; fix cross

- srcpkgs/blueman/patches/musl.patch
- srcpkgs/blueman/template
- srcpkgs/cross-aarch64-linux-musl/template
- srcpkgs/cross-arm-linux-musleabi/template
- srcpkgs/cross-arm-linux-musleabihf/template
- srcpkgs/cross-armv7l-linux-musleabihf/template
- srcpkgs/cross-i686-linux-musl/template
- srcpkgs/cross-mips-linux-musl/template
- srcpkgs/cross-mipsel-linux-musl/template
- srcpkgs/cross-mipsel-linux-muslhf/template
- srcpkgs/cross-x86_64-linux-musl/template
- srcpkgs/kernel-libc-headers/patches/1-5-kernel-libc-compat-musl-support.patch
- srcpkgs/kernel-libc-headers/template
following issue #5786 
still WIP, but NetworkManager 1.0.2 builds (native muslc)
> kernel-libc-headers: musl libc support for compat with linux/*.h

- srcpkgs/fbxkb/patches/fbxkb.patch
- srcpkgs/fbxkb/template
fbxkb is a very lightweight and minimalist, although pretty old (last official update in 2006) X keyboard layout indicator. It's a good choice for lightweight WMs like i3.
I understand that pre-1.0 package with such a long period without maintenance is concerning, but due to its minimal functionality and rather small codebase I don't think it would do any harm. I've been using fbxkb for three month on two distributions and did not have any problems with it.
EDIT: added "only_for_arches" to the template, package didn't build on some architectures.
> New package: fbxkb-0.6

- srcpkgs/ccsm/patches/prefix.patch
- srcpkgs/ccsm/template
The main application prefix was not being set in all places correctly. This is a patch the changes the default prefix from `/usr/local` to `/usr.` It also includes `pygtk` to allow for proper updating of icon themes.
> ccsm: fix icon directory path issue.

- srcpkgs/cpufrequtils/patches/pic-i386.patch
- srcpkgs/cpufrequtils/template
One problem with the `cpuid` instruction is that it uses `%ebx` which,
when code is compiled as PIC for i386, is used as the PIC base register.
This patch tries to handle this case by replacing the second register (`%1`)
constraint with `"=r"`, i.e. any (other) register, and swapping `%ebx` and `%1`
around the `cpuid` instruction.
This patch could use a test, preferably on real i686 hardware.
At least it needs some review and perhaps inspection of the generated
assembler output.
The idea and reasoning was taken from this comment:
http://gcc.gnu.org/ml/gcc-patches/2007-09/msg00324.html
> cpufrequtils: handle i386 -fPIC case

- srcpkgs/python-bitbucket-api/template
Features from python-requests-oauthlib are used in the library, so that
package needs to be a dependency.  python-requests-oauthlib depends on
python-oauthlib, so the latter can safely be removed from the dependency
list without fear of any lost functionality.
> python-bitbucket-api: More encompassing dependency

- srcpkgs/python-smmap/template
python-smmap has a dependency on the base Python install.  Explicitly
adding the python package as a dependency slipped through the cracks
initially because, as a Python library, there are very few use cases
where one would attempt to install smmap without already having the base
language.
The calling of `post_install()` is moved above the python3 subpackage in
the source to be more consistent with other Python packages.
> python-smmap: Add missing dependency on python

- srcpkgs/base-files/files/vkpurge
- srcpkgs/base-files/template
`vkpurge rm 4.10.1_1` does not correctly check if the version is installed and would delete the files anyways, `vkpurge list` and `vkpurge all` use the the correct check.
> base-files: fix vkpurge rm installed check

- srcpkgs/glibc/patches/revert-memchr-i686.patch
- srcpkgs/glibc/template
the changes made in glibc upstream commit 23d27709a423aec32821e9a5198a10267107bae2
cause segmentation faults on at least some i686 processors. This commit
reverts these changes to resolve the issue on affected systems until
there's an upstream fix.
This PR is intended as an alternative to #5752. Since at least some important packages (gnutls, sshd) now link against glib-2.25 symbols, it is now longer feasible to stay on glibc-2.24 on a Void installation. Reverting the repository back to 2.24 would require a rebuild of these packages.
> glibc: revert upstream changes to memchr-sse2

- srcpkgs/gdb/template
When a cross-compiled gdb is built with --with-sysroot, it
looks for shared libraries in the wrong place when installed
to the target system.  So use --with-build-sysroot instead.
> gdb: configure with --with-build-sysroot, not --with-sysroot.

- srcpkgs/cross-aarch64-linux-gnu/template
- srcpkgs/cross-aarch64-linux-musl/template
- srcpkgs/cross-arm-linux-gnueabi/template
- srcpkgs/cross-arm-linux-gnueabihf/template
- srcpkgs/cross-arm-linux-musleabi/template
- srcpkgs/cross-arm-linux-musleabihf/template
- srcpkgs/cross-armv7l-linux-gnueabihf/template
- srcpkgs/cross-armv7l-linux-musleabihf/template
- srcpkgs/cross-i686-linux-musl/template
- srcpkgs/cross-i686-pc-linux-gnu/template
- srcpkgs/cross-mips-linux-musl/template
- srcpkgs/cross-mipsel-linux-musl/template
- srcpkgs/cross-mipsel-linux-muslhf/template
- srcpkgs/cross-vpkg-dummy/template
- srcpkgs/cross-x86_64-linux-musl/template
+ Enable the fortran language for all cross compilers.
+ Update glibc to 2.25 for the cross-*-gnu cross compilers.
+ Enable lapack cross compiling with `<triplet>-gfortran`. (separate PR)
> cross-*: enable fortran cross compilers and update glibc

- srcpkgs/python-github3/template
The former version packaged was 1.0.0a4.  However, 1.0.0a4 is in fact an
alpha release despite being tagged in the upstream Git repository and
being available on PyPI.  This update reverts the package to 0.9.6, the
latest stable release.
The project's PyPI page lists pyOpenSSL, ndg-httpsclient, and pyasn1 as
dependencies.  grepping github3's repository reveals that none of these
libraries are ever imported.  As such, they have all been removed from
the template's depends.
> python-github3: Use stable release, clean depends

- srcpkgs/libcap/patches/gperf-3.1-fix.patch
- srcpkgs/libcap/template
Added a patch from gentoo to allow building with gperf 3.1
> libcap: fix gperf build error

- srcpkgs/perl-Test-Script/template
First build will fail, and for some reason the mirror only has 1.07, 1.15 & 1.16
> perl-Test-Script: update to 1.16

- srcpkgs/kakoune/template
Kakoune is a vim-like text editor, but using a different approach to text editing. It's mostly selection based, uses multiple cursors and has improved (more efficient) key grammar.
Despite being "unreleased" it's pretty usable, I'm using it since late 2015, exclusively since past few months. Did some serious work with it, nothing bad happened.
I've asked the author about versioning scheme, he just said that's only the marketing matter and still not decided about versioning scheme. Kinda weird, but software itself works very well.
> New package: kakoune-20170311

- srcpkgs/speech-dispatcher/patches/spdconfig.patch
- srcpkgs/speech-dispatcher/template
The Python 3 component is just a config file generating tool
and a small client library.  Orca (the biggest user of Speech
Dispatcher) breaks if it isn't available.  The libao audio
driver also seems to be their best one, so build it as well.
> speech-dispatcher: build/install the Python 3 bits and libao driver.

- srcpkgs/xpra/template
Up to and including xpra 1.0.1, connection would always fail with a
Python exception unless pulseaudio was installed. xpra 1.0.2 seems to
have fixed this issue.
> xpra: remove pulseaudio dependency

- common/shlibs
- srcpkgs/xbps/template
We have versioned symbols for glibc, if you update an old system with
the previous glibc release installed, only xbps is updated and breaks
because of those versioned symbols.
Increasing the required glibc version in common/shlibs and bumping xbps
fixes this and would update glibc too if it upates itself.
https://forum.voidlinux.eu/t/update-of-fresh-install-breaking-xbps/2143
> xbps: bump to depend on glibc>=2.25_1

- srcpkgs/inspircd/files/inspircd/run
- srcpkgs/inspircd/template
Without the chown, inspircd just sits there trying to write the PID to a directory that it can't write to.
> inspircd: Fix permissions on /var/run/inspircd

- srcpkgs/jhead/patches/CVE-2016-3822.patch
- srcpkgs/jhead/template
fixes CVE-2016-3822, patch origin:
https://android.googlesource.com/platform/external/jhead/+/bae671597d47b9e5955c4cb742e468cebfd7ca6b
> jhead: add CVE-2016-3822.patch

- srcpkgs/buku/template
This fixes [#6054](https://github.com/voidlinux/void-packages/issues/6054).
> buku: add missing dependency python3-requests

- srcpkgs/openssh/patches/bug2722.patch
- srcpkgs/openssh/patches/config.patch
- srcpkgs/openssh/patches/werror.patch
- srcpkgs/openssh/template
Previous build of OpenSSH 7.5p1 broke due to undefined prototypes for
functions provided by LibreSSL, which then were called according to
the wrong calling convention.
We had this situation before in
https://github.com/OpenSMTPD/OpenSMTPD/issues/691
Build with -Werror now to detect new issues arising in the future.
Remove one obsolete constant value to make this pass.
Check OpenBSD libc functions (partially provided by glibc and musl)
using AC_CHECK_DECLS instead to verify they have a prototype.
Explicitly define prototypes for arc4random* when LibreSSL is detected
(from https://bugzilla.mindrot.org/show_bug.cgi?id=2465)
> openssh: update to 7.5p1.

- srcpkgs/fsharp/template
The F# compiler is required for MonoDevelop. Building is currently broken on musl libc
> New package: fsharp-4.1.0.2

- srcpkgs/mosh/template
- srcpkgs/protobuf/template
I just updated an arm system and got this while connecting via mosh:
`mosh-server: symbol lookup error: mosh-server: undefined symbol: _ZNK6google8protobuf11MessageLite25InitializationErrorStringB5cxx11Ev`
Rebuilding both, protobuf and mosh, solved the problem.
> Mosh rebuild

- srcpkgs/kdoctools/patches/cmake_macro_cross.patch
- srcpkgs/kdoctools/template
some packages use `kdoctools` to generate documentation.
When cross building, the cmake macro selects `meinproc5` executable from the target architecture.
Setting `KDOCTOOLS_MEINPROC_EXECUTABLE` to `meinproc5` prevents this and uses the executable for the host.
> kdoctools: enable cross for dependents

- srcpkgs/speech-dispatcher/template
I forgot to add python3-devel to hostmakedepends in revision
2, so cross builds were still missing the Python bits.
> speech-dispatcher: fix cross.

- srcpkgs/wpa_supplicant/files/config
- srcpkgs/wpa_supplicant/template
This patch also contains:
- a refresh of the 'config' file (copy from wpa_supplicant/defconfig)
- the use of the internal line edit mode instead of the GNU readline
- the control of AP mode operations
Signed-off-by: Jean-Francois Moine <moinejf@free.fr>
> wpa_supplicant: Add P2P support (Wifi Direct)

- srcpkgs/spice-vdagent/files/spice-vdagentd/run
- srcpkgs/spice-vdagent/template
Spice agent does not work correctly without **spice-vdagentd** daemon running. This PR adds service for the daemon.
> spice-vdagent: spice-vdagentd service added

- common/shlibs
- srcpkgs/openjdk/template
required for compiling libreoffice with java support (tested here: https://github.com/juliendehos/void-packages/commit/512dd8cfce43a58a8afad30ed25f9be0647cf995)
> openjdk-jre: add libjawt.so in shlib_provides

- Manual.md
- common/build-style/gnu-makefile.sh
- common/environment/setup/sourcepkg.sh
Cleaner than overwriting `do_build` partially every time we get a good makefile.
Needs a change to unset `good_makefile` as well, so it behaves well.
Tested on the PR of `spt` ( #5883 )
> RFC: gnu-makefile with good makefiles.

- srcpkgs/dynamips/template
- srcpkgs/gns3-gui/template
- srcpkgs/gns3-net-converter/template
- srcpkgs/gns3-server/template
- srcpkgs/iouyap/template
- srcpkgs/python3-aiohttp-cors/template
- srcpkgs/python3-aiohttp/template
- srcpkgs/python3-async-timeout/template
- srcpkgs/python3-multidict/template
- srcpkgs/python3-yarl/template
- srcpkgs/python3-zipstream/template
- srcpkgs/raven-python/template
- srcpkgs/vpcs/patches/ldflags.patch
- srcpkgs/vpcs/patches/readline.patch
- srcpkgs/vpcs/patches/remote_musl.patch
- srcpkgs/vpcs/template
This PR includes GNS3 and all of the required dependencies.  This has been tested to the ability that I could pull off without undue effort.  This includes setting up VirtualBox VMs and Dynamips switches and confirming traffic can be routed between them.  VPCs also work, but some gymnastics are required to get the unique implementation of readline to work on Void.
> New package: gns3

- common/shlibs
- srcpkgs/liblouis/patches/crosspython.patch
- srcpkgs/liblouis/patches/wcharmismatch.patch
- srcpkgs/liblouis/template
Also, build Python 3 bindings.  The only thing that depends on
liblouis is Orca, and Orca needs these.
Build with --enable-ucs4.
To see a justification for why I did that,
have a look at https://bugs.archlinux.org/task/44319
Disable parallel builds; they fail for me.
Make sure .info files are installed.
> liblouis: update to 3.1.0

- srcpkgs/hoogle/template
Hoogle is a search engine for Haskell libraries. I think it's useful to have as a distribution package as it takes some time to compile and updating it by hand from a local stack or cabal installation is not that good of an idea.
> New package: hoogle-5.0.9

- srcpkgs/openvpn/template
Update is because of [the security audit](https://ostif.org/the-openvpn-2-4-0-audit-by-ostif-and-quarkslab-results/) done by ostif and quarkslab
> openvpn: update to 2.4.2

- srcpkgs/feh/template
Currently the icon for feh does not have world read permissions.
> feh: Fix icon permissions

- srcpkgs/vidcutter/template
The Author updated the distfile without version bump (See [AUR](https://aur.archlinux.org/cgit/aur.git/commit/?h=vidcutter&id=22f8f034cb7eff0c03cf3c6e45d471c4e2abacf7))
Something like this has happened in the [past](https://github.com/voidlinux/void-packages/pull/5651).
> vidcutter: distfile checksum changed

- srcpkgs/i3blocks/patches/fix_musl.patch
- srcpkgs/i3blocks/template
i3blocks errors during build on musl with:
src/sched.c:34:17: error: 'sigset' redeclared as different kind of symbol
static sigset_t sigset;
^~~~~~
In file included from src/sched.c:21:0:
/usr/include/signal.h:231:8: note: previous declaration of 'sigset' was here
void (*sigset(int, void (*)(int)))(int);
^~~~~~
make: *** [<builtin>: src/sched.o] Error 1
make: *** Waiting for unfinished jobs....
I did the first thing that came to my mind, which was `:%s/sigset\([^_]\)/sigset_ng\1/g`.
This seem to fix the issue.
> i3blocks: fix musl

- srcpkgs/mate-power-manager/template
> mate-power-manage: needs upower0 on runtime.

- srcpkgs/orca/template
Contracted braille breaks if we can't find the .pc file for
liblouis at build time, so liblouis-devel belongs in makedepends.
> orca: fix build-time detection of liblouis.

- srcpkgs/libtasn1/patches/CVE-2017-6891.patch
- srcpkgs/libtasn1/template
fixes CVE-2017-6891. Patch taken from upstream git commit
5520704d075802df25ce4ffccc010ba1641bd484
> libtasn1: add CVE-2017-6891.patch

- srcpkgs/samba/patches/CVE-2017-7494.patch
- srcpkgs/samba/template
fixes CVE-2017-6891, patch from upstream via Debian.
> samba: add CVE-2017-6891.patch

- srcpkgs/linux4.11/patches/iommu-amd-flush-IOTLB-for-specific-domains-only-v2.patch
- srcpkgs/linux4.11/template
see:
https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-amdgpu/+bug/1683184
patch:
https://patchwork.freedesktop.org/series/21684/
I used this patch on 4.11.2 a few days and on 4.11.3 since the template was updated to .3
Without this patch, my machine doesn't boot stable unless i use iommu=soft cmdline option.
> linux4.11: fix iommu error on AMD processors

- srcpkgs/broadcom-wl-dkms/patches/linux-4.11.patch
- srcpkgs/broadcom-wl-dkms/template
patch via Arch:
https://aur.archlinux.org/cgit/aur.git/tree/linux411.patch?h=broadcom-wl
> broadcom-wl-dkms: fix building with linux-4.11

- srcpkgs/python-axolotl-curve25519/template
- srcpkgs/python-axolotl/template
- srcpkgs/python3-axolotl
- srcpkgs/python3-axolotl-curve25519
Port of libaxolotl-android written by Moxie Marlinspike.
This provides the underlying cryptographic support for the OMEMO XMPP extension. In particular, installing this package allow gajim users to download and enable the OMEMO plugin.
> New package: python-axolotl-0.1.39

- srcpkgs/atom/patches/desktop.patch
- srcpkgs/atom/template
The current (1.17.0-1) .desktop file does not point correctly to the icon. In this pull request, the issue has been fixed.
> atom: Fix icon in desktop entry

- srcpkgs/mutter/patches/meta-backend-x11.patch
- srcpkgs/mutter/patches/meta-renderer-x11.patch
- srcpkgs/mutter/template
these patches fix a [known](https://bugzilla.gnome.org/show_bug.cgi?id=781835) annoying bug upstream that causes terrible performance in gnome when using nvidia GPUs. This works great on my x86_64 machine with nvidia and in my testing VM but i've not tried anything outside of them.
> mutter: revert a upstream commit

- srcpkgs/linux4.4/template
Looking at the Arch [package](https://aur.archlinux.org/cgit/aur.git/commit/?h=linux-lts44&id=397c6b3cd93812ca2bf292db21a8d1ab46912b01), it _seems like_ there's no change since the last release 4.4.69.
> linux4.4: update to 4.4.70

- srcpkgs/nvidia/template
the `nvidia` template was missing the file `nvidia_icd.json` in the vinstall step, resulting in `VK_ERROR_INITIALIZATION_FAILED` errors trying to use vulkan
> nvidia: added missing vulkan icd file to vinstall

- srcpkgs/qemu/template
This pull request disables sdl support in qemu and replaces it with gtk3.
> qemu: disable sdl by default, use gtk instead

- srcpkgs/unison/template
Currently, when unison is run on Void Linux with `repeat -watch`, it spits out an error about no file watching utility being present. Locate reveals that `unison-fsmonitor` is missing. 
Poking around with xbps-src, the binary is built but not installed. This commit modifies the template to install it. `unison repeat -watch` functions correctly with this change.
> unison: install unison-fsmonitor utility

- srcpkgs/sddm/patches/0001-Fix-Avatars.patch
- srcpkgs/sddm/template
sddm 0.14.0 introduced an issue with displaying user avatars.  The
simple fix was committed to master, but wasn't released.
https://github.com/sddm/sddm/issues/807
It looks like at least Arch and Gentoo include this patch, as it's rather
simple but provides a major advantage.  It's not clear when sddm
plans to have a new release.
> sddm: fix display of user avatars

- srcpkgs/libogre/template
Our libogre build doesn't support any image formats other than dds (no png, jpg, etc). For better support it needs to link to devil or freeimage.
I've gone with freeimage here, as that's what the ogre folks choose as default.
> libogre: build against freeimage

- srcpkgs/xf86-video-intel/template
Same commit as the Arch [package](https://www.archlinux.org/packages/extra/x86_64/xf86-video-intel/).
> xf86-video-intel: update to 2.99.917.56

- common/environment/setup/misc.sh
New url and https for xorg, path stays the same.
> xbps-src: use https and new url for XORG_SITE

- srcpkgs/openldap/template
openldap-32bit is currently not on the repo. 
#6680
> openldap: rebuild for repo

- srcpkgs/libvirt/template
distfiles URL changed to http for now because they use a StartCom certificate
which is no longer trusted
> libvirt: update to 3.4.0

- srcpkgs/mcabber/template
distfiles URL changed to http for now because they use a StartCom certificate which is no longer trusted
> mcabber: update to 1.1.0

- srcpkgs/vivaldi/template
Now Vivaldi is only for x86_64, see the [website](https://vivaldi.com/download/) and the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vivaldi) from AUR.
> vivaldi: update to 1.10.867.38

- srcpkgs/compton-git/template
Back to the same repository as the Arch [package](https://www.archlinux.org/packages/community-testing/x86_64/compton/).
> compton-git: update to 20170430

- srcpkgs/jbig2dec/patches/CVE-2017-7885.patch
- srcpkgs/jbig2dec/patches/CVE-2017-7975.patch
- srcpkgs/jbig2dec/patches/CVE-2017-7976.patch
- srcpkgs/jbig2dec/template
fixes CVE-2017-7885, CVE-2017-7975 and CVE-2017-7976.
Patches taken from the upstream ghostpdl git repository,
http://git.ghostscript.com/?p=ghostpdl.git
git revisions
e24e6194ca59d7b556116451490f71d2d85f4642
1a624d1bfa1e63ceab87f5e4e22c3daffa2d0f01 and
04b37bbce174eed24edec7ad5b920eb93db4d47d
> jbig2dec: add patches for multiple CVEs

- srcpkgs/musl/patches/bigstack-option.patch
- srcpkgs/musl/template
This enables building musl with a bigger default pthread stack size
(currently 8MB to match glibc default stack size), to make it easier to
diagnose these issues.
#4147
> musl: add bigstack build option

- srcpkgs/keepassxc/template
https://github.com/keepassxreboot/keepassxc/releases/tag/2.2.0
also added GPL-2, and removed GPL-3 since it is provided.
> keepassxc: update to 2.2.0

- srcpkgs/xorg-server/patches/CVE-2017-10971.patch
- srcpkgs/xorg-server/patches/CVE-2017-10972.patch
- srcpkgs/xorg-server/template
fixes CVE-2017-10971 and CVE-2017-10972, patches from upstream, commits:
ba336b24052122b136486961c82deac76bbde455
8caed4df36b1f802b4992edcfd282cbeeec35d9d
215f894965df5fb0bb45b107d84524e700d2073c and
05442de962d3dc624f79fc1a00eca3ffc5489ced
> xorg-server: add CVE-2017-10971.patch and CVE-2017-10972.patch

- srcpkgs/haveged/template
The distfiles was missing. 
````
$ xgensum -f srcpkgs/haveged/template
=> haveged-1.9.1_6: running do-fetch hook: 00-distfiles ...
=> haveged-1.9.1_6: fetching distfile 'haveged-1.9.1.tar.gz'...
looking up distfiles.alpinelinux.org
connecting to distfiles.alpinelinux.org:80
requesting http://distfiles.alpinelinux.org/distfiles/haveged-1.9.1.tar.gz
http://distfiles.alpinelinux.org/distfiles/haveged-1.9.1.tar.gz: Not Found
=> ERROR: haveged-1.9.1_6: failed to fetch haveged-1.9.1.tar.gz.
````
> haveged: fix missing distfiles

- srcpkgs/busybox/template
> Bug fix release. 1.27.1 has fixes for uuencode (allow space
> instead of "`" as padding char), dd (fixed status=none),
> setpriv (option parsing should not eat options in PROG ARGS),
> fix for "applet (for example halt) as login shell" use case,
> a few fixes for less typical build environments.
> busybox: update to 1.27.1

- common/shlibs
- srcpkgs/ccsm/template
- srcpkgs/compiz-bcop/template
- srcpkgs/compiz-core/template
- srcpkgs/compizconfig-python/template
- srcpkgs/libcompizconfig/template
Update compiz-reloaded from 0.8.12.x to 0.8.14. .
This PR will at first attempted to update all compiz packages, that failed.
EDIT: the all-in-one PR has failed. Thus emerald will be in another PR and the comiz-plugins-* will be in yet another PR.
> compiz: update to 0.8.14

- srcpkgs/deadbeef/patches/fix-narrowing_arm.patch
- srcpkgs/deadbeef/template
I've experienced errors with GTK+3 version of deadbeef such as broken progress bar:
Compiling with GTK+2 fixes this error:
> deadbeef: Allow building with GTK2 using build options

- srcpkgs/intellij-idea-community-edition/template
Also move to nonfree, which fixes #7094, and remove a few additional unnecessary natives.
> intellij-idea-community-edition: update to 2017.2.

- srcpkgs/onedrive-d/template
a few changes, including a recent commit which fixes a major problem that I and some others were experiencing, which simply caused onedrive to crash whenever it attempted to sync.
> onedrive-d: update to 0.0.0.20170702

- common/shlibs
- srcpkgs/emerald-themes/template
- srcpkgs/emerald/patches/CCfix.patch
- srcpkgs/emerald/template
This is part 3 of 3 for the compiz upgrade.
compiz core packages. [done]
compiz-plugin-* packages [done]
emerald packages []
Note: The lovely folks over at Compiz-Reloaded  have made it so emerald will not cross compile because of ... interesting.... decisions about their configure.ac file. I have applied a patch that fixes the issue and allows for cross compiling.
> emerald: update to 0.8.14

- srcpkgs/ADMS-qucs/template
- srcpkgs/perl-XML-LibXML/template
- srcpkgs/qucs/template
From the wikipedia description: 
Quite Universal Circuit Simulator (Qucs) is an open-source electronics circuit simulator software released under GPL. It gives you the ability to set up a circuit with a graphical user interface and simulate the large-signal, small-signal and noise behaviour of the circuit. Pure digital simulations are also supported using VHDL and/or Verilog.
This includes two dependencies:
* ADMS-qucs : A fork of ADMS ("Automatic Device Model Synthesizer"), which is used to create .C source from Verilog files. The original ADMS project has gone stale. 
* perl-XML-LibXML: A perl binding for the libxml2 library. Note that the current version of libxml2 (2.9.4) is marked as "broken" by perl-XML-LibXML, but it passes all regression tests.
> New package: qucs-0.0.19 

- srcpkgs/kernel-libc-headers/patches/2220fc1ab363e6fab1f321430d69be17a8b92bd7.patch
- srcpkgs/kernel-libc-headers/template
Required by the chromium 59+ build.
> kernel-libc-headers: ship linux/dma-buf.h

- srcpkgs/oracle-jdk/template
"Java SE 8u144 includes important bug fixes. Oracle strongly recommends that all Java SE 8 users upgrade to this release."
> oracle-jdk: update to 8u144

- srcpkgs/oracle-jre/template
"Java SE 8u144 includes important bug fixes. Oracle strongly recommends that all Java SE 8 users upgrade to this release."
> oracle-jre: update to 8u144

- srcpkgs/opencv/template
"OpenCV now can use vendor-provided OpenVX and LAPACK/BLAS (including Intel MKL, Apple’s Accelerate, OpenBLAS and Atlas) for acceleration" (http://opencv.org/opencv-3-2.html)
I've run some tests and obtained a x8 speed-up.
> opencv: enable openblas support

- srcpkgs/gnome-online-accounts/template
* Corrected the homepage link and set the right license [License](https://git.gnome.org/browse/gnome-online-accounts/tree/COPYING)
> gnome-online-accounts: update to 3.24.2

- srcpkgs/gdk-pixbuf/template
Fixes [#7151](https://github.com/voidlinux/void-packages/issues/7151).
> gdk-pixbuf: update to 2.36.8

- srcpkgs/tumbler/template
> tumbler: update to 0.2.0

- common/shlibs
1. I found this when I was trying to build [gala](https://github.com/elementary/gala). 
2. Seems like there's a problem with `mutter-devel` package: `libmutter` is not correctly detected when we try to build gala, we discussed it on the forum.
> common/shlibs: cleanup

- srcpkgs/keybase/template
Since keybase don't really support their actual release tags and advices people to follow pre-release I feel we should too since you actually face problems if you don't
1: https://github.com/keybase/client/issues/7907
2: https://github.com/keybase/client/issues/8110
3: See their release log: https://github.com/keybase/client/releases , it's full of holes!
> keybase: update to 1.0.28-20170815161818+fed6e3db9

- srcpkgs/libdwarf/template
According to the README:
<pre>When cross-compiling, gennames has to be built by the
native compiler. So try
make HOSTCC=cc gennames
as a first step before the normal make.</pre>
I adjusted `make_cmd` and fixed an error in the `Makefile` where the $HOSTCC used (target) $LDFLAGS.
The `gennames` binary is just used for building purposes and not in the final package.
> libdwarf: fix cross-compilation

- common/shlibs
- srcpkgs/ffmpeg/template
- srcpkgs/libvidstab/template
I was preparing a template for vid.stab and after finishing I realised it’s already there as libvidstab. So I decided to open a pull request to update the package. But that leads me to a question about naming conventions. The [manual](https://github.com/voidlinux/void-packages/blob/master/Manual.md#libs) says:
> Libraries are packages which provide shared objects (*.so) in /usr/lib. They should be named like their upstream package name with the following exceptions:
> 
> The package is a subpackage of a front end application and provides shared objects used by the base package and other third party libraries. In that case it should be prefixed with 'lib'. An exception from that rule is: If an executable is only used for building that package, it moves to the -devel package.
The way I …
> libvidstab: update to 1.1.0

- srcpkgs/kodi-rpi/template
- srcpkgs/kodi/patches/crossguid-0.2.patch
- srcpkgs/kodi/template
Building of the kodi-rpi update in #7485 failed because crossguid was updated in the meantime and kodi still uses a version based on the incompatible 0.1 branch. Building the version bundled by kodi fails when cross-compiling so I added a small patch to build kodi against the current version from the repository.
> Fix building kodi/kodi-rpi against crossguid-0.2.x

- srcpkgs/gnustep-make/template
Installation process was leaving some parts of the bootstrapped env in the final script.
I wasn't sure what to do with the `-specs` thing, but it seems to be effectively adding `-fPIC` as appropriate. Since for building packages, the env should add it anyway I think it is safe to just leave it out.
Feel free to provide better solution(s), of course.
Fixes #7074
> gnustep-make: Fix vars in config.make

- srcpkgs/octoxbps/patches/no-force.patch
- srcpkgs/octoxbps/template
As it has already been discussed a few times, this is a dangerous flag to have in a package managing too, especially if user's may not be aware of it.
Whover wants to --force on his xbps-system, should do that on the terminal.
> octoxbps: don't use --force

- srcpkgs/rng-tools/INSTALL.msg
- srcpkgs/rng-tools/patches/musl-needs-limits_h-include.patch
- srcpkgs/rng-tools/template
Note that this update required a minor patch for compilation with
musl, and that the upstream location has moved.
Also note the command line options for rngd have changed.
> rng-tools: update to version 6

- srcpkgs/st/template
dl.suckless.org now supports TLS using LetsEncrypt
> st: get distfiles from https

- srcpkgs/dmenu/template
dl.suckless.org now supports TLS using LetsEncrypt
> dmenu: get distfiles from https

- srcpkgs/chromium/patches/0002-replace-struct-ucontext-with-ucontext_t.patch
- srcpkgs/chromium/patches/no-getcontext.patch
These two patches make chromium compile with the new glibc. See #7599 and #7164. I've briefly verified that the compiled browser works as intended.
> Fixed chromium compilation with new glibc

- common/travis/prepare.sh
This PR switches travis to an US mirror. This should result in less traffic on the main repository and faster build times on travis as the bits don't have to cross oceans anymore.
> common/travis: switch to mirror for travis builds

- srcpkgs/sublime-text3/template
Hello,
because the sublime-text3 package was pretty outdated, I updated it.
I did bump the version number, so the right tarball gets fetched. Furthermore I updated the checksums.
On my machine both packages build using xbps-src and the 64bit version installed.
Because this is my first pull request on a big project and voidlinux, please correct me if I'm doing something wrong.
> sublime-text3: updated to build 3143

- srcpkgs/thunderbird/patches/freetype-skia.patch
- srcpkgs/thunderbird/template
After the recent freetype upgrade, font rendering in thunderbird was
messed up because of issues with the bundled Skia library as documented
in https://bugzilla.mozilla.org/show_bug.cgi?id=1393467 . This commit
adds the patch from https://bugzilla.mozilla.org/attachment.cgi?id=8904705
which is a backported version of the Skia fix for Firefox 52 ESR and also
applies to the Skia version bundled with thunderbird.
> thunderbird: add patch to fix font rendering issue with freetype 2.8.1

- srcpkgs/libcaca/template
According to `img2txt`’s manpage libcaca needs imlib2 to load other image formats than regular BMP files. 
Because `imlib2-devel` needs `libX11-devel` (else the build fails with `/usr/include/Imlib2.h:28:22: fatal error: X11/Xlib.h: No such file or directory`; it’s not a package dependency, though) and there already is a build option ‘x11’ I just added `imlib2-devel` to that option and didn’t enable it per default.
Alternatively one could add `libX11-devel` as a dependency to `imlib2-devel` (should it be added anyway because Imlib2.h includes Xlib.h?) and add an extra build option.
> libcaca: add (optional) support for imlib2

- srcpkgs/tbb/patches/hostname-usage.patch
- srcpkgs/tbb/template
- srcpkgs/tbb/update
More details:
* update to last version
* fix crossbuild support and unbreak musl support: fix #4317
As QA, `oce` can be now crossbuilded (subsequent PR)
* support new numbering scheme (like '2017_U7')
* update check is fine now
* no ABI changes: checked using `freecad` and `embree`
> tbb: update to 2018, unbreak crossbuild and musl support

- srcpkgs/qt5/patches/skia-freetype.patch
- srcpkgs/qt5/template
Since the chromium environment shipped with qt-webengine also bundles
the skia library, it is affected by the same font rendering issues as
the mozilla products with freetype 2.8.1. This commit adds the patch
backported for Firefox ESR from
https://bug1393467.bmoattachments.org/attachment.cgi?id=8904705 which also
applies to the skia version bundled with qt-5.8.
> qt5: add fix for font rendering issues in qt-webengine

- common/build-style/meson.sh
This should address (or begin to address) #7656.
I've tested this with armv6, armv6l-musl, armv7l for the ncmpc and fuse-sshfs packages.
> meson: add preliminary support for cross compilation

- srcpkgs/oce/template
Following crossbuild fix and update of tbb (PR #7745), related to issue #4317.  
Probably too big for Travis CI, but my personal cross-build are fine.
> oce: unbreak crossbuild

- Manual.md
following discussion in issue #7805
> Manual.md: no underscore or shell subst allowed in version

- srcpkgs/breeze-gtk/template
Closes #7762
For GTK3 versions >= 3.20 `WITH_GTK3_VERSION` needs to be set. (default is 3.18)
`BUILD_TESTING` is not used.
> breeze-gtk: fix gtk3

- srcpkgs/gnome-maps/template
without them gnome-maps is just complaining that they are missing.
> gnome-maps: add geoclue and gfbgraph to dependencies

- srcpkgs/dbus/template
* Minor bigfix release [Changelog](https://cgit.freedesktop.org/dbus/dbus/tree/NEWS?h=dbus-1.10)
* Compiles fine locally on x86_64{-musl} , armv7l{-musl} and aarch64{-musl}
> dbus: update to 1.10.24

- srcpkgs/blackbox_exporter/template
Group names may only be up to 16 chars long, so the install script fails to create the group `_blackbox_exporter`.
> blackbox_exporter: shorten name of system account.

- srcpkgs/SDL2/template
- srcpkgs/logstalgia/template
- srcpkgs/mgba/template
- srcpkgs/qtox/template
Linking against SDL2 currently fails on armv[67] because ld apparently can't find libbcm-host.so. 
Better solutions?
> SDL2: add -rpath=/opt/vc/lib on rpi archs 

- srcpkgs/eog/patches/fix-markdown-itstool.patch
- srcpkgs/eog/template
resolves #8238
the fix is a combination of the following commits https://github.com/GNOME/eog/commit/382503eff951270eaa833245b7ac4bf551e52d79 https://github.com/GNOME/eog/commit/8ac2e6bf805c5accf88495f14fa903cbb904dc86 they were added after the 3.26.1 bump, when 3.26.2 comes the patch should be removed
Tested only on x86_64
> eog: update to 3.26.1.

- srcpkgs/gnote/template
Testing has shown that trying to use a custom font causes segfault ( also applies to 3.24.1 )
```
(gnote:7739): Gtk-CRITICAL **: file gtkcssenumvalue.c: line 528 (_gtk_css_font_weight_value_new): should not be reached
fish: “gnote” terminated by signal SIGSEGV (Address boundary error)
```
but i don't have the full gnome stack installed and running.
> gnote: update to 3.26.0.

- srcpkgs/gnome-desktop/template
- srcpkgs/gnome-session/template
- srcpkgs/gnome-settings-daemon/template
- srcpkgs/gnome-shell-extensions/template
- srcpkgs/gnome-shell/template
- srcpkgs/mutter/template
* This PR bumps the core gnome libs to `3.26.1` as updating them one at a time can cause issues in some cases
> Gnome core: update to 3.26.1

- srcpkgs/avrdude/template
I found that avrdude compiles without patches on alpine.
Testing: I build avrdude for x86_64-musl, installed it and made it initate communication with an AVR device.
> avrdude: enable cross

- srcpkgs/perl-X11-Protocol-Other/template
- srcpkgs/perl-X11-Protocol/template
Fixes cross-compilation issues by adding `perl` to `makedepends`
This also includes a commit that adds the same thing to perl-X11-Protocol so it can be cross-compiled too.
> perl-X11-Protocol-Other: update to 30.

- srcpkgs/cross-aarch64-linux-gnu/template
- srcpkgs/cross-arm-linux-gnueabi/template
- srcpkgs/cross-arm-linux-gnueabihf/template
- srcpkgs/cross-armv7l-linux-gnueabihf/template
- srcpkgs/cross-i686-pc-linux-gnu/template
follow-up to #7928 regarding #7846
> Build glibc with --enable-obsolete-nsl for the cross-* packages

- srcpkgs/gtkglextmm/template
Just removed `nocross`. The package seems to build fine now.
> gtkglextmm: fix cross compilation

- README.md
When building packages with -N there is a dependency loop between gtk+3 and colord.
Describe how to break out of this loop without falling back to using central repository files.
This is required for e.g. i686-musl because there is no existing gtk+3 or colord package.
> README.md: describe breaking dependency loop

- srcpkgs/syncthing-gtk/template
Without python-gobject, syncthing-gtk fails with:
```
Traceback (most recent call last):
File "/usr/bin/syncthing-gtk", line 2, in <module>
import sys, os, signal, gi
ImportError: No module named gi
```
> syncthing-gtk: add python-gobject to depends

- srcpkgs/tectonic/template
Tectonic is a modernized, complete, self-contained TeX/LaTeX engine
website: https://tectonic-typesetting.github.io
> New package: tectonic-0.1.7

- srcpkgs/evtest/template
evtest displays information on the input device specified on the command line, including all the events supported by the device. It then monitors the device and displays all the events layer events generated.
> New package: evtest-1.33_1

- srcpkgs/khard/template
- srcpkgs/python-ruamel.yaml/template
- srcpkgs/python3-ruamel.yaml
New dependencies: `python3-Unidecode`, `python3-ruamel-yaml` (new package)
original name is ruamel.yaml on PYPI and ruamel/yaml on BitBucket (homepage) so i just used dash ( - )
> khard: update to 0.12.0.

- srcpkgs/python-neovim/template
> python-neovim: fix python-msgpack name change.

- srcpkgs/mcabber/template
Install `mcabberrc.example` to `/usr/share/doc/mcabber/` for reference.
> mcabber: add mcabberrc.example

- srcpkgs/helm/patches/fix-musl.patch
- srcpkgs/helm/patches/fix_sigemptyset.patch
- srcpkgs/helm/template
The musl patch is the one form libopenshot-audio with patched paths.
Also the fix_sigemptyset.patch was failing locally because of different line endings (the source code uses DOS ones). It seems like it got converted when it was meged.
> helm: fix musl and recreate fix_sigemptyset.patch

- srcpkgs/kickassembler/template
Also x65xx assembler, but mostly targeted at C64: http://www.theweb.dk/KickAssembler/
Contains the very featureful metaprogramming "language".
I've used the `plantuml` package as a boilerplate to generate shell loader and store JAR in its own directory.
> New package: kickassembler-4.19

- srcpkgs/kakoune/template
• Still no release (but I've starting pushing @mawww a little and he's going to do it very soon I think)
• No runtime deps beyond `ncurses` (boost was kicked out when he made its own regexp impl)
• Everything's a bit more faster and sensible.
Release "issues" for reference:
mawww/kakoune#1019
mawww/kakoune#315
mawww/kakoune#89
mawww/kakoune#249
> kakoune: update to 0.0.20180301

- Manual.md
- common/hooks/do-fetch/00-distfiles.sh
Add support for contents checksums. This is meant to be used for tarballs
like the ones coming from https://*.googlesource.com/ which on every download
change their outer checksum due to being packaged with different date/time
stamps or similar.
If such a distfile still contains the same files as the author of a template
found, then the checksum of its contents can be specified by prepending a
commercial at (@) to the corresponding checksum="..." line.
Depending on the format of the distfile its entire contents will then be
piped into sha256sum and the resulting digest is verified against what
follows after the @.
An example is the pending package addition of [gyp](https://github.com/voidlinux/void-packages/pull/11729). The following template uses the tarball:
```
pkgname=gyp …
```
> hooks/do-fetch/00-distfiles.sh: contents checksum

- srcpkgs/vice/template
• GTK3 UI has more convenient monitor/debugger than SDL2 UI, and it's overall "better" for development purposes
• SDL UI has been upgraded to SDL2 as it's supported since 3.x. I'm still leaving it as it is because it's more suitable for ad-hoc emulation/gaming.
• I've merged GTK3 vopt with Pulseaudio and told the SDL UI to use SDL's sound subsystem instead (to reduce redundancy, there's no added latency)
**BUT**: I wanted to add `ReSID(fp)` which is the "real" SID emulation (with filters) instead of the "fast SID" emulation, the buildsystem says something weird:
```
configure: WARNING: g++ is not the intended cross-compiler, ReSID will not be configured
```
Surprisinglyy, when compiled out of the `xbps-src`, it builds fine with ReSID too. What could be wrong here?
> vice: switch to GTK3 UI by default, replace SDL with SDL2

- srcpkgs/elogind/template
This ensures that arguments to install_items are space separated when
more than one install_item is present in the dracut configuration.
> elogind: ensure valid install_items syntax

- common/xbps-src/shutils/common.sh
This commit makes xbps-src print stacktraces when an error occured:
> common/xbps-src: add stacktraces on build errors

- srcpkgs/rust/patches/link-musl-dynamically.patch
- srcpkgs/rust/template
Builds on x86_64, x86_64-musl and i686.
Also, the new rustc is able to build firefox on all supported architectures (needs reduced level of debuginfo on i686 to prevent  running out of memory).
> rust: update to 1.25.0. [CI Skip]

- common/shlibs
- srcpkgs/nvidia/files/nvidia-swiotlb-linux_4_16.patch
- srcpkgs/nvidia/files/nvidia-x86_64-uvm8_va_block-linux_4_14_9.patch
- srcpkgs/nvidia/template
this doesn't fix broken drivers on linux4.16 but it does fix screen flickering when composition pipeline is on on 4.15
> nvidia: update to 390.48

- srcpkgs/cava-gui/template
Portaudio input support has been added to the project since 0.6.1 and it hasn't been included.
> cava-gui: missing portaudio dependency

- srcpkgs/SDL2/template
We can use desktop OpenGL as well as X11 with the open source
graphics stack on Tegra hardware besides others, so enable
options to match x86.
I'm currently in process of porting Void to the Google Pixel C tablet and this is so that SDL2 games and other applications can work properly under X11 with the open source graphics stack. Additionally, enable OpenGL ES in addition to desktop GL.
> SDL2: enable x11, opengl and pulse on aarch64

- srcpkgs/emacs/template
Marking as WIP while I test it for a bit, compiles and runs in text mode at least on x86_64-musl.
Dropping usage of unencypted POP3 fetching and using groups to store site-wide highscores.
> [WIP] emacs: update to 26.1.
